// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/code_generation_rule (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/code_generation_rule UseCase
//

// Package mock_code_generation_rule is a generated GoMock package.
package mock_code_generation_rule

import (
	context "context"
	reflect "reflect"

	code_generation_rule "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/code_generation_rule"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// ExistenceCheckPrefix mocks base method.
func (m *MockUseCase) ExistenceCheckPrefix(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistenceCheckPrefix", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistenceCheckPrefix indicates an expected call of ExistenceCheckPrefix.
func (mr *MockUseCaseMockRecorder) ExistenceCheckPrefix(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistenceCheckPrefix", reflect.TypeOf((*MockUseCase)(nil).ExistenceCheckPrefix), arg0, arg1)
}

// Generate mocks base method.
func (m *MockUseCase) Generate(arg0 context.Context, arg1 uuid.UUID, arg2 code_generation_rule.GenerateOptions) (*code_generation_rule.CodeList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*code_generation_rule.CodeList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockUseCaseMockRecorder) Generate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUseCase)(nil).Generate), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockUseCase) Get(arg0 context.Context, arg1 uuid.UUID) (*code_generation_rule.CodeGenerationRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*code_generation_rule.CodeGenerationRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUseCaseMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUseCase)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockUseCase) List(arg0 context.Context) (*code_generation_rule.CodeGenerationRuleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(*code_generation_rule.CodeGenerationRuleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUseCaseMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUseCase)(nil).List), arg0)
}

// Patch mocks base method.
func (m *MockUseCase) Patch(arg0 context.Context, arg1 *code_generation_rule.CodeGenerationRule) (*code_generation_rule.CodeGenerationRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", arg0, arg1)
	ret0, _ := ret[0].(*code_generation_rule.CodeGenerationRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockUseCaseMockRecorder) Patch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockUseCase)(nil).Patch), arg0, arg1)
}

// Upgrade mocks base method.
func (m *MockUseCase) Upgrade(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockUseCaseMockRecorder) Upgrade(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockUseCase)(nil).Upgrade), arg0)
}
