// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameKnowledgeNetworkInfoDetail = "t_knowledge_network_info_detail"

// KnowledgeNetworkInfoDetail mapped from table <t_knowledge_network_info_detail>
type KnowledgeNetworkInfoDetail struct {
	ID     string  `gorm:"column:f_id;not null;comment:逻辑主键，与t_knowledge_network_info的f_id字段一致" json:"id"` // 逻辑主键，与t_knowledge_network_info的f_id字段一致
	Detail *string `gorm:"column:f_detail;comment:详细信息" json:"detail"`                                     // 详细信息
}

func (m *KnowledgeNetworkInfoDetail) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = uuid.NewString()
	}

	return nil
}

// TableName KnowledgeNetworkInfoDetail's table name
func (*KnowledgeNetworkInfoDetail) TableName() string {
	return TableNameKnowledgeNetworkInfoDetail
}
