// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"time"
)

const TableNameTAgent = "t_agent"

// TAgent mapped from table <t_agent>
type TAgent struct {
	AgentID     int64     `gorm:"column:agent_id;not null;comment:af 智能体id" json:"agent_id"`             // af 智能体id
	ID          string    `gorm:"column:id;primaryKey;comment:智能体id" json:"id"`                          // 智能体id
	AdpAgentKey string    `gorm:"column:adp_agent_key;not null;comment:adp 智能体key" json:"adp_agent_key"` // adp 智能体id
	DeletedAt   int64     `gorm:"column:deleted_at;not null;comment:是否删除" json:"deleted_at"`             // 是否删除
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`
}

// TableName TAgent's table name
func (*TAgent) TableName() string {
	return TableNameTAgent
}

func (d *TAgent) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.AgentID == 0 {
		uniqueID, idErr := utilities.GetUniqueID()
		d.AgentID, err = int64(uniqueID), idErr
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}

func (d *TAgent) BeforeUpdate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return nil
}
