// Code generated by MockGen. DO NOT EDIT.
// Source: domain/tc_project/project.go

// Package mock_tc_project is a generated GoMock package.
package impl

import (
	context "context"
	reflect "reflect"

	"github.com/kweaver-ai/dsg/services/apps/task_center/domain/tc_project"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/repository/db/model"
)

// MockProjectRepo is a mock of ProjectRepo interface.
type MockProjectRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepoMockRecorder
}

// MockProjectRepoMockRecorder is the mock recorder for MockProjectRepo.
type MockProjectRepoMockRecorder struct {
	mock *MockProjectRepo
}

// NewMockProjectRepo creates a new mock instance.
func NewMockProjectRepo(ctrl *gomock.Controller) *MockProjectRepo {
	mock := &MockProjectRepo{ctrl: ctrl}
	mock.recorder = &MockProjectRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepo) EXPECT() *MockProjectRepoMockRecorder {
	return m.recorder
}

// CheckRepeat mocks base method.
func (m *MockProjectRepo) CheckRepeat(ctx context.Context, id, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRepeat", ctx, id, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRepeat indicates an expected call of CheckRepeat.
func (mr *MockProjectRepoMockRecorder) CheckRepeat(ctx, id, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRepeat", reflect.TypeOf((*MockProjectRepo)(nil).CheckRepeat), ctx, id, name)
}

// CheckTaskRoles mocks base method.
func (m *MockProjectRepo) CheckTaskRoles(ctx context.Context, flowId, flowVersion string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTaskRoles", ctx, flowId, flowVersion)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTaskRoles indicates an expected call of CheckTaskRoles.
func (mr *MockProjectRepoMockRecorder) CheckTaskRoles(ctx, flowId, flowVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTaskRoles", reflect.TypeOf((*MockProjectRepo)(nil).CheckTaskRoles), ctx, flowId, flowVersion)
}

// Get mocks base method.
func (m *MockProjectRepo) Get(ctx context.Context, id string) (*model.TcProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.TcProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectRepoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectRepo)(nil).Get), ctx, id)
}

// GetAllTasks mocks base method.
func (m *MockProjectRepo) GetAllTasks(ctx context.Context, id string) ([]*model.TcTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", ctx, id)
	ret0, _ := ret[0].([]*model.TcTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockProjectRepoMockRecorder) GetAllTasks(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockProjectRepo)(nil).GetAllTasks), ctx, id)
}

// GetFlowView mocks base method.
func (m *MockProjectRepo) GetFlowView(ctx context.Context, fid, fVersion string) (*model.TcFlowView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowView", ctx, fid, fVersion)
	ret0, _ := ret[0].(*model.TcFlowView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowView indicates an expected call of GetFlowView.
func (mr *MockProjectRepoMockRecorder) GetFlowView(ctx, fid, fVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowView", reflect.TypeOf((*MockProjectRepo)(nil).GetFlowView), ctx, fid, fVersion)
}

// Insert mocks base method.
func (m *MockProjectRepo) Insert(arg0 context.Context, arg1 *model.TcProject, arg2 []*model.TcMember, arg3 []*model.TcFlowInfo, arg4 *model.TcFlowView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockProjectRepoMockRecorder) Insert(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockProjectRepo)(nil).Insert), arg0, arg1, arg2, arg3, arg4)
}

// QueryProjects mocks base method.
func (m *MockProjectRepo) QueryProjects(ctx context.Context, params *tc_project.ProjectCardQueryReq) ([]model.TcProject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryProjects", ctx, params)
	ret0, _ := ret[0].([]model.TcProject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryProjects indicates an expected call of QueryProjects.
func (mr *MockProjectRepoMockRecorder) QueryProjects(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryProjects", reflect.TypeOf((*MockProjectRepo)(nil).QueryProjects), ctx, params)
}

// TaskRoles mocks base method.
func (m *MockProjectRepo) TaskRoles(ctx context.Context, id, version string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskRoles", ctx, id, version)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskRoles indicates an expected call of TaskRoles.
func (mr *MockProjectRepoMockRecorder) TaskRoles(ctx, id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskRoles", reflect.TypeOf((*MockProjectRepo)(nil).TaskRoles), ctx, id, version)
}

// Update mocks base method.
func (m *MockProjectRepo) Update(arg0 context.Context, arg1 *model.TcProject, arg2 []*model.TcMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectRepoMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRepo)(nil).Update), arg0, arg1, arg2)
}
