apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-install-job
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  annotations:
    # 注意，如果没有下面的这个注释的话，当前的这个Job就会被当成release的一部分
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
        version: {{ .Chart.Version }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "sh"
            - "-c"
            - >
              curl -f -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/agent-web-all &&
              curl -f -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/agent-web-space &&
              curl -f -X DELETE http://studio-web-service:8877/api/workstation/v1/webapp/agent-web-customspace &&
              curl -f -H "Content-Type:application/json" -X PUT -d '
              [
              {
                "parent": "root",
                "name": "dataagent",
                "orderIndex": 1000,
                "app": {
                  "textZHCN": "决策智能体",
                  "textZHTW": "決策智能體",
                  "textENUS": "Decision Agent",
                  "type": "group",
                  "pathname": "/agent"
                },
                "subapp": {
                  "children": {
                  }
                }
              },
              {
                "parent": "dataagent",
                "name": "development",
                "orderIndex": 1000,
                "app": {
                  "textZHCN": "开发",
                  "textZHTW": "開發",
                  "textENUS": "Development",
                  "icon": "//ip:port/agent-web/public/icons/development.svg",
                  "type": "directory",
                  "isDefaultOpen": true,
                  "pathname": "/agent/development"
                },
                "subapp": {
                  "children": {
                  }
                }
              },
              {
                "parent": "dataagent",
                "name": "square",
                "orderIndex": 2000,
                "app": {
                  "textZHCN": "广场",
                  "textZHTW": "廣場",
                  "textENUS": "Square",
                  "icon": "//ip:port/agent-web/public/icons/square.svg",
                  "type": "directory",
                  "isDefaultOpen": true,
                  "pathname": "/agent/square"
                },
                "subapp": {
                  "children": {
                  }
                }
              },
              {
                "parent": "square",
                "name": "agent-list",
                "orderIndex": 1000,
                "app": {
                  "textZHCN": "决策智能体",
                  "textZHTW": "決策智能體",
                  "textENUS": "Decision Agent",
                  "icon": "//ip:port/agent-web/public/icons/decision-agent.svg",
                  "type": "directory",
                  "pathname": "/agent/square/agent-list"
                },
                "subapp": {
                  "entry": "//ip:port/agent-web/decision-agent.html",
                  "activeRule": "/",
                  "baseRouter": ""
                }
              },
              {
                "parent": "square",
                "name": "agent-template",
                "orderIndex": 2000,
                "app": {
                  "textZHCN": "模板",
                  "textZHTW": "模板",
                  "textENUS": "Template",
                  "icon": "//ip:port/agent-web/public/icons/agent-template.svg",
                  "type": "directory",
                  "pathname": "/agent/square/agent-template"
                },
                "subapp": {
                  "entry": "//ip:port/agent-web/agent-template.html",
                  "activeRule": "/",
                  "baseRouter": ""
                }
              },
              {
                "parent": "square",
                "name": "agent-api",
                "orderIndex": 3000,
                "app": {
                  "textZHCN": "API",
                  "textZHTW": "API",
                  "textENUS": "API",
                  "icon": "//ip:port/agent-web/public/icons/api.svg",
                  "type": "directory",
                  "pathname": "/agent/square/agent-api"
                },
                "subapp": {
                  "entry": "//ip:port/agent-web/api.html",
                  "activeRule": "/",
                  "baseRouter": ""
                }
              },
              {
                "parent": "development",
                "name": "my-agent-list",
                "orderIndex": 1000,
                "app": {
                  "textZHCN": "决策智能体",
                  "textZHTW": "決策智能體",
                  "textENUS": "Decision Agent",
                  "icon": "//ip:port/agent-web/public/icons/decision-agent.svg",
                  "type": "directory",
                  "pathname": "/agent/development/my-agent-list"
                },
                "subapp": {
                  "entry": "//ip:port/agent-web/my-agents.html",
                  "activeRule": "/",
                  "baseRouter": ""
                }
              }
              ]' http://studio-web-service:8877/api/workstation/v1/webapp

