// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain/tc_project/interface.go

// Package mock_tc_project is a generated GoMock package.
package impl

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/kweaver-ai/dsg/services/apps/task_center/common/models/response"
	tc_project "github.com/kweaver-ai/dsg/services/apps/task_center/domain/tc_project"
	model "github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/repository/db/model"
)

// MockUserCase is a mock of UserCase interface.
type MockUserCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserCaseMockRecorder
}

// MockUserCaseMockRecorder is the mock recorder for MockUserCase.
type MockUserCaseMockRecorder struct {
	mock *MockUserCase
}

// NewMockUserCase creates a new mock instance.
func NewMockUserCase(ctrl *gomock.Controller) *MockUserCase {
	mock := &MockUserCase{ctrl: ctrl}
	mock.recorder = &MockUserCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCase) EXPECT() *MockUserCaseMockRecorder {
	return m.recorder
}

// CheckImageExistence mocks base method.
func (m *MockUserCase) CheckImageExistence(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckImageExistence", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckImageExistence indicates an expected call of CheckImageExistence.
func (mr *MockUserCaseMockRecorder) CheckImageExistence(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckImageExistence", reflect.TypeOf((*MockUserCase)(nil).CheckImageExistence), ctx, id)
}

// CheckRepeat mocks base method.
func (m *MockUserCase) CheckRepeat(ctx context.Context, req tc_project.ProjectNameRepeatReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRepeat", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRepeat indicates an expected call of CheckRepeat.
func (mr *MockUserCaseMockRecorder) CheckRepeat(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRepeat", reflect.TypeOf((*MockUserCase)(nil).CheckRepeat), ctx, req)
}

// CheckStatus mocks base method.
func (m *MockUserCase) CheckStatus(ctx context.Context, newProject, old *model.TcProject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus", ctx, newProject, old)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockUserCaseMockRecorder) CheckStatus(ctx, newProject, old interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockUserCase)(nil).CheckStatus), ctx, newProject, old)
}

// Create mocks base method.
func (m *MockUserCase) Create(ctx context.Context, projectReq *tc_project.ProjectReqModel, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, projectReq, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserCaseMockRecorder) Create(ctx, projectReq, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserCase)(nil).Create), ctx, projectReq, token)
}

// DeleteMemberByUsedRoleUserProject mocks base method.
func (m *MockUserCase) DeleteMemberByUsedRoleUserProject(ctx context.Context, roleId, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMemberByUsedRoleUserProject", ctx, roleId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMemberByUsedRoleUserProject indicates an expected call of DeleteMemberByUsedRoleUserProject.
func (mr *MockUserCaseMockRecorder) DeleteMemberByUsedRoleUserProject(ctx, roleId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMemberByUsedRoleUserProject", reflect.TypeOf((*MockUserCase)(nil).DeleteMemberByUsedRoleUserProject), ctx, roleId, userId)
}

// DeleteProject mocks base method.
func (m *MockUserCase) DeleteProject(ctx context.Context, projectId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, projectId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockUserCaseMockRecorder) DeleteProject(ctx, projectId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockUserCase)(nil).DeleteProject), ctx, projectId)
}

// GetDetail mocks base method.
func (m *MockUserCase) GetDetail(ctx context.Context, id string) (*tc_project.ProjectDetailModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, id)
	ret0, _ := ret[0].(*tc_project.ProjectDetailModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockUserCaseMockRecorder) GetDetail(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockUserCase)(nil).GetDetail), ctx, id)
}

// GetFlowView mocks base method.
func (m *MockUserCase) GetFlowView(ctx context.Context, pid string) (*tc_project.FlowchartView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowView", ctx, pid)
	ret0, _ := ret[0].(*tc_project.FlowchartView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowView indicates an expected call of GetFlowView.
func (mr *MockUserCaseMockRecorder) GetFlowView(ctx, pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowView", reflect.TypeOf((*MockUserCase)(nil).GetFlowView), ctx, pid)
}

// GetProjectCandidate mocks base method.
func (m *MockUserCase) GetProjectCandidate(ctx context.Context, reqData *tc_project.FlowIdModel, token string) (*tc_project.ProjectCandidates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCandidate", ctx, reqData, token)
	ret0, _ := ret[0].(*tc_project.ProjectCandidates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCandidate indicates an expected call of GetProjectCandidate.
func (mr *MockUserCaseMockRecorder) GetProjectCandidate(ctx, reqData, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCandidate", reflect.TypeOf((*MockUserCase)(nil).GetProjectCandidate), ctx, reqData, token)
}

// QueryProjects mocks base method.
func (m *MockUserCase) QueryProjects(ctx context.Context, params *tc_project.ProjectCardQueryReq) (response.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryProjects", ctx, params)
	ret0, _ := ret[0].(response.PageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryProjects indicates an expected call of QueryProjects.
func (mr *MockUserCaseMockRecorder) QueryProjects(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryProjects", reflect.TypeOf((*MockUserCase)(nil).QueryProjects), ctx, params)
}

// Update mocks base method.
func (m *MockUserCase) Update(ctx context.Context, projectReq *tc_project.ProjectEditModel, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, projectReq, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserCaseMockRecorder) Update(ctx, projectReq, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserCase)(nil).Update), ctx, projectReq, token)
}
