// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	impl5 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/data_search_all/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/es_data_datalog"
	impl3 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/es_data_view/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/es_elec_license/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/es_indicator/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/es_info_catalog/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/es_interface_svc/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driven/opensearch"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver"
	data_catalog2 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/data_catalog"
	data_search_all2 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/data_search_all"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/data_view"
	elec_license2 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/elec_license"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/indicator"
	info_catalog2 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/info_catalog"
	info_system2 "github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/info_system"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/adapter/driver/interface_svc"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/common/settings"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/domain/data_catalog"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/domain/data_search_all/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/basic-search/domain/data_view/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/domain/elec_license/impl"
	impl7 "github.com/kweaver-ai/dsg/services/apps/basic-search/domain/indicator/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/domain/info_catalog/impl"
	"github.com/kweaver-ai/dsg/services/apps/basic-search/domain/info_system"
	impl2 "github.com/kweaver-ai/dsg/services/apps/basic-search/domain/interface_svc/impl"
	"github.com/kweaver-ai/idrm-go-frame"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, cfg *settings.Config) (*idrm_go_frame.App, func(), error) {
	searchClient, err := opensearch.NewOpenSearchClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	search, err := es_data_datalog.NewSearch(ctx, searchClient)
	if err != nil {
		return nil, nil, err
	}
	useCase := data_catalog.NewUseCase(search)
	service := data_catalog2.NewService(useCase)
	esInterfaceSvc, err := impl.NewObjSearch(searchClient)
	if err != nil {
		return nil, nil, err
	}
	interface_svcUseCase := impl2.NewUseCase(esInterfaceSvc)
	interface_svcService := interface_svc.NewService(interface_svcUseCase)
	esDataView, err := impl3.NewObjSearch(searchClient)
	if err != nil {
		return nil, nil, err
	}
	data_viewUseCase := impl4.NewUseCase(esDataView)
	data_viewService := data_view.NewService(data_viewUseCase)
	esAll := impl5.NewSearch(searchClient)
	data_search_allUseCase := data_search_all.NewUseCase(esAll)
	data_search_allService := data_search_all2.NewService(data_search_allUseCase)
	es_info_catalogSearch, err := es_info_catalog.NewSearch(ctx, searchClient)
	if err != nil {
		return nil, nil, err
	}
	info_catalogUseCase := info_catalog.NewUseCase(es_info_catalogSearch)
	info_catalogService := info_catalog2.NewService(info_catalogUseCase)
	searcher, err := es_elec_license.NewSearcher(ctx, searchClient)
	if err != nil {
		return nil, nil, err
	}
	elec_licenseUseCase := elec_license.NewUseCase(searcher)
	elec_licenseService := elec_license2.NewService(elec_licenseUseCase)
	info_systemInterface, err := info_system.New(searchClient)
	if err != nil {
		return nil, nil, err
	}
	info_systemService := info_system2.New(info_systemInterface)
	router := &driver.Router{
		DataCatalogSvc:   service,
		InterfaceSvc:     interface_svcService,
		DataViewSvc:      data_viewService,
		DataSearchAllSvc: data_search_allService,
		InfoCatalogSvc:   info_catalogService,
		ElecLicenseSvc:   elec_licenseService,
		InfoSystem:       info_systemService,
	}
	server := driver.NewHttpServer(router)
	consumer := interface_svc.NewConsumer(interface_svcUseCase)
	data_catalogConsumer := data_catalog2.NewConsumer(useCase)
	data_viewConsumer := data_view.NewConsumer(data_viewUseCase)
	esIndicator, err := impl6.NewObjSearch(searchClient)
	if err != nil {
		return nil, nil, err
	}
	indicatorUseCase := impl7.NewUseCase(esIndicator)
	indicatorConsumer := indicator.NewConsumer(indicatorUseCase)
	info_catalogConsumer := info_catalog2.NewConsumer(info_catalogUseCase)
	elec_licenseConsumer := elec_license2.NewConsumer(elec_licenseUseCase)
	mqConsumerService := driver.NewMQConsumeService(cfg, consumer, data_catalogConsumer, data_viewConsumer, indicatorConsumer, info_catalogConsumer, elec_licenseConsumer, info_systemInterface)
	app := newApp(server, mqConsumerService)
	return app, func() {
	}, nil
}
