// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller"
	apply_scope "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/apply-scope"
	v1_30 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/assessment/v1"
	v1_10 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/audit_process/v1"
	v1_17 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/catalog_feedback/v1"
	v1_14 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/category/v1"
	v1_24 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/cognitive_service_system/v1"
	v1_12 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_assets/frontend/v1"
	v1_13 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_assets/v1"
	v1_6 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_catalog/frontend/v1"
	v1_9 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_catalog/frontend/v2"
	v1 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_catalog/v1"
	v1_20 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_catalog_score/v1"
	v1_11 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_comprehension/frontend/v1"
	v1_23 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_push/v1"
	v1_15 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_resource/frontend/v1"
	v1_16 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/data_resource/v1"
	v1_21 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/elec_licence/v1"
	v1_25 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/file_resource/v1"
	v1_19 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/info_catalog/v1"
	v1_27 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/info_system/frontend/v1"
	v1_4 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/my/frontend/v1"
	v1_22 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/my_favorite/v1"
	v1_18 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/open_catalog/v1"
	v1_31 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/res_feedback/v1"
	v1_28 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/statistics/v1"
	v1_29 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/system_operation/v1"
	v1_2 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/tree/v1"
	v1_7 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/tree_node/frontend/v1"
	v1_3 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/controller/tree_node/v1"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/ad"
	impl41 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/auth/impl"
	impl37 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/auth_service/impl"
	impl39 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/basic_search/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/callbacks"
	impl40 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/cognitive_assistant/impl"
	impl9 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/configuration_center/impl"
	impl81 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/data_exploration/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/databases"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/demand_management"
	impl17 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/mq/es/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/openai"
	impl29 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/task_center/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/virtualization_engine"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/workflow"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driver/mq"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driver/mq/apply_num"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driver/mq/entity_change"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driver/mq/interface_catalog"
	kafka2 "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driver/mq/kafka"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/settings"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	impl83 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/apply-scope/impl"
	impl85 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/assessment/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/audit_process"
	impl55 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/catalog_feedback/impl"
	impl52 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/category/apply_scope_config/impl"
	impl51 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/category/impl"
	impl74 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/cognitive_service_system/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/common"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/common_usecase"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_assets"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_catalog"
	impl63 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_catalog_score/impl"
	impl30 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_comprehension/impl"
	impl71 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_push/impl"
	impl53 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_resource/impl"
	impl27 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/data_resource_catalog/impl"
	impl67 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/elec_licence/impl"
	impl75 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/file_resource/impl"
	data_catalog2 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/frontend/data_catalog"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/frontend/data_resource"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/frontend/info_system"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/frontend/my"
	info_catalog2 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/info_catalog"
	impl60 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/info_resource_catalog/impl"
	impl68 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/my_favorite/impl"
	impl57 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/open_catalog/impl"
	impl87 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/res_feedback/impl"
	impl77 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/statistics/impl"
	impl82 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/system_operation/impl"
	impl32 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/tree/impl"
	impl34 "github.com/kweaver-ai/dsg/services/apps/data-catalog/domain/tree_node/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/mq/kafka"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db"
	impl49 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/apply-scope/impl"
	impl84 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/assessment/impl"
	impl45 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/business_logic_entity_by_business_domain/impl"
	impl46 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/business_logic_entity_by_department/impl"
	impl23 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/catalog_feedback/impl"
	impl54 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/catalog_feedback_op_log/impl"
	impl18 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/category/impl"
	impl50 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/category_apply_scope_relation/impl"
	impl66 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/classify/impl"
	impl48 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/client_info/impl"
	impl72 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/cognitive_service_system/impl"
	impl44 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_assets_info/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog/impl"
	impl7 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_audit_flow_bind/impl"
	impl5 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_code_sequence/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_code_title/impl"
	impl3 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_column/impl"
	impl8 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_download_apply/impl"
	impl2 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_info/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_mount_resource/impl"
	impl62 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_score/impl"
	impl19 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_catalog_stats_info/impl"
	impl21 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_comprehension/impl"
	impl28 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_comprehension_template/impl"
	impl69 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_push/impl"
	impl10 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_resource/impl"
	impl12 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/data_resource_catalog/impl"
	impl64 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/elec_licence/impl"
	impl65 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/elec_licence_column/impl"
	impl24 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/file_resource/impl"
	impl79 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/form_data_count/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/info_catalog"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/info_resource_catalog"
	impl59 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/info_resource_catalog_statistic/impl"
	impl35 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/my/impl"
	impl22 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/my_favorite/impl"
	impl20 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/open_catalog/impl"
	impl86 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/res_feedback/impl"
	impl80 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/rule_config/impl"
	impl47 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/standardization_info/impl"
	impl76 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/statistics/impl"
	impl78 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/system_operation_detail/impl"
	impl31 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/tree/impl"
	impl33 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/tree_node/impl"
	impl36 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/user_data_catalog_rel/impl"
	impl38 "github.com/kweaver-ai/dsg/services/apps/data-catalog/infrastructure/repository/db/gorm/user_data_catalog_stats_info/impl"
	gocephclient "github.com/kweaver-ai/idrm-go-common/go-ceph-client"
	v1_8 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	v1_5 "github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl43 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl61 "github.com/kweaver-ai/idrm-go-common/rest/basic_bigdata_service/impl"
	v1_26 "github.com/kweaver-ai/idrm-go-common/rest/basic_search/v1"
	impl58 "github.com/kweaver-ai/idrm-go-common/rest/business_grooming/impl"
	impl11 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	impl14 "github.com/kweaver-ai/idrm-go-common/rest/data_application_service/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/data_subject/data_subject_impl"
	impl70 "github.com/kweaver-ai/idrm-go-common/rest/data_sync/impl"
	impl15 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	impl73 "github.com/kweaver-ai/idrm-go-common/rest/demand_management/impl"
	impl42 "github.com/kweaver-ai/idrm-go-common/rest/hydra/impl"
	impl16 "github.com/kweaver-ai/idrm-go-common/rest/label/impl"
	impl13 "github.com/kweaver-ai/idrm-go-common/rest/standardization/impl"
	impl25 "github.com/kweaver-ai/idrm-go-common/rest/task_center/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/user_management"
	impl26 "github.com/kweaver-ai/idrm-go-common/rest/virtual_engine/impl"
	impl56 "github.com/kweaver-ai/idrm-go-common/rest/workflow/impl"
	"github.com/kweaver-ai/idrm-go-common/trace"
	"github.com/kweaver-ai/idrm-go-frame/core/utils/httpclient"

	_ "github.com/golang-migrate/migrate/v4/database/mysql"

	_ "github.com/golang-migrate/migrate/v4/source/file"
)

// Injectors from wire.go:

func InitApp(config *settings.Config) (*AppRunner, func(), error) {
	data, cleanup, err := db.NewData(config)
	if err != nil {
		return nil, nil, err
	}
	repoOp := impl.NewRepo(data)
	data_catalog_infoRepoOp := impl2.NewRepo(data)
	data_catalog_columnRepoOp := impl3.NewRepo(data)
	data_catalog_mount_resourceRepoOp := impl4.NewRepo(data)
	data_catalog_code_sequenceRepoOp := impl5.NewRepo(data)
	data_catalog_code_titleRepoOp := impl6.NewRepo(data)
	data_catalog_audit_flow_bindRepoOp := impl7.NewRepo(data)
	data_catalog_download_applyRepoOp := impl8.NewRepo(data)
	redis := repository.NewRedis(config)
	redisson := util.NewRedisson(redis)
	client := trace.NewOtelHttpClient()
	workflowInterface, err := workflow.NewWorkflow(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpClient := httpclient.NewMiddlewareHTTPClient(client)
	repo := impl9.NewCCDrivenRepo(httpClient)
	mqManager, err := mq.NewMQManager()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gormDB := db.NewGormDB(data)
	dataResourceRepo := impl10.NewDataResourceRepo(gormDB)
	configuration_centerDriven := impl11.NewConfigurationCenterDrivenByService(client)
	data_subjectDriven := data_subject_impl.NewDataViewDriven(client)
	dataResourceCatalogRepo := impl12.NewDataResourceCatalogRepo(gormDB)
	standardizationDriven := impl13.NewDriven(client)
	data_application_serviceDriven := impl14.NewDrivenImpl(client)
	syncProducer, err := kafka.NewSyncProducer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_viewDriven := impl15.NewDataViewDriven(client)
	labelDriven := impl16.NewBigDataDriven(client)
	esRepo := impl17.NewESRepo(syncProducer, data_viewDriven, configuration_centerDriven, labelDriven)
	categoryRepo := impl18.NewRepo(data)
	treeRepo := impl18.NewRepoTree(data)
	data_catalog_stats_infoRepoOp := impl19.NewRepo(data)
	openCatalogRepo := impl20.NewOpenCatalogRepo(gormDB)
	data_comprehensionRepoOp := impl21.NewRepo(data, workflowInterface)
	my_favoriteRepo := impl22.NewRepo(data)
	catalog_feedbackRepo := impl23.NewRepo(data)
	fileResourceRepo := impl24.NewFileResourceRepo(gormDB)
	task_centerDriven := impl25.NewDriven(client)
	virtual_engineDriven := impl26.NewDrivenImpl(client)
	drivenUserMgnt := user_management.NewUserMgntByService(client)
	departmentDomain := common.NewDepartmentDomain(configuration_centerDriven, drivenUserMgnt)
	dataResourceCatalogDomain := impl27.NewDataResourceCatalogDomain(dataResourceRepo, configuration_centerDriven, data_subjectDriven, dataResourceCatalogRepo, repoOp, data_catalog_columnRepoOp, standardizationDriven, data_application_serviceDriven, workflowInterface, esRepo, categoryRepo, treeRepo, data_catalog_stats_infoRepoOp, data_viewDriven, openCatalogRepo, data_comprehensionRepoOp, my_favoriteRepo, catalog_feedbackRepo, fileResourceRepo, task_centerDriven, virtual_engineDriven, departmentDomain)
	dataCatalogDomain := data_catalog.NewDataCatalogDomain(repoOp, data_catalog_infoRepoOp, data_catalog_columnRepoOp, data_catalog_mount_resourceRepoOp, data_catalog_code_sequenceRepoOp, data_catalog_code_titleRepoOp, data_catalog_audit_flow_bindRepoOp, data_catalog_download_applyRepoOp, redis, redisson, data, workflowInterface, repo, mqManager, dataResourceCatalogDomain)
	data_comprehension_templateRepo := impl28.NewRepo(gormDB)
	adAD := ad.NewAD(client)
	openAI := openai.NewOpenAI(client)
	virtualizationEngine := virtualization_engine.NewVirtualizationEngine(client)
	driven2 := impl29.NewDriven(client)
	comprehensionDomain := impl30.NewComprehensionDomain(data_comprehensionRepoOp, data_comprehension_templateRepo, repoOp, data_catalog_columnRepoOp, dataResourceRepo, data_catalog_infoRepoOp, adAD, openAI, virtualizationEngine, data, driven2, task_centerDriven, configuration_centerDriven, workflowInterface, departmentDomain)
	v1Controller := v1.NewController(dataCatalogDomain, comprehensionDomain, dataResourceCatalogDomain)
	repo2 := impl31.NewRepo(data)
	useCase := impl32.NewUseCase(repo2)
	service := v1_2.NewService(useCase)
	tree_nodeRepo := impl33.NewRepo(data)
	tree_nodeUseCase := impl34.NewUseCase(tree_nodeRepo, repo2)
	v1Service := v1_3.NewService(tree_nodeUseCase)
	myRepoOp := impl35.NewRepo(data)
	user_data_catalog_relRepoOp := impl36.NewRepo(data)
	commonUseCase := common_usecase.NewCommonUseCase(data_catalog_download_applyRepoOp, user_data_catalog_relRepoOp)
	drivenAuthService := impl37.NewAuthServiceImpl()
	domain := my.NewMyDomain(data, myRepoOp, data_catalog_infoRepoOp, commonUseCase, data_catalog_mount_resourceRepoOp, drivenAuthService)
	controller2 := v1_4.NewController(domain)
	user_data_catalog_stats_infoRepoOp := impl38.NewRepo(data)
	auth_serviceRepo := impl37.NewASDrivenRepo(httpClient)
	basic_searchRepo := impl39.NewRepo(httpClient, client)
	cogAssistant := impl40.NewCogAssistant(httpClient)
	authRepo := impl41.NewRepo(httpClient)
	authServiceV1Interface, err := v1_5.NewForBaseAndClient(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	demandManagementV1Client, err := demand_management.New(config, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_catalogDataCatalogDomain := data_catalog2.NewDataCatalogDomain(data, repoOp, data_catalog_infoRepoOp, data_catalog_columnRepoOp, data_comprehensionRepoOp, data_catalog_mount_resourceRepoOp, data_catalog_audit_flow_bindRepoOp, data_catalog_download_applyRepoOp, data_catalog_stats_infoRepoOp, user_data_catalog_relRepoOp, commonUseCase, user_data_catalog_stats_infoRepoOp, auth_serviceRepo, basic_searchRepo, repo, cogAssistant, authRepo, drivenAuthService, workflowInterface, configuration_centerDriven, data_subjectDriven, categoryRepo, my_favoriteRepo, authServiceV1Interface, demandManagementV1Client, data_viewDriven, dataResourceRepo)
	controller3 := v1_6.NewController(data_catalogDataCatalogDomain, dataCatalogDomain, dataResourceCatalogDomain)
	service2 := v1_7.NewService(tree_nodeUseCase)
	hydra := impl42.NewHydraByService(client)
	logger := controller.NewAuditLogger()
	authorizationDriven := impl43.NewDriven(client)
	authServiceInternalV1Interface, err := v1_5.NewInternalForBase(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	middleware := v1_8.NewMiddleware(hydra, drivenUserMgnt, configuration_centerDriven, logger, authorizationDriven, authServiceInternalV1Interface)
	controller4 := v1_9.NewController(data_catalogDataCatalogDomain)
	auditProcessDomain := audit_process.NewAuditProcessDomain(data_catalog_audit_flow_bindRepoOp, data)
	controller5 := v1_10.NewController(auditProcessDomain)
	controller6 := v1_11.NewController(comprehensionDomain)
	data_assets_infoRepoOp := impl44.NewRepo(data)
	business_logic_entity_by_business_domainRepoOp := impl45.NewRepo(data)
	business_logic_entity_by_departmentRepoOp := impl46.NewRepo(data)
	standardization_infoRepoOp := impl47.NewRepo(data)
	client_infoRepoOp := impl48.NewRepo(data)
	dataAssetsDomain := data_assets.NewDataAssetsDomain(data_assets_infoRepoOp, business_logic_entity_by_business_domainRepoOp, business_logic_entity_by_departmentRepoOp, standardization_infoRepoOp, repoOp, data_catalog_columnRepoOp, data_catalog_infoRepoOp, client_infoRepoOp, data)
	controller7 := v1_12.NewController(dataAssetsDomain)
	controller8 := v1_13.NewController(dataAssetsDomain)
	apply_scopeRepo := impl49.NewRepoImpl(data)
	category_apply_scope_relationRepo := impl50.NewRepoImpl(data)
	categoryUseCase := impl51.NewUseCase(categoryRepo, repo, apply_scopeRepo, category_apply_scope_relationRepo)
	service3 := v1_14.NewService(categoryUseCase)
	useCaseTree := impl51.NewUseTreeCase(treeRepo, categoryRepo)
	treeService := v1_14.NewTreeService(useCaseTree)
	apply_scope_configUseCase := impl52.NewUseCase(category_apply_scope_relationRepo, categoryRepo, treeRepo, configuration_centerDriven)
	categoryApplyScopeConfigService := v1_14.NewCategoryApplyScopeConfigService(apply_scope_configUseCase)
	data_viewRepo := driven.NewLocalDataViewRepo(httpClient)
	indicator_managementRepo := driven.NewLocalIndicatorManagementRepo(httpClient)
	databasesClient := databases.New(data)
	dataResourceDomain := data_resource.NewDataResourceDomain(auth_serviceRepo, basic_searchRepo, repo, data_viewRepo, indicator_managementRepo, databasesClient, my_favoriteRepo)
	controller9 := v1_15.NewController(dataResourceDomain)
	dataResourceCatalogInternal := impl27.NewDataResourceCatalogInternal(dataResourceCatalogDomain)
	implDataResourceDomain := impl53.NewDataResourceDomain(dataResourceRepo, configuration_centerDriven, data_application_serviceDriven, data_viewDriven, data_subjectDriven, data_viewRepo, esRepo, dataResourceCatalogRepo, dataResourceCatalogInternal)
	controller10 := v1_16.NewController(implDataResourceDomain)
	catalog_feedback_op_logRepo := impl54.NewRepo(data)
	catalog_feedbackUseCase := impl55.NewUseCase(repoOp, catalog_feedbackRepo, catalog_feedback_op_logRepo, data, configuration_centerDriven)
	controller11 := v1_17.NewController(catalog_feedbackUseCase)
	docAuditDriven := impl56.NewDocAuditDriven(client)
	openCatalogDomain := impl57.NewOpenCatalogDomain(configuration_centerDriven, openCatalogRepo, dataResourceCatalogRepo, workflowInterface, docAuditDriven, data_subjectDriven, dataResourceRepo)
	controller12 := v1_18.NewController(openCatalogDomain)
	consumer := kafka.NewConsumer()
	business_groomingDriven := impl58.NewDriven(client)
	infoResourceCatalogRepo := info_resource_catalog.NewInfoResourceCatalogRepo(gormDB, consumer, business_groomingDriven)
	info_resource_catalog_statisticRepo := impl59.NewRepo(data)
	infoResourceCatalogDomain := impl60.NewInfoResourceCatalogDomain(infoResourceCatalogRepo, dataResourceCatalogRepo, categoryRepo, configuration_centerDriven, repo, business_groomingDriven, standardizationDriven, workflowInterface, docAuditDriven, basic_searchRepo, esRepo, my_favoriteRepo, databasesClient, info_resource_catalog_statisticRepo, labelDriven)
	infoCatalogRepo := info_catalog.NewInfoCatalogRepo(gormDB)
	basic_bigdata_serviceDriven := impl61.NewDriven(client)
	infoCatalogDomain := info_catalog2.NewInfoCatalogDomain(infoCatalogRepo, basic_bigdata_serviceDriven, treeRepo, configuration_centerDriven)
	controller13 := v1_19.NewController(infoResourceCatalogDomain, infoCatalogDomain)
	dataCatalogScoreRepo := impl62.NewDataCatalogScoreRepo(gormDB)
	dataCatalogScoreDomain := impl63.NewDataCatalogScoreDomain(dataCatalogScoreRepo, dataResourceCatalogRepo, configuration_centerDriven)
	controller14 := v1_20.NewController(dataCatalogScoreDomain)
	elecLicenceRepo := impl64.NewElecLicenceRepo(gormDB)
	elecLicenceColumnRepo := impl65.NewElecLicenceColumnRepo(gormDB)
	classifyRepo := impl66.NewClassifyRepo(gormDB)
	elecLicenceUseCase := impl67.NewElecLicenceDomain(elecLicenceRepo, elecLicenceColumnRepo, classifyRepo, esRepo, basic_searchRepo, configuration_centerDriven, my_favoriteRepo)
	controller15 := v1_21.NewController(elecLicenceUseCase)
	my_favoriteUseCase := impl68.NewUseCase(my_favoriteRepo, dataCatalogScoreRepo, basic_searchRepo, data)
	controller16 := v1_22.NewController(my_favoriteUseCase)
	data_pushRepo := impl69.NewRepoImpl(data)
	workflowDriven := impl56.NewWorkflowDriven(client)
	data_syncDriven := impl70.NewDataSyncDriven(client)
	producer, err := kafka.NewXSyncProducer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	callbackInterface, cleanup2, err := callbacks.NewDataPushCallback()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_pushUseCase := impl71.NewUseCase(gormDB, data_pushRepo, workflowInterface, workflowDriven, configuration_centerDriven, data_syncDriven, dataResourceRepo, data_viewDriven, virtual_engineDriven, business_groomingDriven, repoOp, task_centerDriven, driven2, producer, data_viewRepo, callbackInterface, repo)
	controller17 := v1_23.NewController(data_pushUseCase)
	cognitive_service_systemRepo := impl72.NewRepoImpl(data)
	demand_managementDriven := impl73.NewDemandManagementDriven(client)
	cognitiveServiceSystemDomain := impl74.NewCognitiveServiceSystemDomain(gormDB, data_pushRepo, workflowInterface, configuration_centerDriven, data_syncDriven, dataResourceRepo, data_viewDriven, virtual_engineDriven, business_groomingDriven, repoOp, cognitive_service_systemRepo, demand_managementDriven, auth_serviceRepo, authorizationDriven)
	controller18 := v1_24.NewController(cognitiveServiceSystemDomain)
	cephClient, err := gocephclient.NewCephClient(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fileResourceDomain := impl75.NewFileResourceDomain(configuration_centerDriven, fileResourceRepo, dataResourceRepo, dataResourceCatalogRepo, workflowInterface, docAuditDriven, basic_bigdata_serviceDriven, cephClient, departmentDomain)
	controller19 := v1_25.NewController(fileResourceDomain)
	v1Client, err := v1_26.NewForBaseAndClient(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	info_systemDomain := info_system.New(databasesClient, v1Client)
	controller20 := v1_27.New(info_systemDomain)
	statisticsRepo := impl76.NewRepo(data)
	statisticsUseCase := impl77.NewUseCase(data, statisticsRepo, data_viewDriven, dataResourceCatalogRepo, data_application_serviceDriven)
	controller21 := v1_28.NewController(statisticsUseCase)
	systemOperationDetailRepo := impl78.NewSystemOperationDetailRepo(gormDB)
	formDataCountRepo := impl79.NewFormDataCountRepo(gormDB)
	ruleConfigRepo := impl80.NewRuleConfigRepo(gormDB)
	drivenDataExploration := impl81.NewDataExploration(client)
	systemOperationDomain := impl82.NewSystemOperationDomain(repoOp, dataResourceRepo, systemOperationDetailRepo, formDataCountRepo, ruleConfigRepo, configuration_centerDriven, data_viewRepo, data_viewDriven, dataResourceCatalogRepo, task_centerDriven, drivenDataExploration)
	controller22 := v1_29.NewController(systemOperationDomain)
	applyScopeUseCase := impl83.NewApplyScopeUseCaseImpl(apply_scopeRepo)
	apply_scopeController := apply_scope.NewController(applyScopeUseCase)
	assessmentRepo := impl84.NewAssessmentRepo(gormDB)
	targetDomain := impl85.NewAssessmentTargetDomain(assessmentRepo, configuration_centerDriven)
	planDomain := impl85.NewAssessmentPlanDomain(assessmentRepo, configuration_centerDriven)
	operationTargetDomain := impl85.NewOperationTargetDomain(assessmentRepo, configuration_centerDriven)
	operationPlanDomain := impl85.NewOperationPlanDomain(assessmentRepo, configuration_centerDriven)
	controller23 := v1_30.NewController(targetDomain, planDomain, operationTargetDomain, operationPlanDomain)
	res_feedbackRepo := impl86.NewRepo(data)
	res_feedbackUseCase := impl87.NewUseCase(repoOp, res_feedbackRepo, catalog_feedback_op_logRepo, basic_searchRepo, data, configuration_centerDriven)
	controller24 := v1_31.NewController(res_feedbackUseCase)
	router := &controller.Router{
		DcController:                         v1Controller,
		TreeApi:                              service,
		TreeNodeApi:                          v1Service,
		MyController:                         controller2,
		FrontendDcController:                 controller3,
		FrontendTreeNodeApi:                  service2,
		Middleware:                           middleware,
		FrontendDcControllerV2:               controller4,
		AuditProcessController:               controller5,
		DataComprehensionController:          controller6,
		FrontendDaController:                 controller7,
		DaController:                         controller8,
		CategoryController:                   service3,
		CategoryTreeController:               treeService,
		CategoryApplyScopeConfigController:   categoryApplyScopeConfigService,
		FrontendDRController:                 controller9,
		DataResourceController:               controller10,
		CatalogFeedbackController:            controller11,
		OpenCatalogController:                controller12,
		InfoCatalogController:                controller13,
		DataCatalogScoreController:           controller14,
		ElecLicenceController:                controller15,
		MyFavoriteController:                 controller16,
		DataPushController:                   controller17,
		CognitiveServiceSystem:               controller18,
		FileResourceController:               controller19,
		FrontendInfoSystemController:         controller20,
		StatisticsController:                 controller21,
		SystemOperationController:            controller22,
		CategoryApplyScopeRelationController: apply_scopeController,
		AssessmentController:                 controller23,
		ResFeedbackController:                controller24,
	}
	server := controller.NewHttpServer(router)
	app := newApp(server)
	entityChangeTransport := callbacks.NewEntityChangeTransport(producer)
	transports := callbacks.NewTransport(gormDB, entityChangeTransport)
	wfStarter := workflow.NewWFStarter(workflowInterface, dataCatalogDomain, data_catalogDataCatalogDomain)
	entityChangeHandler := entity_change.NewEntityChangeHandler(implDataResourceDomain)
	interfaceCatalogHandler := interface_catalog.NewInterfaceCatalogHandler(implDataResourceDomain)
	applyNumHandler := apply_num.NewApplyNumHandler(dataResourceCatalogDomain)
	mqHandler := kafka2.NewMqHandler(consumer, entityChangeHandler, interfaceCatalogHandler, applyNumHandler)
	implUseCase := impl77.NewUseCaseImpl(data, statisticsRepo, data_viewDriven)
	appRunner := NewAppRunner(app, transports, wfStarter, mqHandler, implUseCase, controller23)
	return appRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}
