// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain/tc_oss/logic.go

// Package mock is a generated GoMock package.
package impl

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/repository/db/model"
)

// MockOssRepo is a mock of OssRepo interface.
type MockOssRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOssRepoMockRecorder
}

// MockOssRepoMockRecorder is the mock recorder for MockOssRepo.
type MockOssRepoMockRecorder struct {
	mock *MockOssRepo
}

// NewMockOssRepo creates a new mock instance.
func NewMockOssRepo(ctrl *gomock.Controller) *MockOssRepo {
	mock := &MockOssRepo{ctrl: ctrl}
	mock.recorder = &MockOssRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOssRepo) EXPECT() *MockOssRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOssRepo) Get(ctx context.Context, uuid string) (*model.TcOss, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*model.TcOss)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOssRepoMockRecorder) Get(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOssRepo)(nil).Get), ctx, uuid)
}

// Insert mocks base method.
func (m *MockOssRepo) Insert(ctx context.Context, obj *model.TcOss) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockOssRepoMockRecorder) Insert(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOssRepo)(nil).Insert), ctx, obj)
}
