// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTCatalogCodeSequence = "t_catalog_code_sequence"

// TCatalogCodeSequence mapped from table <t_catalog_code_sequence>
type TCatalogCodeSequence struct {
	ID         uint64     `gorm:"column:id;primaryKey" json:"id"`                                           // 唯一id，雪花算法
	CodePrefix string     `gorm:"column:code_prefix;not null" json:"code_prefix"`                           // 目录编码前缀部分（类、项、目码+细目码）
	OrderCode  int32      `gorm:"column:order_code;not null" json:"order_code"`                             // 目录编码顺序码，不足6位高位补0
	CreatedAt  *util.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"` // 创建时间
	UpdatedAt  *util.Time `gorm:"column:updated_at;not null" json:"updated_at"`                             // 更新时间
}

func (m *TCatalogCodeSequence) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TCatalogCodeSequence's table name
func (*TCatalogCodeSequence) TableName() string {
	return TableNameTCatalogCodeSequence
}
