// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogAuditFlowBind = "t_data_catalog_audit_flow_bind"

// TDataCatalogAuditFlowBind mapped from table <t_data_catalog_audit_flow_bind>
type TDataCatalogAuditFlowBind struct {
	ID         uint64     `gorm:"column:id;primaryKey" json:"id"`                                           // 唯一id，雪花算法
	AuditType  string     `gorm:"column:audit_type;not null" json:"audit_type"`                             // 审核类型： af-catalog-online 上线审核  af-catalog-change 变更审核  af-catalog-offline 下线审核  af-data-catalog-download 下载审核
	ProcDefKey string     `gorm:"column:proc_def_key;not null" json:"proc_def_key"`                         // 审核流程key
	CreatedAt  *util.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"` // 创建时间
	CreatorUID string     `gorm:"column:creator_uid;not null" json:"creator_uid,omitempty"`                 // 创建用户ID
	UpdatedAt  *util.Time `gorm:"column:updated_at;not null" json:"updated_at"`                             // 更新时间
	UpdaterUID string     `gorm:"column:updater_uid" json:"updater_uid,omitempty"`                          // 更新用户ID
}

func (m *TDataCatalogAuditFlowBind) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataCatalogResourceMount's table name
func (*TDataCatalogAuditFlowBind) TableName() string {
	return TableNameTDataCatalogAuditFlowBind
}
