// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTDataCatalogDownloadApply = "t_data_catalog_download_apply"

// TDataCatalogDownloadApply mapped from table <t_data_catalog_download_apply>
type TDataCatalogDownloadApply struct {
	ID           uint64     `gorm:"column:id;primaryKey" json:"id"`                                           // 唯一id，雪花算法
	UID          string     `gorm:"column:uid;not null" json:"uid"`                                           // 用户ID
	Code         string     `gorm:"column:code;not null" json:"code"`                                         // 目录编码
	ApplyDays    int        `gorm:"column:apply_days;not null" json:"apply_days"`                             // 申请天数（7、15、30天）
	ApplyReason  string     `gorm:"column:apply_reason;not null" json:"apply_reason"`                         // 申请理由
	AuditApplySN uint64     `gorm:"column:audit_apply_sn;not null" json:"audit_apply_sn"`                     // 发起审核申请序号
	AuditType    string     `gorm:"column:audit_type;not null" json:"audit_type"`                             // 审核类型，默认af-data-catalog-download
	State        int8       `gorm:"column:state;not null;default:1" json:"state"`                             // 申请审核状态 1 审核中 2 审核通过 3 审核不通过
	CreatedAt    *util.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"` // 审核创建时间
	UpdatedAt    *util.Time `gorm:"column:updated_at;not null" json:"updated_at"`                             // 审核结果更新时间
	FlowID       string     `gorm:"column:flow_id" json:"flow_id"`                                            // 审批流程实例ID
	ProcDefKey   string     `gorm:"column:proc_def_key" json:"proc_def_key"`                                  // 审核流程key
	FlowApplyId  string     `gorm:"column:flow_apply_id" json:"flow_apply_id"`                                // 审核流程ID
}

func (m *TDataCatalogDownloadApply) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TDataCatalogDownloadApply's table name
func (*TDataCatalogDownloadApply) TableName() string {
	return TableNameTDataCatalogDownloadApply
}
