// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

type TUserDataCatalogStatsInfo struct {
	ID         uint64     `gorm:"column:id;primaryKey" json:"id,string"`                                    // 唯一id，雪花算法
	Code       string     `gorm:"column:code;not null" json:"code"`                                         // 目录编码
	UserID     string     `gorm:"column:user_id;not null" json:"user_id"`                                   // 创建用户ID
	PreviewNum int        `gorm:"column:preview_num;not null;default:0" json:"preview_num"`                 // 预览数
	CreatedAt  *util.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"` // 创建时间
	UpdatedAt  *util.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`              // 更新时间
}

func (m *TUserDataCatalogStatsInfo) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName UserDataCatalogStatsInfo's table name
func (*TUserDataCatalogStatsInfo) TableName() string {
	return "t_user_data_catalog_stats_info"
}
