// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTUserDataCatalogRel = "t_user_data_catalog_rel"

// TUserDataCatalogRel mapped from table <t_user_data_catalog_rel>
type TUserDataCatalogRel struct {
	ID          uint64     `gorm:"column:id;primaryKey" json:"id"`                                           // 唯一id，雪花算法
	UID         string     `gorm:"column:uid;not null" json:"uid"`                                           // 用户ID
	Code        string     `gorm:"column:code;not null" json:"code"`                                         // 目录编码
	ApplyID     uint64     `gorm:"column:apply_id;not null" json:"apply_id"`                                 // 申请记录ID
	CreatedAt   *util.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"` // 记录创建时间
	UpdatedAt   *util.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"` // 记录更新时间
	ExpiredAt   *util.Time `gorm:"column:expired_at" json:"expired_at"`                                      // 权限过期时间
	ExpiredFlag int8       `gorm:"column:expired_flag;not nul" json:"expired_flag"`                          // 权限过期标记 1 未过期 2 已过期
}

func (m *TUserDataCatalogRel) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
	}

	return err
}

// TableName TUserDataCatalogRel's table name
func (*TUserDataCatalogRel) TableName() string {
	return TableNameTUserDataCatalogRel
}
