// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/models"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameTreeNode = "tree_node"

// TreeNode mapped from table <tree_node>
type TreeNode struct {
	ID           models.ModelID        `gorm:"column:id;primaryKey" json:"id"`                                // 主键，雪花id
	TreeID       models.ModelID        `gorm:"column:tree_id;not null" json:"tree_id"`                        // 所属目录组
	ParentID     models.ModelID        `gorm:"column:parent_id;not null" json:"parent_id"`                    // 父目录类别id，为0表示没有父id
	Name         string                `gorm:"column:name;not null" json:"name"`                              // 目录类别名称
	Describe     string                `gorm:"column:describe;not null" json:"describe"`                      // 目录类别描述
	CategoryNum  string                `gorm:"column:category_num;not null" json:"category_num"`              // 类目编码
	MgmDepID     string                `gorm:"column:mgm_dep_id;not null" json:"mgm_dep_id"`                  // 管理部门id
	MgmDepName   string                `gorm:"column:mgm_dep_name;not null" json:"mgm_dep_name"`              // 管理部门名称
	SortWeight   uint64                `gorm:"column:sort_weight;not null" json:"sort_weight"`                // 排序权重
	CreatedAt    *time.Time            `gorm:"column:created_at;not null" json:"created_at"`                  // 创建时间
	CreatedByUID models.UserID         `gorm:"column:created_by_uid;not null" json:"created_by_uid"`          // 创建用户ID
	UpdatedAt    *time.Time            `gorm:"column:updated_at;not null" json:"updated_at"`                  // 更新时间
	UpdatedByUID models.UserID         `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`          // 更新用户ID
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"` // 删除时间(逻辑删除)
}

func (m *TreeNode) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID.Uint64() > 0 {
		return nil
	}

	id, err := util.NewUniqueID()
	if err != nil {
		return err
	}

	m.ID = models.NewModelID(id)

	return nil
}

// TableName TreeNode's table name
func (*TreeNode) TableName() string {
	return TableNameTreeNode
}
