// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/models"
	"github.com/kweaver-ai/dsg/services/apps/data-catalog/common/util"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameTreeInfo = "tree_info"

// TreeInfo mapped from table <tree_info>
type TreeInfo struct {
	ID           models.ModelID        `gorm:"column:id;primaryKey" json:"id"`                                // 主键，雪花id
	Name         string                `gorm:"column:name;not null" json:"name"`                              // 目录组名称
	RootNodeID   models.ModelID        `gorm:"column:root_node_id;not null" json:"root_node_id"`              // 目录组的根目录类别id，基本不变，冗余
	CreatedAt    *time.Time            `gorm:"column:created_at;not null" json:"created_at"`                  // 创建时间
	CreatedByUID models.UserID         `gorm:"column:created_by_uid;not null" json:"created_by_uid"`          // 创建用户ID
	UpdatedAt    *time.Time            `gorm:"column:updated_at;not null" json:"updated_at"`                  // 更新时间
	UpdatedByUID models.UserID         `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`          // 更新用户ID
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"` // 删除时间(逻辑删除)
}

func (m *TreeInfo) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID.Uint64() > 0 {
		return nil
	}

	id, err := util.NewUniqueID()
	if err != nil {
		return err
	}

	m.ID = models.NewModelID(id)

	return nil
}

// TableName TreeInfo's table name
func (*TreeInfo) TableName() string {
	return TableNameTreeInfo
}
