// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/thrift_gen/ethriftexception"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/thrift_gen/evfs"
	"github.com/kweaver-ai/idrm-go-common/thrift"
)

var _ = ethriftexception.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  ncTEVFSGNSObjectSet GetSubObjectSet()")
	fmt.Fprintln(os.Stderr, "  void CreateDir(string gns, string dirName)")
	fmt.Fprintln(os.Stderr, "  ncTEVFSGNSObjectSet ListDirWithoutPermCheck(string gns)")
	fmt.Fprintln(os.Stderr, "  ncTEVFSGNSObjectSet ListFileWithoutPermCheck(string gns)")
	fmt.Fprintln(os.Stderr, "  string CopyWithoutPermCheck(string userId, string srcGns, string newParentGns, i32 ondup)")
	fmt.Fprintln(os.Stderr, "  bool CheckMgrObjectEmptyWithoutRecycleBin(string gns)")
	fmt.Fprintln(os.Stderr, "  string ConvertPath(string gns)")
	fmt.Fprintln(os.Stderr, "   ConvertPathByBatch( gnsList)")
	fmt.Fprintln(os.Stderr, "  string ConvertNamePath(string gns)")
	fmt.Fprintln(os.Stderr, "  void SetVersionMaxNum(i32 maxNum)")
	fmt.Fprintln(os.Stderr, "  i32 GetVersionMaxNum()")
	fmt.Fprintln(os.Stderr, "  void SetVersionBuildCycle(i32 buildCycle)")
	fmt.Fprintln(os.Stderr, "  i32 GetVersionBuildCycle()")
	fmt.Fprintln(os.Stderr, "  void SetLinkAccessCodeStatus(bool enable)")
	fmt.Fprintln(os.Stderr, "  bool GetLinkAccessCodeStatus()")
	fmt.Fprintln(os.Stderr, "  void SetLargeFileLimit(ncTEVFSLargeFileLimitConf conf)")
	fmt.Fprintln(os.Stderr, "  ncTEVFSLargeFileLimitConf GetLargeFileLimit()")
	fmt.Fprintln(os.Stderr, "  void SetFileSuffixLimit( suffixDocs)")
	fmt.Fprintln(os.Stderr, "   GetFileSuffixLimit()")
	fmt.Fprintln(os.Stderr, "  ncTETSResourceInfo GetETSResourceInfo(string gns)")
	fmt.Fprintln(os.Stderr, "   GetAllResourceInfo( gnsList)")
	fmt.Fprintln(os.Stderr, "  void ResetListCache()")
	fmt.Fprintln(os.Stderr, "  void EnableListCache()")
	fmt.Fprintln(os.Stderr, "  void DisableListCache()")
	fmt.Fprintln(os.Stderr, "  void EnableListCacheStats()")
	fmt.Fprintln(os.Stderr, "  void DisableListCacheStats()")
	fmt.Fprintln(os.Stderr, "  ncTEVFSListCacheInfo FetchListCacheInfo()")
	fmt.Fprintln(os.Stderr, "  ncTEVFSFilesCount GetCurrentFilesTotal()")
	fmt.Fprintln(os.Stderr, "   GetFilesTotal(ncTEVFSDate date, ncTEVFSDateUnit dateUnit)")
	fmt.Fprintln(os.Stderr, "   GetFilesChangeInfo(ncTEVFSDate date, ncTEVFSDateUnit dateUnit)")
	fmt.Fprintln(os.Stderr, "  ncTEVFSQuotaInfo FetchSpaceQuotaInfo(string cidGns)")
	fmt.Fprintln(os.Stderr, "  void SetQuotaInfo(string cidGns, i64 quota)")
	fmt.Fprintln(os.Stderr, "  i64 FetchOperatedInfo(ncTEVFSDate begDate, ncTEVFSDate endDate, ncTEVFSOperatedType opType)")
	fmt.Fprintln(os.Stderr, "   FetchAllOperatedInfo(ncTEVFSDate begDate, ncTEVFSDate endDate)")
	fmt.Fprintln(os.Stderr, "  bool GetRapidUploadSupport()")
	fmt.Fprintln(os.Stderr, "  void SetRapidUploadSupport(bool support)")
	fmt.Fprintln(os.Stderr, "  bool GetCrossOSSRapidUploadStatus()")
	fmt.Fprintln(os.Stderr, "  void SetCrossOSSRapidUploadStatus(bool enable)")
	fmt.Fprintln(os.Stderr, "  ncTEVFSRapidStatisInfo FetchRapidStatisInfo()")
	fmt.Fprintln(os.Stderr, "  i64 FetchTotalRapidFile(string fileName, i64 fileSizeMin, i64 fileSizeMax, i64 beginDate, i64 endDate)")
	fmt.Fprintln(os.Stderr, "   FetchRapidFilesInfo(string fileName, i64 fileSizeMin, i64 fileSizeMax, i64 beginDate, i64 endDate, i64 offset, i32 rows)")
	fmt.Fprintln(os.Stderr, "  i32 GetCSFLevel(string gns)")
	fmt.Fprintln(os.Stderr, "  i32 GetDirCSFLevel(string gns)")
	fmt.Fprintln(os.Stderr, "  void DeleteFavoritesByUserId(string userId)")
	fmt.Fprintln(os.Stderr, "  void SetStoragePrefix(string prefix)")
	fmt.Fprintln(os.Stderr, "  string GetStoragePrefix()")
	fmt.Fprintln(os.Stderr, "  void SetPreConvertEnable(bool enable)")
	fmt.Fprintln(os.Stderr, "  void ObjMeta_AddAppInfo(string appId, string appName)")
	fmt.Fprintln(os.Stderr, "   ObjMeta_GetAppInfos()")
	fmt.Fprintln(os.Stderr, "  void ObjMeta_SetAppName(string appId, string appName)")
	fmt.Fprintln(os.Stderr, "  void ObjMeta_SetAppStatus(string appId, i32 status)")
	fmt.Fprintln(os.Stderr, "  void ObjMeta_DeleteAppInfo(string appId)")
	fmt.Fprintln(os.Stderr, "  void SetUserDownloadLimitStatus(bool enable)")
	fmt.Fprintln(os.Stderr, "  bool GetUserDonwloadLimitStatus()")
	fmt.Fprintln(os.Stderr, "  void AddUserDownloadLimitInfos( limitInfos)")
	fmt.Fprintln(os.Stderr, "   GetUserDownloadLimitInfos()")
	fmt.Fprintln(os.Stderr, "  void DeleteUserDownloadLimitInfos( userIds)")
	fmt.Fprintln(os.Stderr, "   GetQuarantineFileList(ncTFiltrationParam filter, i64 start, i64 limit)")
	fmt.Fprintln(os.Stderr, "   GetFileVersionList(string docid, string key)")
	fmt.Fprintln(os.Stderr, "  i64 GetQuarantineFileCount(ncTFiltrationParam filter)")
	fmt.Fprintln(os.Stderr, "  ncTOSDowndloadRetParam OSDownload(string gns, string versionId, string authType, string reqHost, bool usehttps, string saveName)")
	fmt.Fprintln(os.Stderr, "  string RestoreQuarantineFile(string gns, i32 ondup)")
	fmt.Fprintln(os.Stderr, "  string DeleteQuarantineFile(string gns)")
	fmt.Fprintln(os.Stderr, "  ncTQuarantineRetMsg Quarantine(string docId, string reason, ncTEVFSQuarantineType type)")
	fmt.Fprintln(os.Stderr, "  ncTQuarantineConfig QRT_GetConfig()")
	fmt.Fprintln(os.Stderr, "  void QRT_SetAppealProtectTime(i32 days)")
	fmt.Fprintln(os.Stderr, "  void QRT_SetAutoDeleteTime(i32 days)")
	fmt.Fprintln(os.Stderr, "  string QRT_AppealApproval(string docid, bool approvalResult, i32 ondup, string appealSuggest)")
	fmt.Fprintln(os.Stderr, "  ncTEVFSFileInfoCount GetFileInfoCount(string name)")
	fmt.Fprintln(os.Stderr, "   GetPageFileInfo(ncTEVFSGetPageFileInfoParam param)")
	fmt.Fprintln(os.Stderr, "   GetFileRevisions(string docId)")
	fmt.Fprintln(os.Stderr, "  bool GetDocDueRemindStatus()")
	fmt.Fprintln(os.Stderr, "  void SetDocDueRemindStatus(bool enable)")
	fmt.Fprintln(os.Stderr, "  i32 GetDocDueRemindMsgSendTime()")
	fmt.Fprintln(os.Stderr, "  void SetDocDueRemindMsgSendTime(i32 hour)")
	fmt.Fprintln(os.Stderr, "  void SetNSQPubEnableStatus(bool enable)")
	fmt.Fprintln(os.Stderr, "  bool GetNSQPubEnableStatus()")
	fmt.Fprintln(os.Stderr, "  void EVFS_ThriftServerPing()")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()

	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := evfs.NewNcTEVFSClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "GetSubObjectSet":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetSubObjectSet requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetSubObjectSet(context.Background()))
		fmt.Print("\n")
		break
	case "CreateDir":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "CreateDir requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.CreateDir(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "ListDirWithoutPermCheck":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListDirWithoutPermCheck requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ListDirWithoutPermCheck(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ListFileWithoutPermCheck":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ListFileWithoutPermCheck requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ListFileWithoutPermCheck(context.Background(), value0))
		fmt.Print("\n")
		break
	case "CopyWithoutPermCheck":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "CopyWithoutPermCheck requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		tmp3, err193 := (strconv.Atoi(flag.Arg(4)))
		if err193 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.CopyWithoutPermCheck(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "CheckMgrObjectEmptyWithoutRecycleBin":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "CheckMgrObjectEmptyWithoutRecycleBin requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.CheckMgrObjectEmptyWithoutRecycleBin(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ConvertPath":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ConvertPath requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ConvertPath(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ConvertPathByBatch":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ConvertPathByBatch requires 1 args")
			flag.Usage()
		}
		arg196 := flag.Arg(1)
		mbTrans197 := thrift.NewTMemoryBufferLen(len(arg196))
		defer mbTrans197.Close()
		_, err198 := mbTrans197.WriteString(arg196)
		if err198 != nil {
			Usage()
			return
		}
		factory199 := thrift.NewTJSONProtocolFactory()
		jsProt200 := factory199.GetProtocol(mbTrans197)
		containerStruct0 := evfs.NewNcTEVFSConvertPathByBatchArgs()
		err201 := containerStruct0.ReadField1(jsProt200)
		if err201 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.GnsList
		value0 := argvalue0
		fmt.Print(client.ConvertPathByBatch(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ConvertNamePath":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ConvertNamePath requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ConvertNamePath(context.Background(), value0))
		fmt.Print("\n")
		break
	case "SetVersionMaxNum":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetVersionMaxNum requires 1 args")
			flag.Usage()
		}
		tmp0, err203 := (strconv.Atoi(flag.Arg(1)))
		if err203 != nil {
			Usage()
			return
		}
		argvalue0 := int32(tmp0)
		value0 := argvalue0
		fmt.Print(client.SetVersionMaxNum(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetVersionMaxNum":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetVersionMaxNum requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetVersionMaxNum(context.Background()))
		fmt.Print("\n")
		break
	case "SetVersionBuildCycle":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetVersionBuildCycle requires 1 args")
			flag.Usage()
		}
		tmp0, err204 := (strconv.Atoi(flag.Arg(1)))
		if err204 != nil {
			Usage()
			return
		}
		argvalue0 := int32(tmp0)
		value0 := argvalue0
		fmt.Print(client.SetVersionBuildCycle(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetVersionBuildCycle":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetVersionBuildCycle requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetVersionBuildCycle(context.Background()))
		fmt.Print("\n")
		break
	case "SetLinkAccessCodeStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetLinkAccessCodeStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetLinkAccessCodeStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetLinkAccessCodeStatus":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetLinkAccessCodeStatus requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetLinkAccessCodeStatus(context.Background()))
		fmt.Print("\n")
		break
	case "SetLargeFileLimit":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetLargeFileLimit requires 1 args")
			flag.Usage()
		}
		arg206 := flag.Arg(1)
		mbTrans207 := thrift.NewTMemoryBufferLen(len(arg206))
		defer mbTrans207.Close()
		_, err208 := mbTrans207.WriteString(arg206)
		if err208 != nil {
			Usage()
			return
		}
		factory209 := thrift.NewTJSONProtocolFactory()
		jsProt210 := factory209.GetProtocol(mbTrans207)
		argvalue0 := evfs.NewNcTEVFSLargeFileLimitConf()
		err211 := argvalue0.Read(jsProt210)
		if err211 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SetLargeFileLimit(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetLargeFileLimit":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetLargeFileLimit requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetLargeFileLimit(context.Background()))
		fmt.Print("\n")
		break
	case "SetFileSuffixLimit":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetFileSuffixLimit requires 1 args")
			flag.Usage()
		}
		arg212 := flag.Arg(1)
		mbTrans213 := thrift.NewTMemoryBufferLen(len(arg212))
		defer mbTrans213.Close()
		_, err214 := mbTrans213.WriteString(arg212)
		if err214 != nil {
			Usage()
			return
		}
		factory215 := thrift.NewTJSONProtocolFactory()
		jsProt216 := factory215.GetProtocol(mbTrans213)
		containerStruct0 := evfs.NewNcTEVFSSetFileSuffixLimitArgs()
		err217 := containerStruct0.ReadField1(jsProt216)
		if err217 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.SuffixDocs
		value0 := argvalue0
		fmt.Print(client.SetFileSuffixLimit(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetFileSuffixLimit":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetFileSuffixLimit requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetFileSuffixLimit(context.Background()))
		fmt.Print("\n")
		break
	case "GetETSResourceInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetETSResourceInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetETSResourceInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetAllResourceInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAllResourceInfo requires 1 args")
			flag.Usage()
		}
		arg219 := flag.Arg(1)
		mbTrans220 := thrift.NewTMemoryBufferLen(len(arg219))
		defer mbTrans220.Close()
		_, err221 := mbTrans220.WriteString(arg219)
		if err221 != nil {
			Usage()
			return
		}
		factory222 := thrift.NewTJSONProtocolFactory()
		jsProt223 := factory222.GetProtocol(mbTrans220)
		containerStruct0 := evfs.NewNcTEVFSGetAllResourceInfoArgs()
		err224 := containerStruct0.ReadField1(jsProt223)
		if err224 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.GnsList
		value0 := argvalue0
		fmt.Print(client.GetAllResourceInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ResetListCache":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "ResetListCache requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ResetListCache(context.Background()))
		fmt.Print("\n")
		break
	case "EnableListCache":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "EnableListCache requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.EnableListCache(context.Background()))
		fmt.Print("\n")
		break
	case "DisableListCache":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "DisableListCache requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.DisableListCache(context.Background()))
		fmt.Print("\n")
		break
	case "EnableListCacheStats":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "EnableListCacheStats requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.EnableListCacheStats(context.Background()))
		fmt.Print("\n")
		break
	case "DisableListCacheStats":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "DisableListCacheStats requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.DisableListCacheStats(context.Background()))
		fmt.Print("\n")
		break
	case "FetchListCacheInfo":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FetchListCacheInfo requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FetchListCacheInfo(context.Background()))
		fmt.Print("\n")
		break
	case "GetCurrentFilesTotal":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetCurrentFilesTotal requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetCurrentFilesTotal(context.Background()))
		fmt.Print("\n")
		break
	case "GetFilesTotal":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "GetFilesTotal requires 2 args")
			flag.Usage()
		}
		arg225 := flag.Arg(1)
		mbTrans226 := thrift.NewTMemoryBufferLen(len(arg225))
		defer mbTrans226.Close()
		_, err227 := mbTrans226.WriteString(arg225)
		if err227 != nil {
			Usage()
			return
		}
		factory228 := thrift.NewTJSONProtocolFactory()
		jsProt229 := factory228.GetProtocol(mbTrans226)
		argvalue0 := evfs.NewNcTEVFSDate()
		err230 := argvalue0.Read(jsProt229)
		if err230 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		tmp1, err := (strconv.Atoi(flag.Arg(2)))
		if err != nil {
			Usage()
			return
		}
		argvalue1 := evfs.NcTEVFSDateUnit(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetFilesTotal(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "GetFilesChangeInfo":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "GetFilesChangeInfo requires 2 args")
			flag.Usage()
		}
		arg231 := flag.Arg(1)
		mbTrans232 := thrift.NewTMemoryBufferLen(len(arg231))
		defer mbTrans232.Close()
		_, err233 := mbTrans232.WriteString(arg231)
		if err233 != nil {
			Usage()
			return
		}
		factory234 := thrift.NewTJSONProtocolFactory()
		jsProt235 := factory234.GetProtocol(mbTrans232)
		argvalue0 := evfs.NewNcTEVFSDate()
		err236 := argvalue0.Read(jsProt235)
		if err236 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		tmp1, err := (strconv.Atoi(flag.Arg(2)))
		if err != nil {
			Usage()
			return
		}
		argvalue1 := evfs.NcTEVFSDateUnit(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetFilesChangeInfo(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "FetchSpaceQuotaInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "FetchSpaceQuotaInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.FetchSpaceQuotaInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "SetQuotaInfo":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "SetQuotaInfo requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1, err239 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err239 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.SetQuotaInfo(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "FetchOperatedInfo":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "FetchOperatedInfo requires 3 args")
			flag.Usage()
		}
		arg240 := flag.Arg(1)
		mbTrans241 := thrift.NewTMemoryBufferLen(len(arg240))
		defer mbTrans241.Close()
		_, err242 := mbTrans241.WriteString(arg240)
		if err242 != nil {
			Usage()
			return
		}
		factory243 := thrift.NewTJSONProtocolFactory()
		jsProt244 := factory243.GetProtocol(mbTrans241)
		argvalue0 := evfs.NewNcTEVFSDate()
		err245 := argvalue0.Read(jsProt244)
		if err245 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		arg246 := flag.Arg(2)
		mbTrans247 := thrift.NewTMemoryBufferLen(len(arg246))
		defer mbTrans247.Close()
		_, err248 := mbTrans247.WriteString(arg246)
		if err248 != nil {
			Usage()
			return
		}
		factory249 := thrift.NewTJSONProtocolFactory()
		jsProt250 := factory249.GetProtocol(mbTrans247)
		argvalue1 := evfs.NewNcTEVFSDate()
		err251 := argvalue1.Read(jsProt250)
		if err251 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := evfs.NcTEVFSOperatedType(tmp2)
		value2 := argvalue2
		fmt.Print(client.FetchOperatedInfo(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "FetchAllOperatedInfo":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "FetchAllOperatedInfo requires 2 args")
			flag.Usage()
		}
		arg252 := flag.Arg(1)
		mbTrans253 := thrift.NewTMemoryBufferLen(len(arg252))
		defer mbTrans253.Close()
		_, err254 := mbTrans253.WriteString(arg252)
		if err254 != nil {
			Usage()
			return
		}
		factory255 := thrift.NewTJSONProtocolFactory()
		jsProt256 := factory255.GetProtocol(mbTrans253)
		argvalue0 := evfs.NewNcTEVFSDate()
		err257 := argvalue0.Read(jsProt256)
		if err257 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		arg258 := flag.Arg(2)
		mbTrans259 := thrift.NewTMemoryBufferLen(len(arg258))
		defer mbTrans259.Close()
		_, err260 := mbTrans259.WriteString(arg258)
		if err260 != nil {
			Usage()
			return
		}
		factory261 := thrift.NewTJSONProtocolFactory()
		jsProt262 := factory261.GetProtocol(mbTrans259)
		argvalue1 := evfs.NewNcTEVFSDate()
		err263 := argvalue1.Read(jsProt262)
		if err263 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.FetchAllOperatedInfo(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "GetRapidUploadSupport":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetRapidUploadSupport requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetRapidUploadSupport(context.Background()))
		fmt.Print("\n")
		break
	case "SetRapidUploadSupport":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetRapidUploadSupport requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetRapidUploadSupport(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetCrossOSSRapidUploadStatus":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetCrossOSSRapidUploadStatus requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetCrossOSSRapidUploadStatus(context.Background()))
		fmt.Print("\n")
		break
	case "SetCrossOSSRapidUploadStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetCrossOSSRapidUploadStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetCrossOSSRapidUploadStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "FetchRapidStatisInfo":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FetchRapidStatisInfo requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FetchRapidStatisInfo(context.Background()))
		fmt.Print("\n")
		break
	case "FetchTotalRapidFile":
		if flag.NArg()-1 != 5 {
			fmt.Fprintln(os.Stderr, "FetchTotalRapidFile requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1, err267 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err267 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err268 := (strconv.ParseInt(flag.Arg(3), 10, 64))
		if err268 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		argvalue3, err269 := (strconv.ParseInt(flag.Arg(4), 10, 64))
		if err269 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		argvalue4, err270 := (strconv.ParseInt(flag.Arg(5), 10, 64))
		if err270 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		fmt.Print(client.FetchTotalRapidFile(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "FetchRapidFilesInfo":
		if flag.NArg()-1 != 7 {
			fmt.Fprintln(os.Stderr, "FetchRapidFilesInfo requires 7 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1, err272 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err272 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err273 := (strconv.ParseInt(flag.Arg(3), 10, 64))
		if err273 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		argvalue3, err274 := (strconv.ParseInt(flag.Arg(4), 10, 64))
		if err274 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		argvalue4, err275 := (strconv.ParseInt(flag.Arg(5), 10, 64))
		if err275 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		argvalue5, err276 := (strconv.ParseInt(flag.Arg(6), 10, 64))
		if err276 != nil {
			Usage()
			return
		}
		value5 := argvalue5
		tmp6, err277 := (strconv.Atoi(flag.Arg(7)))
		if err277 != nil {
			Usage()
			return
		}
		argvalue6 := int32(tmp6)
		value6 := argvalue6
		fmt.Print(client.FetchRapidFilesInfo(context.Background(), value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "GetCSFLevel":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetCSFLevel requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetCSFLevel(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetDirCSFLevel":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDirCSFLevel requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetDirCSFLevel(context.Background(), value0))
		fmt.Print("\n")
		break
	case "DeleteFavoritesByUserId":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteFavoritesByUserId requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DeleteFavoritesByUserId(context.Background(), value0))
		fmt.Print("\n")
		break
	case "SetStoragePrefix":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetStoragePrefix requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.SetStoragePrefix(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetStoragePrefix":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetStoragePrefix requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetStoragePrefix(context.Background()))
		fmt.Print("\n")
		break
	case "SetPreConvertEnable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetPreConvertEnable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetPreConvertEnable(context.Background(), value0))
		fmt.Print("\n")
		break
	case "ObjMeta_AddAppInfo":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "ObjMeta_AddAppInfo requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.ObjMeta_AddAppInfo(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "ObjMeta_GetAppInfos":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "ObjMeta_GetAppInfos requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ObjMeta_GetAppInfos(context.Background()))
		fmt.Print("\n")
		break
	case "ObjMeta_SetAppName":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "ObjMeta_SetAppName requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.ObjMeta_SetAppName(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "ObjMeta_SetAppStatus":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "ObjMeta_SetAppStatus requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		tmp1, err288 := (strconv.Atoi(flag.Arg(2)))
		if err288 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.ObjMeta_SetAppStatus(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "ObjMeta_DeleteAppInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ObjMeta_DeleteAppInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ObjMeta_DeleteAppInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "SetUserDownloadLimitStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetUserDownloadLimitStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetUserDownloadLimitStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetUserDonwloadLimitStatus":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetUserDonwloadLimitStatus requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetUserDonwloadLimitStatus(context.Background()))
		fmt.Print("\n")
		break
	case "AddUserDownloadLimitInfos":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "AddUserDownloadLimitInfos requires 1 args")
			flag.Usage()
		}
		arg291 := flag.Arg(1)
		mbTrans292 := thrift.NewTMemoryBufferLen(len(arg291))
		defer mbTrans292.Close()
		_, err293 := mbTrans292.WriteString(arg291)
		if err293 != nil {
			Usage()
			return
		}
		factory294 := thrift.NewTJSONProtocolFactory()
		jsProt295 := factory294.GetProtocol(mbTrans292)
		containerStruct0 := evfs.NewNcTEVFSAddUserDownloadLimitInfosArgs()
		err296 := containerStruct0.ReadField1(jsProt295)
		if err296 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.LimitInfos
		value0 := argvalue0
		fmt.Print(client.AddUserDownloadLimitInfos(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetUserDownloadLimitInfos":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetUserDownloadLimitInfos requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetUserDownloadLimitInfos(context.Background()))
		fmt.Print("\n")
		break
	case "DeleteUserDownloadLimitInfos":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteUserDownloadLimitInfos requires 1 args")
			flag.Usage()
		}
		arg297 := flag.Arg(1)
		mbTrans298 := thrift.NewTMemoryBufferLen(len(arg297))
		defer mbTrans298.Close()
		_, err299 := mbTrans298.WriteString(arg297)
		if err299 != nil {
			Usage()
			return
		}
		factory300 := thrift.NewTJSONProtocolFactory()
		jsProt301 := factory300.GetProtocol(mbTrans298)
		containerStruct0 := evfs.NewNcTEVFSDeleteUserDownloadLimitInfosArgs()
		err302 := containerStruct0.ReadField1(jsProt301)
		if err302 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.UserIds
		value0 := argvalue0
		fmt.Print(client.DeleteUserDownloadLimitInfos(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetQuarantineFileList":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "GetQuarantineFileList requires 3 args")
			flag.Usage()
		}
		arg303 := flag.Arg(1)
		mbTrans304 := thrift.NewTMemoryBufferLen(len(arg303))
		defer mbTrans304.Close()
		_, err305 := mbTrans304.WriteString(arg303)
		if err305 != nil {
			Usage()
			return
		}
		factory306 := thrift.NewTJSONProtocolFactory()
		jsProt307 := factory306.GetProtocol(mbTrans304)
		argvalue0 := evfs.NewNcTFiltrationParam()
		err308 := argvalue0.Read(jsProt307)
		if err308 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err309 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err309 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2, err310 := (strconv.ParseInt(flag.Arg(3), 10, 64))
		if err310 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetQuarantineFileList(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "GetFileVersionList":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "GetFileVersionList requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetFileVersionList(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "GetQuarantineFileCount":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetQuarantineFileCount requires 1 args")
			flag.Usage()
		}
		arg313 := flag.Arg(1)
		mbTrans314 := thrift.NewTMemoryBufferLen(len(arg313))
		defer mbTrans314.Close()
		_, err315 := mbTrans314.WriteString(arg313)
		if err315 != nil {
			Usage()
			return
		}
		factory316 := thrift.NewTJSONProtocolFactory()
		jsProt317 := factory316.GetProtocol(mbTrans314)
		argvalue0 := evfs.NewNcTFiltrationParam()
		err318 := argvalue0.Read(jsProt317)
		if err318 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetQuarantineFileCount(context.Background(), value0))
		fmt.Print("\n")
		break
	case "OSDownload":
		if flag.NArg()-1 != 6 {
			fmt.Fprintln(os.Stderr, "OSDownload requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		argvalue5 := flag.Arg(6)
		value5 := argvalue5
		fmt.Print(client.OSDownload(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "RestoreQuarantineFile":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "RestoreQuarantineFile requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		tmp1, err326 := (strconv.Atoi(flag.Arg(2)))
		if err326 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.RestoreQuarantineFile(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "DeleteQuarantineFile":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteQuarantineFile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DeleteQuarantineFile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "Quarantine":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "Quarantine requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := evfs.NcTEVFSQuarantineType(tmp2)
		value2 := argvalue2
		fmt.Print(client.Quarantine(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "QRT_GetConfig":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "QRT_GetConfig requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.QRT_GetConfig(context.Background()))
		fmt.Print("\n")
		break
	case "QRT_SetAppealProtectTime":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QRT_SetAppealProtectTime requires 1 args")
			flag.Usage()
		}
		tmp0, err330 := (strconv.Atoi(flag.Arg(1)))
		if err330 != nil {
			Usage()
			return
		}
		argvalue0 := int32(tmp0)
		value0 := argvalue0
		fmt.Print(client.QRT_SetAppealProtectTime(context.Background(), value0))
		fmt.Print("\n")
		break
	case "QRT_SetAutoDeleteTime":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QRT_SetAutoDeleteTime requires 1 args")
			flag.Usage()
		}
		tmp0, err331 := (strconv.Atoi(flag.Arg(1)))
		if err331 != nil {
			Usage()
			return
		}
		argvalue0 := int32(tmp0)
		value0 := argvalue0
		fmt.Print(client.QRT_SetAutoDeleteTime(context.Background(), value0))
		fmt.Print("\n")
		break
	case "QRT_AppealApproval":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "QRT_AppealApproval requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2) == "true"
		value1 := argvalue1
		tmp2, err334 := (strconv.Atoi(flag.Arg(3)))
		if err334 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		fmt.Print(client.QRT_AppealApproval(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "GetFileInfoCount":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetFileInfoCount requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetFileInfoCount(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetPageFileInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetPageFileInfo requires 1 args")
			flag.Usage()
		}
		arg337 := flag.Arg(1)
		mbTrans338 := thrift.NewTMemoryBufferLen(len(arg337))
		defer mbTrans338.Close()
		_, err339 := mbTrans338.WriteString(arg337)
		if err339 != nil {
			Usage()
			return
		}
		factory340 := thrift.NewTJSONProtocolFactory()
		jsProt341 := factory340.GetProtocol(mbTrans338)
		argvalue0 := evfs.NewNcTEVFSGetPageFileInfoParam()
		err342 := argvalue0.Read(jsProt341)
		if err342 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetPageFileInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetFileRevisions":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetFileRevisions requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetFileRevisions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetDocDueRemindStatus":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetDocDueRemindStatus requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetDocDueRemindStatus(context.Background()))
		fmt.Print("\n")
		break
	case "SetDocDueRemindStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetDocDueRemindStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetDocDueRemindStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetDocDueRemindMsgSendTime":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetDocDueRemindMsgSendTime requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetDocDueRemindMsgSendTime(context.Background()))
		fmt.Print("\n")
		break
	case "SetDocDueRemindMsgSendTime":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetDocDueRemindMsgSendTime requires 1 args")
			flag.Usage()
		}
		tmp0, err345 := (strconv.Atoi(flag.Arg(1)))
		if err345 != nil {
			Usage()
			return
		}
		argvalue0 := int32(tmp0)
		value0 := argvalue0
		fmt.Print(client.SetDocDueRemindMsgSendTime(context.Background(), value0))
		fmt.Print("\n")
		break
	case "SetNSQPubEnableStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SetNSQPubEnableStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1) == "true"
		value0 := argvalue0
		fmt.Print(client.SetNSQPubEnableStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "GetNSQPubEnableStatus":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetNSQPubEnableStatus requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetNSQPubEnableStatus(context.Background()))
		fmt.Print("\n")
		break
	case "EVFS_ThriftServerPing":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "EVFS_ThriftServerPing requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.EVFS_ThriftServerPing(context.Background()))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
