// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/callbacks"
	impl11 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/gorm/classify/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/gorm/form_subject_relation/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/gorm/standard_info/impl"
	impl2 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/gorm/subject_domain/impl"
	impl3 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/gorm/user/impl"
	impl10 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driven/rest/sailor_service/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driver"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driver/middleware"
	v1_3 "github.com/kweaver-ai/dsg/services/apps/data-subject/adapter/driver/subject_domain/v1"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/common/app"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/common/initialization"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/domain/excel_process"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/domain/subject_domain"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/infrastructure/config"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/infrastructure/db"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/infrastructure/mq/kafka"
	v1_2 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	impl12 "github.com/kweaver-ai/idrm-go-common/rest/af_sailor/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	"github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl8 "github.com/kweaver-ai/idrm-go-common/rest/data_application_service/impl"
	impl7 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	impl9 "github.com/kweaver-ai/idrm-go-common/rest/indicator_management/impl"
	impl5 "github.com/kweaver-ai/idrm-go-common/rest/standardization/impl"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/trace"
)

// Injectors from wire.go:

func InitApp(conf2 *conf.Bootstrap) (*app.AppRunner, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := middleware.NewHydra(conf2, client)
	drivenUserMgnt := middleware.NewUserMgnt(conf2, client)
	driven := middleware.NewConfigurationCenterDriven(conf2, client)
	logger, cleanup, err := initialization.InitAuditLog(conf2)
	if err != nil {
		return nil, nil, err
	}
	authorizationDriven := impl.NewDriven(client)
	authServiceInternalV1Interface, err := v1.NewInternalForBase(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	middlewareMiddleware := v1_2.NewMiddleware(hydra, drivenUserMgnt, driven, logger, authorizationDriven, authServiceInternalV1Interface)
	gormDB, cleanup2, err := db.NewDB(conf2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	subjectDomainRepo := impl2.NewSubjectDomainRepo(gormDB)
	userRepo := impl3.NewUserRepo(gormDB)
	standardInfoRepo := impl4.NewStandardInfoRepo(gormDB)
	standardizationDriven := impl5.NewDriven(client)
	repo := impl6.NewRepoImpl(gormDB)
	data_viewDriven := impl7.NewDataViewDriven(client)
	data_application_serviceDriven := impl8.NewDrivenImpl(client)
	indicator_managementDriven := impl9.NewDrivenImpl(client)
	excelProcessUsecase := excel_process.NewExcelProcessUsecase()
	graphSearch := impl10.NewSailorServiceCall(client, conf2)
	classifyRepo := impl11.NewRepoImpl(gormDB)
	af_sailorDriven := impl12.NewSailorDriven(client)
	subjectDomainUsecase := subject_domain.NewSubjectDomainUseCase(subjectDomainRepo, drivenUserMgnt, userRepo, standardInfoRepo, standardizationDriven, repo, driven, data_viewDriven, data_application_serviceDriven, indicator_managementDriven, excelProcessUsecase, graphSearch, classifyRepo, af_sailorDriven)
	subjectDomainService := v1_3.NewBusinessDomainService(subjectDomainUsecase)
	iRouter := driver.NewRouter(middlewareMiddleware, subjectDomainService, logger, driven)
	server := driver.NewHttpEngine(conf2, iRouter)
	idrm_go_frameApp := app.NewApp(conf2, server)
	syncProducer, err := kafka.NewSyncProducer(conf2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	entityChangeTransport := callbacks.NewEntityChangeTransport(syncProducer)
	transports := callbacks.NewTransport(gormDB, entityChangeTransport)
	appRunner := app.NewAppRunner(idrm_go_frameApp, transports)
	return appRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}
