// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	impl25 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/business_grooming/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/callback"
	impl5 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/configuration_center/impl"
	impl9 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/data_catalog/impl"
	impl31 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/data_exploration/impl"
	impl16 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/data_view/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/alarm_rule"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/configuration"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_aggregation_inventory"
	impl22 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_aggregation_plan/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_aggregation_resource"
	impl21 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_comprehension_plan/impl"
	impl47 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_processing_overview/impl"
	impl23 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_processing_plan/impl"
	impl24 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_quality_improvement/impl"
	impl26 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/data_research_report/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/database"
	impl44 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/db_sandbox/impl"
	impl28 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/fusion_model/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/notification"
	impl8 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/operation_log/impl"
	impl40 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/points_management/impl"
	impl33 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/quality_audit_model/impl"
	impl7 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/task_relation_data/impl"
	impl3 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/tc_flow_info/impl"
	impl15 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/tc_member/impl"
	impl14 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/tc_oss/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/tc_project/impl"
	impl2 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/tc_task/impl"
	impl37 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/tenant_application/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/user/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/user_single"
	impl11 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order_alarm"
	impl29 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order_extend/impl"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order_manage"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order_single"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order_task"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/gorm/work_order_template"
	kafka2 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/mq/kafka"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driven/workflow"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver"
	v1_18 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_aggregation_inventory/v1"
	v1_9 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_aggregation_plan/v1"
	v1_8 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_comprehension_plan/v1"
	v1_23 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_processing_overview/v1"
	v1_12 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_processing_plan/v1"
	v1_19 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_quality/v1"
	v1_10 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/data_research_report/v1"
	v1_20 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/db_sandbox/v1"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/middleware"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/mq"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/mq/data_catalog"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/mq/domain"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/mq/points"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/mq/role"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/mq/user_mgm"
	notification3 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/notification/v1"
	v1_5 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/operation_log/v1"
	v1_13 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/points_management/v1"
	v1_6 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/relation_data/v1"
	v1_3 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/tc_oss/v1"
	"github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/tc_project/v1"
	v1_2 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/tc_task/v1"
	v1_11 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/tenant_application/v1"
	v1_4 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/user/v1"
	v1_16 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/work_order/v1"
	v1_22 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/work_order_manage/v1"
	v1_17 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/work_order_task/v1"
	v1_21 "github.com/kweaver-ai/dsg/services/apps/task_center/adapter/driver/work_order_template/v1"
	"github.com/kweaver-ai/dsg/services/apps/task_center/controller"
	data_aggregation_inventory2 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_aggregation_inventory"
	impl36 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_aggregation_plan/impl"
	impl35 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_comprehension_plan/impl"
	impl48 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_processing_overview/impl"
	impl39 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_processing_plan/impl"
	impl43 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_quality/impl"
	impl27 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/data_research_report/impl"
	impl46 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/db_sandbox/impl"
	notification2 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/notification"
	impl19 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/operation_log/impl"
	impl41 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/points_management/impl"
	impl20 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/relation_data/impl"
	impl18 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/tc_oss/impl"
	impl17 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/tc_project/impl"
	impl13 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/tc_task/impl"
	impl38 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/tenant_application/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/user/impl"
	impl34 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/work_order/impl"
	work_order_alarm2 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/work_order_alarm"
	work_order_manage2 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/work_order_manage"
	work_order_task2 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/work_order_task"
	work_order_template2 "github.com/kweaver-ai/dsg/services/apps/task_center/domain/work_order_template"
	"github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/conf"
	"github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/mq/kafka"
	"github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/mq/mq_client"
	"github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/repository/db"
	"github.com/kweaver-ai/idrm-go-common/go-ceph-client"
	v1_15 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	v1_14 "github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl42 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl10 "github.com/kweaver-ai/idrm-go-common/rest/data_catalog/impl"
	impl30 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	impl32 "github.com/kweaver-ai/idrm-go-common/rest/demand_management/impl"
	v1_7 "github.com/kweaver-ai/idrm-go-common/rest/doc_audit_rest/v1"
	impl12 "github.com/kweaver-ai/idrm-go-common/rest/standardization/impl"
	impl45 "github.com/kweaver-ai/idrm-go-common/rest/workflow/impl"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/trace"
)

// Injectors from wire.go:

func InitApp(server *conf.Server, dbDatabase *db.Database) (*AppRunner, func(), error) {
	producer, err := kafka.NewSyncProducer()
	if err != nil {
		return nil, nil, err
	}
	data, cleanup, err := db.NewData(dbDatabase)
	if err != nil {
		return nil, nil, err
	}
	repo := impl.NewProjectRepo(data)
	tc_taskRepo := impl2.NewTaskRepo(data, repo)
	tc_flow_infoRepo := impl3.NewFlowInfoRepo(data)
	iUserRepo := impl4.NewUserRepo(data)
	client := trace.NewOtelHttpClient()
	drivenUserMgnt := middleware.NewUserMgnt(client)
	call := impl5.NewConfigurationCenterCall(client)
	iUser := impl6.NewUser(iUserRepo, drivenUserMgnt, call)
	task_relations_dataRepo := impl7.NewRepo(data)
	operation_logRepo := impl8.NewOperationLogRepo(data)
	data_catalogCall := impl9.NewCatalogServiceCall(client)
	driven := impl10.NewDrivenImpl(client)
	work_orderRepo := impl11.NewWorkOderRepo(data)
	standardizationDriven := impl12.NewDriven(client)
	configuration_centerDriven := middleware.NewConfigurationCenterDriven(client)
	userCase := impl13.NewTaskUserCase(producer, tc_taskRepo, tc_flow_infoRepo, iUser, task_relations_dataRepo, iUserRepo, operation_logRepo, data_catalogCall, driven, work_orderRepo, standardizationDriven, repo, configuration_centerDriven)
	tc_ossRepo := impl14.NewOssRepo(data)
	tc_memberRepo := impl15.NewMemberRepo(data)
	dataView := impl16.NewDataView(client)
	tc_projectUserCase := impl17.NewProjectUserCase(producer, repo, tc_taskRepo, userCase, tc_ossRepo, tc_memberRepo, tc_flow_infoRepo, iUser, operation_logRepo, task_relations_dataRepo, call, dataView)
	projectService := v1.NewProjectService(tc_projectUserCase)
	taskService := v1_2.NewTaskService(userCase)
	cephClient, err := gocephclient.NewCephClient(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tc_ossUserCase := impl18.NewOssUserCase(cephClient, tc_ossRepo)
	ossService := v1_3.NewOssService(tc_ossUserCase)
	userService := v1_4.NewUserService(iUser)
	operation_logUserCase := impl19.NewOperationLogUserCase(operation_logRepo, iUser)
	service := v1_5.NewService(operation_logUserCase)
	relation_dataUserCase := impl20.NewUseCase(task_relations_dataRepo, tc_taskRepo)
	relationDataService := v1_6.NewRelationDataService(relation_dataUserCase)
	dataComprehensionPlanRepo := impl21.NewComprehensionPlanRepo(data)
	workflowInterface, err := workflow.NewWorkflow(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	workflowWorkflowInterface := workflow.NewWorkflowRest(client)
	dataAggregatioPlanRepo := impl22.NewAggregationPlanRepo(data)
	repository := data_aggregation_inventory.New(data)
	data_aggregation_resourceInterface := data_aggregation_resource.New(data)
	dataProcessingPlanRepo := impl23.NewProcessinPlanRepo(data)
	data_quality_improvementRepo := impl24.NewDataQualityImprovementRepo(data)
	databaseClient, err := database.NewForData(data)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	docAuditRestV1Interface, err := v1_7.NewForHTTPClient(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	business_groomingCall := impl25.NewBusinessGroomingCall(client)
	data_aggregation_inventoryDomain := data_aggregation_inventory2.New(databaseClient, repository, iUserRepo, docAuditRestV1Interface, work_orderRepo, business_groomingCall, configuration_centerDriven, workflowInterface)
	dataResearchReportRepo := impl26.NewDataResearchReportRepo(data)
	dataResearchReport := impl27.NewDataResearchReport(dataResearchReportRepo, configuration_centerDriven, workflowInterface, workflowWorkflowInterface)
	fusionModelRepo := impl28.NewFusionModelRepo(data)
	workOrderExtendRepo := impl29.NewWorkOrderExtendRepo(data)
	data_viewDriven := impl30.NewDataViewDriven(client)
	dataExploration := impl31.NewDataExploration(client)
	demand_managementDriven := impl32.NewDemandManagementDriven(client)
	work_order_taskRepository := work_order_task.New(data)
	qualityAuditModelRepo := impl33.NewRepo(data)
	callbackInterface, cleanup2, err := callback.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	protonMQClient, err := mq_client.NewProtonMQClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configurationRepo := configuration.NewRepo(data)
	workOrderUseCase := impl34.NewWorkOrderUseCase(work_orderRepo, iUser, workflowInterface, workflowWorkflowInterface, configuration_centerDriven, dataComprehensionPlanRepo, dataAggregatioPlanRepo, repository, data_aggregation_resourceInterface, dataProcessingPlanRepo, data_catalogCall, call, tc_taskRepo, repo, tc_flow_infoRepo, data_quality_improvementRepo, producer, drivenUserMgnt, data_aggregation_inventoryDomain, dataResearchReport, databaseClient, fusionModelRepo, workOrderExtendRepo, data_viewDriven, dataExploration, standardizationDriven, driven, demand_managementDriven, work_order_taskRepository, qualityAuditModelRepo, callbackInterface, protonMQClient, configurationRepo, dataView)
	workOrderInterface := impl34.NewWorkOrderInterface(workOrderUseCase)
	dataComprehensionPlan := impl35.NewDataComprehensionPlan(dataComprehensionPlanRepo, iUser, configuration_centerDriven, workflowInterface, workflowWorkflowInterface, workOrderInterface)
	comprehensionPlanService := v1_8.NewUserService(dataComprehensionPlan)
	dataAggregationPlan := impl36.NewDataComprehensionPlan(dataAggregatioPlanRepo, iUser, workflowInterface, workflowWorkflowInterface, configuration_centerDriven)
	aggregationPlanService := v1_9.NewUserService(dataAggregationPlan)
	dataResearchReportService := v1_10.NewUserService(dataResearchReport)
	tenantApplicationRepo := impl37.NewTenantApplicationRepo(data)
	tenantApplication := impl38.NewTenantApplication(tenantApplicationRepo, configuration_centerDriven, call, iUser, workflowInterface, workflowWorkflowInterface, driven, data)
	tenantApplicationService := v1_11.NewUserService(tenantApplication)
	dataProcessingPlan := impl39.NewDataComprehensionPlan(dataProcessingPlanRepo, iUser, workflowInterface, workflowWorkflowInterface, configuration_centerDriven)
	processingPlanService := v1_12.NewUserService(dataProcessingPlan)
	pointsRuleConfigRepo := impl40.NewPointsRuleConfigRepo(data)
	pointsEventRepo := impl40.NewPointsEventImplRepo(data)
	pointsManagement := impl41.NewPointsManagement(pointsRuleConfigRepo, pointsEventRepo, configuration_centerDriven)
	pointsManagementService := v1_13.NewPointsManagementService(pointsManagement)
	hydra := middleware.NewHydra(client)
	logger := driver.NewAuditLogger()
	authorizationDriven := impl42.NewDriven(client)
	authServiceInternalV1Interface, err := v1_14.NewInternalForBase(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	middlewareMiddleware := v1_15.NewMiddleware(hydra, drivenUserMgnt, configuration_centerDriven, logger, authorizationDriven, authServiceInternalV1Interface)
	workOrderService := v1_16.NewUserService(workOrderUseCase)
	saramaClient, err := kafka2.NewSaramaClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	work_order_taskDomain, err := work_order_task2.New(work_order_taskRepository, databaseClient, work_orderRepo, saramaClient, tc_taskRepo, data_viewDriven, configuration_centerDriven, driven)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v1Service := v1_17.New(work_order_taskDomain)
	service2 := v1_18.New(data_aggregation_inventoryDomain)
	dataQualityUseCase := impl43.NewDataQualityUseCase(work_orderRepo, data_quality_improvementRepo, dataExploration, dataView, data_viewDriven, producer, configuration_centerDriven)
	dataQualityService := v1_19.NewUserService(dataQualityUseCase)
	db_sandboxRepo := impl44.NewRepo(data)
	workflowDriven := impl45.NewWorkflowDriven(client)
	useCase := impl46.NewUseCase(db_sandboxRepo, configuration_centerDriven, workflowInterface, workflowDriven, repo, tc_memberRepo, driven)
	service3 := v1_20.NewService(useCase)
	work_order_templateRepository := work_order_template.New(data)
	work_order_templateDomain := work_order_template2.New(work_order_templateRepository, iUserRepo)
	service4 := v1_21.New(work_order_templateDomain)
	work_order_manageRepository := work_order_manage.New(data)
	work_order_manageDomain := work_order_manage2.New(work_order_manageRepository, iUserRepo)
	service5 := v1_22.New(work_order_manageDomain)
	dataProcessingOverviewRepo := impl47.NewProcessinOverviewRepo(data)
	dataProcessingOverview := impl48.NewDataProcessingOverview(dataProcessingOverviewRepo, iUser, workflowInterface, workflowWorkflowInterface, configuration_centerDriven)
	processingOverviewService := v1_23.NewUserService(dataProcessingOverview)
	notificationInterface := notification.New(data)
	work_order_singleInterface := work_order_single.New(data)
	interface2 := notification2.New(notificationInterface, work_order_singleInterface)
	notificationService := notification3.New(interface2)
	router := &driver.Router{
		ProjectApi:                   projectService,
		TaskApi:                      taskService,
		OssApi:                       ossService,
		UserApi:                      userService,
		OpLogApi:                     service,
		RelationDataApi:              relationDataService,
		ComprehensionPlanServiceApi:  comprehensionPlanService,
		AggregationPlanServiceApi:    aggregationPlanService,
		DataResearchReportServiceApi: dataResearchReportService,
		TenantApplicationServiceApi:  tenantApplicationService,
		ProcessingPlanServiceApi:     processingPlanService,
		PointsManagementServiceApi:   pointsManagementService,
		Middleware:                   middlewareMiddleware,
		WorkOrderServiceApi:          workOrderService,
		WorkOrderTask:                v1Service,
		DataAggregationInventoryApi:  service2,
		DataQualityServiceApi:        dataQualityService,
		DBSandboxApi:                 service3,
		WorkOrderTemplateApi:         service4,
		WorkOrderManageApi:           service5,
		ProcessingOverview:           processingOverviewService,
		NotificationApi:              notificationService,
	}
	consumer := kafka.NewConsumer()
	roleHandler := role.NewRoleHandler(tc_projectUserCase, userCase)
	userMgmHandler := user_mgm.NewUserMgmHandler(iUser)
	businessDomainHandler := domain.NewBusinessDomainHandler(tc_projectUserCase, userCase)
	pointsEventHandler := points.NewPointsEventHandler(pointsManagement)
	dataCatalogHandler := data_catalog.NewDataCatalogHandler(useCase)
	alarm_ruleInterface := alarm_rule.New(data)
	work_order_alarmInterface := work_order_alarm.New(data)
	interface3 := work_order_alarm2.New(alarm_ruleInterface, work_order_alarmInterface)
	mqConsumerService := mq.NewMQConsumerService(consumer, roleHandler, userMgmHandler, businessDomainHandler, pointsEventHandler, dataCatalogHandler, interface3)
	v := driver.NewHttpServer(server, router, mqConsumerService)
	user_singleInterface := user_single.New(data)
	workOrderAlarmController := controller.NewWorkOrderAlarm(alarm_ruleInterface, notificationInterface, work_order_singleInterface, work_order_alarmInterface, user_singleInterface, callbackInterface)
	app := newApp(v, workOrderAlarmController)
	commonService := driver.NewCommonService(iUser, business_groomingCall, call, data_catalogCall)
	wfStarter := workflow.NewWFStarter(workflowInterface, client)
	appRunner := &AppRunner{
		App:    app,
		Common: commonService,
		wfs:    wfStarter,
	}
	return appRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var appRunnerSet = wire.NewSet(wire.Struct(new(AppRunner), "*"))
