// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	impl5 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/adp_agent_factory/impl"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/af_sailor_agent"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/auth_service"
	impl3 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/basic_search/impl"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/configuration_center"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/copilot_helper"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/data_catalog"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/data_subject"
	impl4 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/es_subject_model/impl"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/gorm/assistant"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/gorm/knowledge_datasource"
	knowledge_network2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/gorm/knowledge_network"
	v6 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/hydra/v6"
	knowledge_build2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/knowledge_build"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/knowledge_network"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/large_language_model"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/opensearch"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/self"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/user_management"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driven/virtualization_engine"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver"
	alg_server2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/alg_server"
	v1_2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/comprehension/v1"
	copilot2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/copilot"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/data_change_mq"
	knowledge_build3 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/knowledge_build"
	large_language_model2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/large_language_model"
	recommend2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/recommend"
	v1_3 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/adapter/driver/understanding/v1"
	v1 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/common/middleware/v1"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/common/settings"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/alg_server"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/comprehension/impl"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/comprehension/impl/tools"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/copilot"
	impl2 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/intelligence/impl"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/knowledge_build"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/mq"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/recommend"
	impl6 "github.com/kweaver-ai/dip-for-data-resource/sailor-service/domain/understanding/impl"
	"github.com/kweaver-ai/dip-for-data-resource/sailor-service/infrastructure/repository/db"
	af_go_frame "github.com/kweaver-ai/idrm-go-frame"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/trace"
	"github.com/kweaver-ai/idrm-go-frame/core/utils/httpclient"
)

// Injectors from wire.go:

func InitApp(httpCfg settings.HttpConf) (*af_go_frame.App, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := v6.NewHydra(client)
	httpClient := httpclient.NewMiddlewareHTTPClient(client)
	drivenUserMgnt := user_management.NewUserMgnt(httpClient)
	middleware := v1.NewMiddleware(hydra, drivenUserMgnt)
	ad := knowledge_network.NewAD(client)
	data, cleanup, err := db.NewData()
	if err != nil {
		return nil, nil, err
	}
	repo := knowledge_network2.NewRepo(data)
	helper := knowledge_build.NewHelper(repo)
	anyDataSearch := tools.NewAnyDataSearch(ad, helper)
	openAI := large_language_model.NewOpenAI(client)
	openAPISource := tools.NewOpenAPISource(openAI)
	virtualizationEngine := virtualization_engine.NewVirtualizationEngine(client)
	engineSource := tools.NewEngineSource(virtualizationEngine)
	brain := impl.NewBrain(anyDataSearch, openAPISource, engineSource)
	domain := impl.NewComprehensionDomain(brain, data)
	controller := v1_2.NewController(domain)
	useCase := recommend.NewUseCase(ad, helper, data)
	service := recommend2.NewService(useCase)
	drivenConfigurationCenter := configuration_center.NewConfigurationCenter(httpClient, client)
	alg_serverUseCase := alg_server.NewUseCase(ad, helper, drivenConfigurationCenter)
	alg_serverService := alg_server2.NewService(alg_serverUseCase)
	intelligenceUseCase := impl2.NewUseCase(openAI)
	large_language_modelService := large_language_model2.NewService(intelligenceUseCase)
	mutex := knowledge_build2.NewMutex(data)
	proxy := self.NewProxy(client)
	server := knowledge_build.NewServer(mutex, ad, repo, proxy, drivenConfigurationCenter)
	knowledge_buildService := knowledge_build3.NewService(server)
	copilot_helperAD := copilot_helper.NewAD(client)
	afSailorAgent := af_sailor_agent.NewAFSailorAgent(client)
	assistantRepo := assistant.NewRepo(data)
	authService := auth_service.NewAuthService(client)
	dataCatalog := data_catalog.NewDataCatalog(client)
	driven := data_subject.NewDriven(client)
	basic_searchRepo := impl3.NewRepo(httpClient, client)
	knowledge_datasourceRepo := knowledge_datasource.NewRepo(data)
	config := settings.GetConfig()
	searchClient, err := opensearch.NewOpenSearchClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	esSubjectModel, err := impl4.NewObjSearch(searchClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	adp_agent_factoryRepo := impl5.NewRepo(httpClient, client)
	copilotUseCase := copilot.NewUseCase(copilot_helperAD, afSailorAgent, helper, data, assistantRepo, authService, drivenConfigurationCenter, dataCatalog, driven, basic_searchRepo, knowledge_datasourceRepo, esSubjectModel, adp_agent_factoryRepo)
	copilotService := copilot2.NewService(copilotUseCase)
	understandingUseCase := impl6.NewUseCase(copilot_helperAD)
	v1Controller := v1_3.NewController(understandingUseCase)
	router := &driver.Router{
		Middleware:                  middleware,
		DataComprehensionController: controller,
		RecommendSrv:                service,
		KgSrv:                       alg_serverService,
		LLM:                         large_language_modelService,
		KNBuildSrv:                  knowledge_buildService,
		CopilotSrv:                  copilotService,
		DataUnderstandingController: v1Controller,
	}
	restServer := driver.NewHttpServer(router, httpCfg)
	consumer := data_change_mq.NewConsumer(ad, helper, knowledge_datasourceRepo, drivenConfigurationCenter, esSubjectModel)
	mqConsumerService := mq.NewMQConsumeService(consumer)
	v := toTransportServer(restServer, server, mqConsumerService)
	app := newApp(v)
	return app, func() {
		cleanup()
	}, nil
}
