// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/audit"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client/anyshare"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client/authentication"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client/deploy_manager"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client/hydra/v6"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client/oauth2"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/http_client/user_management"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driven/kafka"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driver/gin"
	"github.com/kweaver-ai/dsg/services/apps/session/adapter/driver/gin/login/v1"
	v1_2 "github.com/kweaver-ai/dsg/services/apps/session/adapter/driver/gin/logout/v1"
	v1_3 "github.com/kweaver-ai/dsg/services/apps/session/adapter/driver/gin/refresh_token/v1"
	v1_4 "github.com/kweaver-ai/dsg/services/apps/session/adapter/driver/gin/user_info/v1"
	"github.com/kweaver-ai/dsg/services/apps/session/common/settings"
	"github.com/kweaver-ai/dsg/services/apps/session/domain/d_session/impl"
	impl3 "github.com/kweaver-ai/dsg/services/apps/session/domain/login/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/session/domain/logout/impl"
	impl5 "github.com/kweaver-ai/dsg/services/apps/session/domain/refresh_token/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/session/domain/user_info/impl"
	impl2 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	"github.com/kweaver-ai/idrm-go-frame"
)

// Injectors from wire.go:

func InitApp(configContains *settings.ConfigContains) (*idrm_go_frame.App, func(), error) {
	httpClient := http_client.NewOtelHTTPClient()
	drivenOauth2 := oauth2.NewOauth2(httpClient)
	drivenUserMgnt := user_management.NewUserMgnt(httpClient)
	session := impl.NewSession()
	drivenDeployMgm := deploy_management.NewDeployMgm(httpClient)
	client := driven.NewClient()
	hydra := v6.NewHydra(client)
	drivenAnyshare := anyshare.NewAnyshare(client)
	authenticationDriven := authentication.NewAuthentication(client)
	configuration_centerDriven := impl2.NewConfigurationCenterDrivenByService(client)
	syncProducer, err := kafka.NewSaramaSyncProducer(configContains)
	if err != nil {
		return nil, nil, err
	}
	logger := audit.NewAuditLogger(configuration_centerDriven, syncProducer)
	loginService := impl3.NewLoginUsecase(drivenOauth2, drivenUserMgnt, session, drivenDeployMgm, hydra, drivenAnyshare, authenticationDriven, logger)
	login := v1.NewLogin(loginService, session, drivenDeployMgm)
	logOutService := impl4.NewLogOutUsecase(drivenOauth2, drivenUserMgnt, session, configuration_centerDriven, logger)
	logOut := v1_2.NewLogOut(logOutService, drivenDeployMgm)
	refreshService := impl5.NewRefreshUsecase(drivenOauth2, session)
	refreshToken := v1_3.NewRefreshToken(refreshService)
	userInfoService := impl6.NewUserInfoUsecase(hydra, drivenUserMgnt, session)
	userInfo := v1_4.NewUserInfo(userInfoService, session)
	router := &gin.Router{
		Login:        login,
		Logout:       logOut,
		RefreshToken: refreshToken,
		UserInfo:     userInfo,
	}
	server := gin.NewHttpServer(configContains, router)
	app := newApp(server)
	return app, func() {
	}, nil
}
