// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package sharemgnt

import (
	"bytes"
	"context"
	"fmt"
	"reflect"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/thrift_gen/eacplog"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/thrift_gen/ethriftexception"
	"github.com/kweaver-ai/idrm-go-common/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = ethriftexception.GoUnusedProtection__
var _ = eacplog.GoUnusedProtection__

const NCT_SHAREMGNT_PORT = 9600
const NCT_USER_ADMIN = "266c6a42-6131-4d62-8f39-853e7093701c"
const NCT_USER_AUDIT = "94752844-BDD0-4B9E-8927-1CA8D427E699"
const NCT_USER_SYSTEM = "234562BE-88FF-4440-9BFF-447F139871A2"
const NCT_USER_SECURIT = "4bb41612-a040-11e6-887d-005056920bea"
const NCT_SYSTEM_ROLE_SUPPER = "7dcfcc9c-ad02-11e8-aa06-000c29358ad6"
const NCT_SYSTEM_ROLE_ADMIN = "d2bd2082-ad03-11e8-aa06-000c29358ad6"
const NCT_SYSTEM_ROLE_SECURIT = "d8998f72-ad03-11e8-aa06-000c29358ad6"
const NCT_SYSTEM_ROLE_AUDIT = "def246f2-ad03-11e8-aa06-000c29358ad6"
const NCT_SYSTEM_ROLE_ORG_MANAGER = "e63e1c88-ad03-11e8-aa06-000c29358ad6"
const NCT_SYSTEM_ROLE_ORG_AUDIT = "f06ac18e-ad03-11e8-aa06-000c29358ad6"
const NCT_DEFAULT_ORGANIZATION = "151bcb65-48ce-4b62-973f-0bb6685f9cb8"
const NCT_UNDISTRIBUTE_USER_GROUP = "-1"
const NCT_ALL_USER_GROUP = "-2"
const NCT_DIRECT_DEPARTMENT = "-3"
const NCT_DIRECT_ORGANIZATION = "-4"
const NCT_MIN_CSF_LEVEL = 5

func init() {
}
