// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/data-exploration-service/common/util"
	"gorm.io/gorm"
)

const TableNameClientInfo = "t_client_info"

// ClientInfo mapped from table <t_client_info>
type ClientInfo struct {
	ID           uint64 `gorm:"column:id;comment:唯一id，雪花算法" json:"id"`                            // 唯一id，雪花算法
	ClientID     string `gorm:"column:client_id;not null;comment:客户端id" json:"client_id"`         // 客户端id
	ClientSecret string `gorm:"column:client_secret;not null;comment:客户端密钥" json:"client_secret"` // 客户端密钥
}

func (m *ClientInfo) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID > 0 {
		return nil
	}

	id, err := util.NewModelID()
	if err != nil {
		return err
	}

	m.ID = id

	return nil
}

// TableName ClientInfo's table name
func (*ClientInfo) TableName() string {
	return TableNameClientInfo
}
