// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-exploration-service/common/errorcode"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameReport = "t_report"

// Report mapped from table <t_report>
type Report struct {
	ID                   uint64     `gorm:"column:f_id;comment:主键id" json:"id"`                                          // 主键id
	Code                 *string    `gorm:"column:f_code;comment:探查报告编号" json:"code"`                                    // 探查报告编号
	TaskID               uint64     `gorm:"column:f_task_id;not null;comment:任务配置记录id" json:"task_id"`                   // 任务配置记录id
	TaskVersion          *int32     `gorm:"column:f_task_version;comment:任务配置版本" json:"task_version"`                    // 任务配置版本
	QueryParams          *string    `gorm:"column:f_query_params;comment:探查任务请求参数，json格式字符串" json:"query_params"`        // 探查任务请求参数，json格式字符串
	ExploreType          *int32     `gorm:"column:f_explore_type;comment:探查类型" json:"explore_type"`                      // 探查类型
	Table                *string    `gorm:"column:f_table;comment:表名" json:"table"`                                      // 表名
	TableID              *string    `gorm:"column:f_table_id;comment:表id" json:"table_id"`                               // 表id
	Schema               *string    `gorm:"column:f_schema;comment:库名" json:"schema"`                                    // 库名
	VeCatalog            *string    `gorm:"column:f_ve_catalog;comment:虚拟化引擎数据源编目" json:"ve_catalog"`                    // 虚拟化引擎数据源编目
	TotalSample          *int32     `gorm:"column:f_total_sample;comment:探查样本数量" json:"total_sample"`                    // 探查样本数量
	TotalNum             *int32     `gorm:"column:f_total_num;comment:探查表总行数" json:"total_num"`                          // 探查表总行数
	TotalScore           *float64   `gorm:"column:f_total_score;comment:探查分数" json:"total_score"`                        // 探查分数
	Result               *string    `gorm:"column:f_result;comment:探查结果" json:"result"`                                  // 探查结果
	Status               *int32     `gorm:"column:f_status;comment:报告状态" json:"status"`                                  // 报告状态
	Latest               int32      `gorm:"column:f_latest;not null;comment:最近一次探查结果" json:"latest"`                     // 最近一次探查结果
	CreatedAt            *time.Time `gorm:"column:f_created_at;comment:创建时间" json:"created_at"`                          // 创建时间
	CreatedByUID         *string    `gorm:"column:f_created_by_uid;comment:创建人" json:"created_by_uid"`                   // 创建人
	CreatedByUname       *string    `gorm:"column:f_created_by_uname;comment:创建人中文名" json:"created_by_uname"`            // 创建人中文名
	FinishedAt           *time.Time `gorm:"column:f_finished_at;comment:完成时间" json:"finished_at"`                        // 完成时间
	Reason               *string    `gorm:"column:f_reason;comment:探查异常说明" json:"reason"`                                // 探查异常说明
	DvTaskID             *string    `gorm:"column:f_dv_task_id;comment:data-view任务id" json:"dv_task_id"`                 // data-view任务id
	TotalCompleteness    *float64   `gorm:"column:f_total_completeness;comment:完整性总分" json:"f_total_completeness"`       // 完整性总分
	TotalStandardization *float64   `gorm:"column:f_total_standardization;comment:规范性总分" json:"f_total_standardization"` // 规范性总分
	TotalUniqueness      *float64   `gorm:"column:f_total_uniqueness;comment:唯一性总分" json:"f_total_uniqueness"`           // 唯一性总分
	TotalAccuracy        *float64   `gorm:"column:f_total_accuracy;comment:准确性总分" json:"f_total_accuracy"`               // 准确性总分
	TotalConsistency     *float64   `gorm:"column:f_total_consistency;comment:一致性总分" json:"f_total_consistency"`         // 一致性总分
	DeletedAt            *time.Time `gorm:"column:f_deleted_at;comment:删除时间" json:"deleted_at"`                          // 删除时间
}

func (m *Report) UniqueKey() string {
	return "f_code"
}

func (m *Report) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	var err error
	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
		if err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return errorcode.Desc(errorcode.PublicUniqueIDError)
		}
	}

	return nil
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
