// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-exploration-service/common/util"
	"gorm.io/gorm"
)

const TableNameReportItem = "t_report_item"

// ReportItem mapped from table <t_report_item>
type ReportItem struct {
	ID            uint64     `gorm:"column:f_id;comment:主键id" json:"id"`                           // 主键id
	Code          *string    `gorm:"column:f_code;comment:探查报告编号" json:"code"`                     // 探查报告编号
	Column        *string    `gorm:"column:f_column;comment:探查字段" json:"column"`                   // 探查字段
	RuleId        *string    `gorm:"column:f_rule_id;comment:探查规则id" json:"rule_id"`               // 探查规则id
	Project       *string    `gorm:"column:f_project;comment:探查项目" json:"project"`                 // 探查项目
	Params        *string    `gorm:"column:f_params;comment:探查参数" json:"params"`                   // 探查参数
	Result        *string    `gorm:"column:f_result;comment:探查结果" json:"result"`                   // 探查结果
	Status        *int32     `gorm:"column:f_status;comment:探查状态" json:"status"`                   // 探查状态
	CreatedAt     *time.Time `gorm:"column:f_created_at;comment:创建时间" json:"created_at"`           // 创建时间
	StartedAt     *time.Time `gorm:"column:f_started_at;comment:开始时间" json:"started_at"`           // 开始时间
	FinishedAt    *time.Time `gorm:"column:f_finished_at;comment:完成时间" json:"finished_at"`         // 完成时间
	Sql           *string    `gorm:"column:f_sql;comment:探查sql" json:"sql"`                        // 探查sql
	DimensionType *string    `gorm:"column:f_dimension_type;comment:维度类型" json:"f_dimension_type"` // 维度类型
}

func (m *ReportItem) UniqueKey() string {
	return "f_id"
}

func (m *ReportItem) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID > 0 {
		return nil
	}

	id, err := util.NewModelID()
	if err != nil {
		return err
	}

	m.ID = id

	return nil
}

// TableName ReportItem's table name
func (*ReportItem) TableName() string {
	return TableNameReportItem
}
