// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/data-exploration-service/common/errorcode"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameTaskConfig = "t_task_config"

// TaskConfig mapped from table <t_task_config>
type TaskConfig struct {
	ID             uint64     `gorm:"column:f_id;comment:主键id" json:"id"`                                   // 主键id
	TaskID         uint64     `gorm:"column:f_task_id;not null;comment:任务配置记录id" json:"task_id"`            // 任务配置记录id
	TaskName       *string    `gorm:"column:f_task_name;comment:任务配置名称" json:"task_name"`                   // 任务配置名称
	TaskDesc       *string    `gorm:"column:f_task_desc;comment:任务配置描述" json:"task_desc"`                   // 任务配置描述
	Version        *int32     `gorm:"column:f_version;comment:当前版本" json:"version"`                         // 当前版本
	VersionState   *int32     `gorm:"column:f_version_state;comment:是否为现行版本" json:"version_state"`          // 是否为现行版本
	QueryParams    *string    `gorm:"column:f_query_params;comment:探查任务请求参数，json格式字符串" json:"query_params"` // 探查任务请求参数，json格式字符串
	ExploreType    *int32     `gorm:"column:f_explore_type;comment:探查类型" json:"explore_type"`               // 探查类型
	Table          *string    `gorm:"column:f_table;comment:表名" json:"table"`                               // 表名
	TableID        *string    `gorm:"column:f_table_id;comment:表id" json:"table_id"`                        // 表id
	Schema         *string    `gorm:"column:f_schema;comment:库名" json:"schema"`                             // 库名
	VeCatalog      *string    `gorm:"column:f_ve_catalog;comment:虚拟化引擎数据源编目" json:"ve_catalog"`             // 虚拟化引擎数据源编目
	TotalSample    *int32     `gorm:"column:f_total_sample;comment:探查样本数量" json:"total_sample"`             // 探查样本数量
	ExecStatus     *int32     `gorm:"column:f_exec_status;comment:最近一次探查结果状态" json:"exec_status"`           // 最近一次探查结果状态
	ExecAt         *time.Time `gorm:"column:f_exec_at;comment:最近一次探查时间" json:"exec_at"`                     // 最近一次探查时间
	Enabled        *int32     `gorm:"column:f_enabled;comment:探查任务启用禁用状态" json:"enabled"`                   // 探查任务启用禁用状态
	CreatedAt      *time.Time `gorm:"column:f_created_at;comment:创建时间" json:"created_at"`                   // 创建时间
	CreatedByUID   *string    `gorm:"column:f_created_by_uid;comment:创建人" json:"created_by_uid"`            // 创建人
	CreatedByUname *string    `gorm:"column:f_created_by_uname;comment:创建人中文名" json:"created_by_uname"`     // 创建人中文名
	UpdatedAt      *time.Time `gorm:"column:f_updated_at;autoUpdateTime;comment:更新时间" json:"updated_at"`    // 更新时间
	UpdatedByUID   *string    `gorm:"column:f_updated_by_uid;comment:修改人" json:"updated_by_uid"`            // 修改人
	UpdatedByUname *string    `gorm:"column:f_updated_by_uname;comment:修改人中文名" json:"updated_by_uname"`     // 修改人中文名
	DeletedAt      *time.Time `gorm:"column:f_deleted_at;comment:删除时间" json:"deleted_at"`                   // 删除时间
	DeletedByUID   *string    `gorm:"column:f_deleted_by_uid;comment:删除人" json:"deleted_by_uid"`            // 删除人
	DeletedByUname *string    `gorm:"column:f_deleted_by_uname;comment:删除人中文名" json:"deleted_by_uname"`     // 删除人中文名
	DvTaskID       *string    `gorm:"column:f_dv_task_id;comment:data-view任务id" json:"dv_task_id"`          // data-view任务id
}

func (m *TaskConfig) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	var err error
	if m.ID == 0 {
		m.ID, err = utils.GetUniqueID()
		if err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return errorcode.Desc(errorcode.PublicUniqueIDError)
		}
	}

	now := time.Now()
	if m.CreatedAt == nil || m.CreatedAt.IsZero() {
		m.CreatedAt = &now
	}
	if m.UpdatedAt == nil || m.UpdatedAt.IsZero() {
		m.UpdatedAt = &now
	}

	return nil
}
func (m *TaskConfig) BeforeUpdate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	now := time.Now()
	if m.UpdatedAt == nil || m.UpdatedAt.IsZero() {
		m.UpdatedAt = &now
	}
	return nil
}

// TableName TaskConfig's table name
func (*TaskConfig) TableName() string {
	return TableNameTaskConfig
}
