// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package evfs

import (
	"bytes"
	"context"
	"fmt"
	"reflect"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/thrift_gen/ethriftexception"
	"github.com/kweaver-ai/idrm-go-common/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = ethriftexception.GoUnusedProtection__

const NCT_EVFS_PORT = 9064
const NCT_EVFS_ERR_PROVIDER_NAME = "evfstimpl"

func init() {
}
