// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/repository/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newFlowchartVersion(db *gorm.DB, opts ...gen.DOOption) flowchartVersion {
	_flowchartVersion := flowchartVersion{}

	_flowchartVersion.flowchartVersionDo.UseDB(db, opts...)
	_flowchartVersion.flowchartVersionDo.UseModel(&model.FlowchartVersion{})

	tableName := _flowchartVersion.flowchartVersionDo.TableName()
	_flowchartVersion.ALL = field.NewAsterisk(tableName)
	_flowchartVersion.ID = field.NewString(tableName, "id")
	_flowchartVersion.Name = field.NewString(tableName, "name")
	_flowchartVersion.Version = field.NewInt32(tableName, "version")
	_flowchartVersion.EditStatus = field.NewInt32(tableName, "edit_status")
	_flowchartVersion.Image = field.NewString(tableName, "image")
	_flowchartVersion.FlowchartID = field.NewString(tableName, "flowchart_id")
	_flowchartVersion.DrawProperties = field.NewString(tableName, "draw_properties")
	_flowchartVersion.CreatedAt = field.NewTime(tableName, "created_at")
	_flowchartVersion.CreatedByUID = field.NewString(tableName, "created_by_uid")
	_flowchartVersion.UpdatedAt = field.NewTime(tableName, "updated_at")
	_flowchartVersion.UpdatedByUID = field.NewString(tableName, "updated_by_uid")
	_flowchartVersion.DeletedAt = field.NewField(tableName, "deleted_at")

	_flowchartVersion.fillFieldMap()

	return _flowchartVersion
}

type flowchartVersion struct {
	flowchartVersionDo flowchartVersionDo

	ALL            field.Asterisk
	ID             field.String // 主键，uuid
	Name           field.String // 运营流程版本名称，eg:v1
	Version        field.Int32  // 运营流程版本
	EditStatus     field.Int32  // 当前版本运营流程编辑状态，枚举：2：正常；3：编辑中
	Image          field.String // 图片文件内容，base64编码
	FlowchartID    field.String // 运营流程ID
	DrawProperties field.String // 图形属性，包含位置、形状、大小等
	CreatedAt      field.Time   // 创建时间
	CreatedByUID   field.String // 创建用户ID
	UpdatedAt      field.Time   // 更新时间
	UpdatedByUID   field.String // 更新用户ID
	DeletedAt      field.Field  // 删除时间(逻辑删除)

	fieldMap map[string]field.Expr
}

func (f flowchartVersion) Table(newTableName string) *flowchartVersion {
	f.flowchartVersionDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f flowchartVersion) As(alias string) *flowchartVersion {
	f.flowchartVersionDo.DO = *(f.flowchartVersionDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *flowchartVersion) updateTableName(table string) *flowchartVersion {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.Name = field.NewString(table, "name")
	f.Version = field.NewInt32(table, "version")
	f.EditStatus = field.NewInt32(table, "edit_status")
	f.Image = field.NewString(table, "image")
	f.FlowchartID = field.NewString(table, "flowchart_id")
	f.DrawProperties = field.NewString(table, "draw_properties")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.CreatedByUID = field.NewString(table, "created_by_uid")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.UpdatedByUID = field.NewString(table, "updated_by_uid")
	f.DeletedAt = field.NewField(table, "deleted_at")

	f.fillFieldMap()

	return f
}

func (f *flowchartVersion) WithContext(ctx context.Context) IFlowchartVersionDo {
	return f.flowchartVersionDo.WithContext(ctx)
}

func (f flowchartVersion) TableName() string { return f.flowchartVersionDo.TableName() }

func (f flowchartVersion) Alias() string { return f.flowchartVersionDo.Alias() }

func (f *flowchartVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *flowchartVersion) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 12)
	f.fieldMap["id"] = f.ID
	f.fieldMap["name"] = f.Name
	f.fieldMap["version"] = f.Version
	f.fieldMap["edit_status"] = f.EditStatus
	f.fieldMap["image"] = f.Image
	f.fieldMap["flowchart_id"] = f.FlowchartID
	f.fieldMap["draw_properties"] = f.DrawProperties
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["created_by_uid"] = f.CreatedByUID
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["updated_by_uid"] = f.UpdatedByUID
	f.fieldMap["deleted_at"] = f.DeletedAt
}

func (f flowchartVersion) clone(db *gorm.DB) flowchartVersion {
	f.flowchartVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f flowchartVersion) replaceDB(db *gorm.DB) flowchartVersion {
	f.flowchartVersionDo.ReplaceDB(db)
	return f
}

type flowchartVersionDo struct{ gen.DO }

type IFlowchartVersionDo interface {
	gen.SubQuery
	Debug() IFlowchartVersionDo
	WithContext(ctx context.Context) IFlowchartVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFlowchartVersionDo
	WriteDB() IFlowchartVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFlowchartVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFlowchartVersionDo
	Not(conds ...gen.Condition) IFlowchartVersionDo
	Or(conds ...gen.Condition) IFlowchartVersionDo
	Select(conds ...field.Expr) IFlowchartVersionDo
	Where(conds ...gen.Condition) IFlowchartVersionDo
	Order(conds ...field.Expr) IFlowchartVersionDo
	Distinct(cols ...field.Expr) IFlowchartVersionDo
	Omit(cols ...field.Expr) IFlowchartVersionDo
	Join(table schema.Tabler, on ...field.Expr) IFlowchartVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFlowchartVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFlowchartVersionDo
	Group(cols ...field.Expr) IFlowchartVersionDo
	Having(conds ...gen.Condition) IFlowchartVersionDo
	Limit(limit int) IFlowchartVersionDo
	Offset(offset int) IFlowchartVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowchartVersionDo
	Unscoped() IFlowchartVersionDo
	Create(values ...*model.FlowchartVersion) error
	CreateInBatches(values []*model.FlowchartVersion, batchSize int) error
	Save(values ...*model.FlowchartVersion) error
	First() (*model.FlowchartVersion, error)
	Take() (*model.FlowchartVersion, error)
	Last() (*model.FlowchartVersion, error)
	Find() ([]*model.FlowchartVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FlowchartVersion, err error)
	FindInBatches(result *[]*model.FlowchartVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FlowchartVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFlowchartVersionDo
	Assign(attrs ...field.AssignExpr) IFlowchartVersionDo
	Joins(fields ...field.RelationField) IFlowchartVersionDo
	Preload(fields ...field.RelationField) IFlowchartVersionDo
	FirstOrInit() (*model.FlowchartVersion, error)
	FirstOrCreate() (*model.FlowchartVersion, error)
	FindByPage(offset int, limit int) (result []*model.FlowchartVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFlowchartVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f flowchartVersionDo) Debug() IFlowchartVersionDo {
	return f.withDO(f.DO.Debug())
}

func (f flowchartVersionDo) WithContext(ctx context.Context) IFlowchartVersionDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f flowchartVersionDo) ReadDB() IFlowchartVersionDo {
	return f.Clauses(dbresolver.Read)
}

func (f flowchartVersionDo) WriteDB() IFlowchartVersionDo {
	return f.Clauses(dbresolver.Write)
}

func (f flowchartVersionDo) Session(config *gorm.Session) IFlowchartVersionDo {
	return f.withDO(f.DO.Session(config))
}

func (f flowchartVersionDo) Clauses(conds ...clause.Expression) IFlowchartVersionDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f flowchartVersionDo) Returning(value interface{}, columns ...string) IFlowchartVersionDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f flowchartVersionDo) Not(conds ...gen.Condition) IFlowchartVersionDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f flowchartVersionDo) Or(conds ...gen.Condition) IFlowchartVersionDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f flowchartVersionDo) Select(conds ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f flowchartVersionDo) Where(conds ...gen.Condition) IFlowchartVersionDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f flowchartVersionDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IFlowchartVersionDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f flowchartVersionDo) Order(conds ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f flowchartVersionDo) Distinct(cols ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f flowchartVersionDo) Omit(cols ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f flowchartVersionDo) Join(table schema.Tabler, on ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f flowchartVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f flowchartVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f flowchartVersionDo) Group(cols ...field.Expr) IFlowchartVersionDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f flowchartVersionDo) Having(conds ...gen.Condition) IFlowchartVersionDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f flowchartVersionDo) Limit(limit int) IFlowchartVersionDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f flowchartVersionDo) Offset(offset int) IFlowchartVersionDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f flowchartVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFlowchartVersionDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f flowchartVersionDo) Unscoped() IFlowchartVersionDo {
	return f.withDO(f.DO.Unscoped())
}

func (f flowchartVersionDo) Create(values ...*model.FlowchartVersion) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f flowchartVersionDo) CreateInBatches(values []*model.FlowchartVersion, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f flowchartVersionDo) Save(values ...*model.FlowchartVersion) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f flowchartVersionDo) First() (*model.FlowchartVersion, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowchartVersion), nil
	}
}

func (f flowchartVersionDo) Take() (*model.FlowchartVersion, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowchartVersion), nil
	}
}

func (f flowchartVersionDo) Last() (*model.FlowchartVersion, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowchartVersion), nil
	}
}

func (f flowchartVersionDo) Find() ([]*model.FlowchartVersion, error) {
	result, err := f.DO.Find()
	return result.([]*model.FlowchartVersion), err
}

func (f flowchartVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FlowchartVersion, err error) {
	buf := make([]*model.FlowchartVersion, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f flowchartVersionDo) FindInBatches(result *[]*model.FlowchartVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f flowchartVersionDo) Attrs(attrs ...field.AssignExpr) IFlowchartVersionDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f flowchartVersionDo) Assign(attrs ...field.AssignExpr) IFlowchartVersionDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f flowchartVersionDo) Joins(fields ...field.RelationField) IFlowchartVersionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f flowchartVersionDo) Preload(fields ...field.RelationField) IFlowchartVersionDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f flowchartVersionDo) FirstOrInit() (*model.FlowchartVersion, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowchartVersion), nil
	}
}

func (f flowchartVersionDo) FirstOrCreate() (*model.FlowchartVersion, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FlowchartVersion), nil
	}
}

func (f flowchartVersionDo) FindByPage(offset int, limit int) (result []*model.FlowchartVersion, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f flowchartVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f flowchartVersionDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f flowchartVersionDo) Delete(models ...*model.FlowchartVersion) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *flowchartVersionDo) withDO(do gen.Dao) *flowchartVersionDo {
	f.DO = *do.(*gen.DO)
	return f
}
