// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/repository/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMqMessage(db *gorm.DB, opts ...gen.DOOption) mqMessage {
	_mqMessage := mqMessage{}

	_mqMessage.mqMessageDo.UseDB(db, opts...)
	_mqMessage.mqMessageDo.UseModel(&model.MqMessage{})

	tableName := _mqMessage.mqMessageDo.TableName()
	_mqMessage.ALL = field.NewAsterisk(tableName)
	_mqMessage.ID = field.NewString(tableName, "id")
	_mqMessage.Topic = field.NewString(tableName, "topic")
	_mqMessage.Message = field.NewString(tableName, "message")
	_mqMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_mqMessage.UpdatedAt = field.NewTime(tableName, "updated_at")

	_mqMessage.fillFieldMap()

	return _mqMessage
}

type mqMessage struct {
	mqMessageDo mqMessageDo

	ALL       field.Asterisk
	ID        field.String // 主键，uuid
	Topic     field.String // 消息的topic
	Message   field.String // json类型字段,NSQ消息体
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (m mqMessage) Table(newTableName string) *mqMessage {
	m.mqMessageDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mqMessage) As(alias string) *mqMessage {
	m.mqMessageDo.DO = *(m.mqMessageDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mqMessage) updateTableName(table string) *mqMessage {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.Topic = field.NewString(table, "topic")
	m.Message = field.NewString(table, "message")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *mqMessage) WithContext(ctx context.Context) IMqMessageDo {
	return m.mqMessageDo.WithContext(ctx)
}

func (m mqMessage) TableName() string { return m.mqMessageDo.TableName() }

func (m mqMessage) Alias() string { return m.mqMessageDo.Alias() }

func (m *mqMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mqMessage) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["topic"] = m.Topic
	m.fieldMap["message"] = m.Message
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m mqMessage) clone(db *gorm.DB) mqMessage {
	m.mqMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mqMessage) replaceDB(db *gorm.DB) mqMessage {
	m.mqMessageDo.ReplaceDB(db)
	return m
}

type mqMessageDo struct{ gen.DO }

type IMqMessageDo interface {
	gen.SubQuery
	Debug() IMqMessageDo
	WithContext(ctx context.Context) IMqMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMqMessageDo
	WriteDB() IMqMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMqMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMqMessageDo
	Not(conds ...gen.Condition) IMqMessageDo
	Or(conds ...gen.Condition) IMqMessageDo
	Select(conds ...field.Expr) IMqMessageDo
	Where(conds ...gen.Condition) IMqMessageDo
	Order(conds ...field.Expr) IMqMessageDo
	Distinct(cols ...field.Expr) IMqMessageDo
	Omit(cols ...field.Expr) IMqMessageDo
	Join(table schema.Tabler, on ...field.Expr) IMqMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMqMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMqMessageDo
	Group(cols ...field.Expr) IMqMessageDo
	Having(conds ...gen.Condition) IMqMessageDo
	Limit(limit int) IMqMessageDo
	Offset(offset int) IMqMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMqMessageDo
	Unscoped() IMqMessageDo
	Create(values ...*model.MqMessage) error
	CreateInBatches(values []*model.MqMessage, batchSize int) error
	Save(values ...*model.MqMessage) error
	First() (*model.MqMessage, error)
	Take() (*model.MqMessage, error)
	Last() (*model.MqMessage, error)
	Find() ([]*model.MqMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqMessage, err error)
	FindInBatches(result *[]*model.MqMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MqMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMqMessageDo
	Assign(attrs ...field.AssignExpr) IMqMessageDo
	Joins(fields ...field.RelationField) IMqMessageDo
	Preload(fields ...field.RelationField) IMqMessageDo
	FirstOrInit() (*model.MqMessage, error)
	FirstOrCreate() (*model.MqMessage, error)
	FindByPage(offset int, limit int) (result []*model.MqMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMqMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mqMessageDo) Debug() IMqMessageDo {
	return m.withDO(m.DO.Debug())
}

func (m mqMessageDo) WithContext(ctx context.Context) IMqMessageDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mqMessageDo) ReadDB() IMqMessageDo {
	return m.Clauses(dbresolver.Read)
}

func (m mqMessageDo) WriteDB() IMqMessageDo {
	return m.Clauses(dbresolver.Write)
}

func (m mqMessageDo) Session(config *gorm.Session) IMqMessageDo {
	return m.withDO(m.DO.Session(config))
}

func (m mqMessageDo) Clauses(conds ...clause.Expression) IMqMessageDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mqMessageDo) Returning(value interface{}, columns ...string) IMqMessageDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mqMessageDo) Not(conds ...gen.Condition) IMqMessageDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mqMessageDo) Or(conds ...gen.Condition) IMqMessageDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mqMessageDo) Select(conds ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mqMessageDo) Where(conds ...gen.Condition) IMqMessageDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mqMessageDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IMqMessageDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m mqMessageDo) Order(conds ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mqMessageDo) Distinct(cols ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mqMessageDo) Omit(cols ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mqMessageDo) Join(table schema.Tabler, on ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mqMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mqMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mqMessageDo) Group(cols ...field.Expr) IMqMessageDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mqMessageDo) Having(conds ...gen.Condition) IMqMessageDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mqMessageDo) Limit(limit int) IMqMessageDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mqMessageDo) Offset(offset int) IMqMessageDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mqMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMqMessageDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mqMessageDo) Unscoped() IMqMessageDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mqMessageDo) Create(values ...*model.MqMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mqMessageDo) CreateInBatches(values []*model.MqMessage, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mqMessageDo) Save(values ...*model.MqMessage) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mqMessageDo) First() (*model.MqMessage, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqMessage), nil
	}
}

func (m mqMessageDo) Take() (*model.MqMessage, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqMessage), nil
	}
}

func (m mqMessageDo) Last() (*model.MqMessage, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqMessage), nil
	}
}

func (m mqMessageDo) Find() ([]*model.MqMessage, error) {
	result, err := m.DO.Find()
	return result.([]*model.MqMessage), err
}

func (m mqMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MqMessage, err error) {
	buf := make([]*model.MqMessage, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mqMessageDo) FindInBatches(result *[]*model.MqMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mqMessageDo) Attrs(attrs ...field.AssignExpr) IMqMessageDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mqMessageDo) Assign(attrs ...field.AssignExpr) IMqMessageDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mqMessageDo) Joins(fields ...field.RelationField) IMqMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mqMessageDo) Preload(fields ...field.RelationField) IMqMessageDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mqMessageDo) FirstOrInit() (*model.MqMessage, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqMessage), nil
	}
}

func (m mqMessageDo) FirstOrCreate() (*model.MqMessage, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MqMessage), nil
	}
}

func (m mqMessageDo) FindByPage(offset int, limit int) (result []*model.MqMessage, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mqMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mqMessageDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mqMessageDo) Delete(models ...*model.MqMessage) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mqMessageDo) withDO(do gen.Dao) *mqMessageDo {
	m.DO = *do.(*gen.DO)
	return m
}
