// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/repository/db/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTDict(db *gorm.DB, opts ...gen.DOOption) tDict {
	_tDict := tDict{}

	_tDict.tDictDo.UseDB(db, opts...)
	_tDict.tDictDo.UseModel(&model.TDict{})

	tableName := _tDict.tDictDo.TableName()
	_tDict.ALL = field.NewAsterisk(tableName)
	_tDict.ID = field.NewInt64(tableName, "id")
	_tDict.FType = field.NewString(tableName, "f_type")
	_tDict.Name = field.NewString(tableName, "name")
	_tDict.FDescription = field.NewString(tableName, "f_description")
	_tDict.CreatedAt = field.NewTime(tableName, "created_at")
	_tDict.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tDict.UpdaterUID = field.NewString(tableName, "updater_uid")
	_tDict.UpdaterName = field.NewString(tableName, "updater_name")
	_tDict.DeletedAt = field.NewInt64(tableName, "deleted_at")
	_tDict.SszdFlag = field.NewInt32(tableName, "sszd_flag")
	_tDict.FVersion = field.NewString(tableName, "f_version")
	_tDict.CreatorUID = field.NewString(tableName, "creator_uid")
	_tDict.CreatorName = field.NewString(tableName, "creator_name")

	_tDict.fillFieldMap()

	return _tDict
}

type tDict struct {
	tDictDo tDictDo

	ALL          field.Asterisk
	ID           field.Int64  // 唯一id，雪花算法
	FType        field.String // 字典类型
	Name         field.String // 字典名称
	FDescription field.String // 描述
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间
	UpdaterUID   field.String // 更新用户ID
	UpdaterName  field.String // 更新用户名称
	DeletedAt    field.Int64  // 删除时间
	SszdFlag     field.Int32  // 是否省市直达1是0否
	FVersion     field.String
	CreatorUID   field.String
	CreatorName  field.String

	fieldMap map[string]field.Expr
}

func (t tDict) Table(newTableName string) *tDict {
	t.tDictDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tDict) As(alias string) *tDict {
	t.tDictDo.DO = *(t.tDictDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tDict) updateTableName(table string) *tDict {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.FType = field.NewString(table, "f_type")
	t.Name = field.NewString(table, "name")
	t.FDescription = field.NewString(table, "f_description")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.UpdaterUID = field.NewString(table, "updater_uid")
	t.UpdaterName = field.NewString(table, "updater_name")
	t.DeletedAt = field.NewInt64(table, "deleted_at")
	t.SszdFlag = field.NewInt32(table, "sszd_flag")
	t.FVersion = field.NewString(table, "f_version")
	t.fillFieldMap()

	return t
}

func (t *tDict) WithContext(ctx context.Context) ITDictDo { return t.tDictDo.WithContext(ctx) }

func (t tDict) TableName() string { return t.tDictDo.TableName() }

func (t tDict) Alias() string { return t.tDictDo.Alias() }

func (t *tDict) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tDict) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["f_type"] = t.FType
	t.fieldMap["name"] = t.Name
	t.fieldMap["f_description"] = t.FDescription
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["updater_uid"] = t.UpdaterUID
	t.fieldMap["updater_name"] = t.UpdaterName
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["sszd_flag"] = t.SszdFlag
	t.fieldMap["f_version"] = t.FVersion
	t.fieldMap["creator_uid"] = t.CreatorUID
	t.fieldMap["CreatorName"] = t.CreatorName

}

func (t tDict) clone(db *gorm.DB) tDict {
	t.tDictDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tDict) replaceDB(db *gorm.DB) tDict {
	t.tDictDo.ReplaceDB(db)
	return t
}

type tDictDo struct{ gen.DO }

type ITDictDo interface {
	gen.SubQuery
	Debug() ITDictDo
	WithContext(ctx context.Context) ITDictDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITDictDo
	WriteDB() ITDictDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITDictDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITDictDo
	Not(conds ...gen.Condition) ITDictDo
	Or(conds ...gen.Condition) ITDictDo
	Select(conds ...field.Expr) ITDictDo
	Where(conds ...gen.Condition) ITDictDo
	Order(conds ...field.Expr) ITDictDo
	Distinct(cols ...field.Expr) ITDictDo
	Omit(cols ...field.Expr) ITDictDo
	Join(table schema.Tabler, on ...field.Expr) ITDictDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITDictDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITDictDo
	Group(cols ...field.Expr) ITDictDo
	Having(conds ...gen.Condition) ITDictDo
	Limit(limit int) ITDictDo
	Offset(offset int) ITDictDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITDictDo
	Unscoped() ITDictDo
	Create(values ...*model.TDict) error
	CreateInBatches(values []*model.TDict, batchSize int) error
	Save(values ...*model.TDict) error
	First() (*model.TDict, error)
	Take() (*model.TDict, error)
	Last() (*model.TDict, error)
	Find() ([]*model.TDict, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDict, err error)
	FindInBatches(result *[]*model.TDict, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TDict) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITDictDo
	Assign(attrs ...field.AssignExpr) ITDictDo
	Joins(fields ...field.RelationField) ITDictDo
	Preload(fields ...field.RelationField) ITDictDo
	FirstOrInit() (*model.TDict, error)
	FirstOrCreate() (*model.TDict, error)
	FindByPage(offset int, limit int) (result []*model.TDict, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITDictDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tDictDo) Debug() ITDictDo {
	return t.withDO(t.DO.Debug())
}

func (t tDictDo) WithContext(ctx context.Context) ITDictDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tDictDo) ReadDB() ITDictDo {
	return t.Clauses(dbresolver.Read)
}

func (t tDictDo) WriteDB() ITDictDo {
	return t.Clauses(dbresolver.Write)
}

func (t tDictDo) Session(config *gorm.Session) ITDictDo {
	return t.withDO(t.DO.Session(config))
}

func (t tDictDo) Clauses(conds ...clause.Expression) ITDictDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tDictDo) Returning(value interface{}, columns ...string) ITDictDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tDictDo) Not(conds ...gen.Condition) ITDictDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tDictDo) Or(conds ...gen.Condition) ITDictDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tDictDo) Select(conds ...field.Expr) ITDictDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tDictDo) Where(conds ...gen.Condition) ITDictDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tDictDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ITDictDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t tDictDo) Order(conds ...field.Expr) ITDictDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tDictDo) Distinct(cols ...field.Expr) ITDictDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tDictDo) Omit(cols ...field.Expr) ITDictDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tDictDo) Join(table schema.Tabler, on ...field.Expr) ITDictDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tDictDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITDictDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tDictDo) RightJoin(table schema.Tabler, on ...field.Expr) ITDictDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tDictDo) Group(cols ...field.Expr) ITDictDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tDictDo) Having(conds ...gen.Condition) ITDictDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tDictDo) Limit(limit int) ITDictDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tDictDo) Offset(offset int) ITDictDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tDictDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITDictDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tDictDo) Unscoped() ITDictDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tDictDo) Create(values ...*model.TDict) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tDictDo) CreateInBatches(values []*model.TDict, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tDictDo) Save(values ...*model.TDict) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tDictDo) First() (*model.TDict, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDict), nil
	}
}

func (t tDictDo) Take() (*model.TDict, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDict), nil
	}
}

func (t tDictDo) Last() (*model.TDict, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDict), nil
	}
}

func (t tDictDo) Find() ([]*model.TDict, error) {
	result, err := t.DO.Find()
	return result.([]*model.TDict), err
}

func (t tDictDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDict, err error) {
	buf := make([]*model.TDict, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tDictDo) FindInBatches(result *[]*model.TDict, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tDictDo) Attrs(attrs ...field.AssignExpr) ITDictDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tDictDo) Assign(attrs ...field.AssignExpr) ITDictDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tDictDo) Joins(fields ...field.RelationField) ITDictDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tDictDo) Preload(fields ...field.RelationField) ITDictDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tDictDo) FirstOrInit() (*model.TDict, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDict), nil
	}
}

func (t tDictDo) FirstOrCreate() (*model.TDict, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDict), nil
	}
}

func (t tDictDo) FindByPage(offset int, limit int) (result []*model.TDict, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tDictDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tDictDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tDictDo) Delete(models ...*model.TDict) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tDictDo) withDO(do gen.Dao) *tDictDo {
	t.DO = *do.(*gen.DO)
	return t
}
