// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/kweaver-ai/dsg/services/apps/data-subject/common/models"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameSubjectDomain = "subject_domain"

// SubjectDomain mapped from table <subject_domain>
type SubjectDomain struct {
	DomainID     uint64                  `gorm:"column:domain_id" json:"domain_id"`                                                        // 雪花id
	ID           string                  `gorm:"column:id;not null" json:"id"`                                                             // 对象id，uuid
	Name         string                  `gorm:"column:name;not null" json:"name"`                                                         // 名称
	Description  string                  `gorm:"column:description;not null" json:"description"`                                           // 描述
	Type         int8                    `gorm:"column:type;not null" json:"type"`                                                         // 类型：1：业务域，2：业务对象，3：业务对象，4：业务活动，5：逻辑实体，6：属性
	PathID       string                  `gorm:"column:path_id;not null" json:"path_id"`                                                   // 路径ID
	Path         string                  `gorm:"column:path;not null" json:"path"`                                                         // 路径
	Owners       models.SQLSlice[string] `gorm:"column:owners" json:"owners"`                                                              // 拥有者
	CreatedAt    time.Time               `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"`                // 创建时间
	CreatedByUID string                  `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                                     // 创建用户ID
	UpdatedAt    time.Time               `gorm:"column:updated_at;autoUpdateTime;not null;default:current_timestamp(3)" json:"updated_at"` // 更新时间
	UpdatedByUID string                  `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`                                     // 更新用户ID
	DeletedAt    soft_delete.DeletedAt   `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`                            // 删除时间(逻辑删除)
	RefID        string                  `gorm:"column:ref_id" json:"ref_id"`                                                              // 引用业务对象/业务活动id
	Unique       int8                    `gorm:"column:unique;not null" json:"unique"`                                                     // 唯一识别属性，枚举：0：不唯一，1：唯一
	StandardID   uint64                  `gorm:"column:standard_id" json:"standard_id"`                                                    // 数据标准id
	LabelID      uint64                  `gorm:"column:label_id" json:"label_id"`                                                          //标签id
	// StandardStatus   int8          		 `gorm:"column:standard_status;default:1" json:"standard_status"`      // 标准化状态，枚举：1：未标准化，2：已标准化，4：标准已修改，8：标准已删除, 9:标准创建中
}

// TableName BusinessDomain's table name
func (*SubjectDomain) TableName() string {
	return TableNameSubjectDomain
}

func (b *SubjectDomain) BeforeCreate(_ *gorm.DB) error {
	if b == nil {
		return nil
	}

	if b.DomainID == 0 {
		id, _ := utils.GetUniqueID()
		b.DomainID = id
	}
	if len(b.ID) == 0 {
		b.ID = uuid.NewString()
	}
	return nil
}

func (b *SubjectDomain) UniqueKey() string {
	return "id"
}
