// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/errorcode"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameAuditPolicyResource = "audit_policy_resources"

// AuditPolicyResource mapped from table <audit_policy_resources>
type AuditPolicyResource struct {
	Sid           uint64                `gorm:"column:sid;not null" json:"sid"`                                // 雪花id
	ID            string                `gorm:"column:id;primaryKey" json:"id"`                                // 资源id，uuid
	AuditPolicyID string                `gorm:"column:audit_policy_id;not null" json:"audit_policy_id"`        // 审核策略id，uuid
	Type          string                `gorm:"column:type;not null" json:"type"`                              // 资源类型
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"` // 删除时间(逻辑删除)
}

func (m *AuditPolicyResource) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.Sid == 0 {
		a, err := utils.GetUniqueID()
		if err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			err = errorcode.Desc(errorcode.PublicUniqueIDError)
			return err
		}
		m.Sid = a
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName AuditPolicyResource's table name
func (*AuditPolicyResource) TableName() string {
	return TableNameAuditPolicyResource
}
