// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/errorcode"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	"gorm.io/gorm"
	"time"
)

const TableNameAuditProcessBind = "audit_process_bind"

// AuditProcessBind mapped from table <audit_process_bind>
type AuditProcessBind struct {
	ID           uint64    `gorm:"column:id;primaryKey" json:"id"`                                             // 主键
	AuditType    string    `gorm:"column:audit_type;not null" json:"audit_type"`                               // 审核类型 af-data-view-publish 发布审核 af-data-view-online 上线审核  af-data-view-offline 上线审核
	ProcDefKey   string    `gorm:"column:proc_def_key;not null" json:"proc_def_key"`                           // 审核流程key
	ServiceType  string    `gorm:"column:service_type" json:"service_type"`                                    // 所属业务模块，如逻辑视图业务为data-view
	CreateTime   time.Time `gorm:"column:create_time;not null;default:current_timestamp()" json:"create_time"` // 创建时间
	CreatedByUID string    `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                       // 创建人id
	UpdateTime   time.Time `gorm:"column:update_time;not null;autoUpdateTime" json:"update_time"` // 更新时间
	UpdatedByUID string    `gorm:"column:updated_by_uid" json:"updated_by_uid"`                                // 编辑人id
}

func (m *AuditProcessBind) BeforeCreate(_ *gorm.DB) (err error) {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		if m.ID, err = utils.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			err = errorcode.Desc(errorcode.PublicUniqueIDError)
		}
	}

	return nil
}

// TableName AuditProcessBind's table name
func (*AuditProcessBind) TableName() string {
	return TableNameAuditProcessBind
}
