// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.


package model

import (
	"database/sql"
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/errorcode"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameBusinessMatter = "business_matters"

// BusinessMatter mapped from table <business_matters>
type BusinessMatter struct {
	ID                uint64                `gorm:"column:id;primaryKey" json:"id"`                                                // 雪花id
	BusinessMattersID string                `gorm:"column:business_matters_id;not null;default:uuid()" json:"business_matters_id"` // 对象ID, uuid
	Name              string                `gorm:"column:name;not null" json:"name"`                                              // 业务事项名称
	TypeKey           string                `gorm:"column:type_key;not null" json:"type_key"`                                      // 业务事项类型key
	DepartmentID      string                `gorm:"column:department_id;not null" json:"department_id"`                            // 所属部门
	MaterialsNumber   sql.NullInt64         `gorm:"column:materials_number;not null" json:"materials_number"`                      // 材料数
	CreatedAt         time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"`     // 创建时间
	CreatorUID        string                `gorm:"column:creator_uid;not null" json:"creator_uid"`                                // 创建用户ID
	UpdatedAt         time.Time             `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`     // 更新时间
	UpdaterUID        string                `gorm:"column:updater_uid;not null" json:"updater_uid"`                                // 更新用户ID
	DeletedAt         soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`                 // 删除时间(逻辑删除)
}

type CssjjBusinessMatter struct {
	ID                uint64                `gorm:"column:id;primaryKey" json:"id"`                                                // 雪花id
	BusinessMattersID string                `gorm:"column:business_matters_id;not null;default:uuid()" json:"business_matters_id"` // 对象ID, uuid
	Name              string                `gorm:"column:name;not null" json:"name"`                                              // 业务事项名称
	TypeKey           string                `gorm:"column:type_key;not null" json:"type_key"`                                      // 业务事项类型key
	DepartmentID      string                `gorm:"column:department_id;not null" json:"department_id"`                            // 所属部门
	DepartmentName    string                `gorm:"column:department_name;not null" json:"department_name"`                        // 所属部门
	MaterialsNumber   sql.NullInt64         `gorm:"column:materials_number;not null" json:"materials_number"`                      // 材料数
	CreatedAt         time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"`     // 创建时间
	CreatorUID        string                `gorm:"column:creator_uid;not null" json:"creator_uid"`                                // 创建用户ID
	UpdatedAt         time.Time             `gorm:"column:updated_at;not null;autoUpdateTime;default:current_timestamp(3)" json:"updated_at"`     // 更新时间
	UpdaterUID        string                `gorm:"column:updater_uid;not null" json:"updater_uid"`                                // 更新用户ID
	DeletedAt         soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`                 // 删除时间(逻辑删除)
}

func (m *BusinessMatter) BeforeCreate(_ *gorm.DB) error {
	var err error
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		if m.ID, err = utils.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			err = errorcode.Desc(errorcode.PublicUniqueIDError)
			return err
		}
	}

	if len(m.BusinessMattersID) == 0 {
		m.BusinessMattersID = util.NewUUID()
	}

	return nil
}

// TableName BusinessMatter's table name
func (*BusinessMatter) TableName() string {
	return TableNameBusinessMatter
}
