// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/models"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
	"time"
)

const TableNameDataGrade = "data_grade"

type DataGrade struct {
	ID models.ModelID `gorm:"column:id;primaryKey" json:"id"` // 雪花id
	//GradeId     string 					`gorm:"column:grade_id;primaryKey" json:"grade_id"` // 业务主键ID
	ParentID     models.ModelID        `gorm:"column:parent_id;not null" json:"parent_id"`                    // 父目录类别id，为0表示没有父id
	Name         string                `gorm:"column:name;not null" json:"name"`                              // 名称
	Description  string                `gorm:"column:description;not null" json:"description"`                // 描述
	SortWeight   uint64                `gorm:"column:sort_weight;not null" json:"sort_weight"`                // 排序权重
	NodeType     int                   `gorm:"column:node_type;not null" json:"node_type"`                    // 节点类型
	Icon         string                `gorm:"column:icon;not null" json:"icon"`                              // 目录类别描述
	SensitiveAttri      *string        `gorm:"column:sensitive_attri" json:"sensitive_attri"`                 // 敏感属性预设
	SecretAttri         *string        `gorm:"column:secret_attri" json:"secret_attri"`                       // 涉密属性预设
	ShareCondition      *string        `gorm:"column:share_condition" json:"share_condition"` 				  // 共享条件：不共享，有条件共享，无条件共享
	DataProtectionQuery bool           `gorm:"column:data_protection_query;not null" json:"data_protection_query"`     // 数据保护查询开关
	CreatedAt    *time.Time            `gorm:"column:created_at;not null" json:"created_at"`                  // 创建时间
	CreatedByUID string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`          // 创建用户ID
	UpdatedAt    *time.Time            `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`                  // 更新时间
	UpdatedByUID string                `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`          // 更新用户ID
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"` // 删除时间(逻辑删除)
}

func (m *DataGrade) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID.Uint64() > 0 {
		return nil
	}

	id, err := util.NewUniqueID()
	if err != nil {
		return err
	}

	m.ID = models.NewModelID(id)

	return nil
}

func (*DataGrade) TableName() string {
	return TableNameDataGrade
}
