// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/errorcode"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	"gorm.io/gorm"
	"time"
)

const TableNameDatasource = "datasource"

// Datasource mapped from table <datasource>
type Datasource struct {
	DataSourceID  uint64         `gorm:"column:data_source_id;primaryKey" json:"data_source_id"`           // 数据源雪花id
	ID            string         `gorm:"column:id;not null" json:"id"`                                     // 数据源业务id
	InfoSystemID  sql.NullString `gorm:"column:info_system_id" json:"info_system_id" swaggertype:"string"` // 信息系统id
	Name          string         `gorm:"column:name;not null" json:"name"`                                 // 数据源名称
	CatalogName   string         `gorm:"column:catalog_name;not null" json:"catalog_name"`                 // 数据源catalog名称
	Host          string         `gorm:"column:host;not null" json:"host"`                                 // 连接地址
	Port          int32          `gorm:"column:port;not null" json:"port"`                                 // 端口
	Username      string         `gorm:"column:username;not null" json:"username"`                         // 用户名
	Password      string         `gorm:"column:password;not null" json:"password"`                         // 密码
	DatabaseName  string         `gorm:"column:database_name;not null" json:"database_name"`               // 数据库名称
	Schema        string         `gorm:"column:schema;not null" json:"schema"`                             // 数据库模式
	SourceType    int32          `gorm:"column:source_type;not null;default:0" json:"source_type"`         // 数据源类型 1:记录型、2:分析型
	CreatedByUID  string         `gorm:"column:created_by_uid" json:"created_by_uid"`                      // 创建人id
	CreatedAt     time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`    // 创建时间
	UpdatedByUID  string         `gorm:"column:updated_by_uid" json:"updated_by_uid"`                      // 更新人id
	UpdatedAt     time.Time      `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`    // 更新时间
	TypeName      string         `gorm:"column:type_name;not null" json:"type_name"`                       // 数据库类型名称
	ExcelProtocol string         `gorm:"column:excel_protocol" json:"excel_protocol" `                     //excel 存储位置
	ExcelBase     string         `gorm:"column:excel_base" json:"excel_base" `                             //excel 路径
	DepartmentId  string         `gorm:"column:department_id"  json:"department_id"`                       //关联部门id
	Enabled       bool           `gorm:"column:enabled"  json:"enabled"`                                   //是否启用
	HuaAoId       string         `gorm:"column:hua_ao_id" json:"hua_ao_id"`                                //华傲数据源id
	ConnectStatus int32          `gorm:"column:connect_status" json:"connect_status"`                      //连接状态 1已连接 2未连接
}

func (m *Datasource) UniqueKey() string {
	return "id"
}

func (m *Datasource) BeforeCreate(_ *gorm.DB) (err error) {
	if m == nil {
		return nil
	}

	if m.DataSourceID == 0 {
		if m.DataSourceID, err = utils.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			err = errorcode.Desc(errorcode.PublicUniqueIDError)
		}
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName Datasource's table name
func (*Datasource) TableName() string {
	return TableNameDatasource
}
