// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameFlowchart = "flowchart"

// Flowchart mapped from table <flowchart>
type Flowchart struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`                           // 主键，uuid
	Name        string `gorm:"column:name;not null" json:"name"`                         // 运营流程名称
	Description string `gorm:"column:description;not null" json:"description"`           // 运营流程描述说明
	EditStatus  int32  `gorm:"column:edit_status;not null;default:1" json:"edit_status"` // 当前版本运营流程编辑状态，枚举：1：新建中；2：正常；3：编辑中
	//ConfigStatus       int32     `gorm:"column:config_status;not null;default:1" json:"config_status"`              // 运营流程配置状态，默认1正常，2任务执行角色缺失
	CurrentVersionID   string                `gorm:"column:current_version_id;not null" json:"current_version_id"`              // 当前使用的已发布运营流程版本ID
	EditingVersionID   string                `gorm:"column:editing_version_id;not null" json:"editing_version_id"`              // 正在编辑的运营流程版本ID
	ClonedByID         string                `gorm:"column:cloned_by_id;not null" json:"cloned_by_id"`                          // 复用的运营流程ID，空表示没有复用
	ClonedByTemplateID string                `gorm:"column:cloned_by_template_id;not null" json:"cloned_by_template_id"`        // 复用的运营流程模版ID，空表示没有复用
	CreatedAt          time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	CreatedByUID       string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                      // 创建用户ID
	UpdatedAt          time.Time             `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"` // 更新时间
	UpdatedByUID       string                `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`                      // 更新用户ID
	DeletedAt          soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`             // 删除时间(逻辑删除)
}

func (m *Flowchart) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName Flowchart's table name
func (*Flowchart) TableName() string {
	return TableNameFlowchart
}
