// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameFlowchartVersion = "flowchart_version"

// FlowchartVersion mapped from table <flowchart_version>
type FlowchartVersion struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`                                            // 主键，uuid
	Name           string    `gorm:"column:name;not null" json:"name"`                                          // 运营流程版本名称，eg:v1
	Version        int32     `gorm:"column:version;not null;default:1" json:"version"`                          // 运营流程版本
	EditStatus     int32     `gorm:"column:edit_status;not null;default:1" json:"edit_status"`                  // 当前版本运营流程编辑状态，枚举：2：正常；3：编辑中
	Image          string    `gorm:"column:image" json:"image"`                                                 // 图片文件内容，base64编码
	FlowchartID    string    `gorm:"column:flowchart_id;not null" json:"flowchart_id"`                          // 运营流程ID
	DrawProperties string    `gorm:"column:draw_properties" json:"draw_properties"`                             // 图形属性，包含位置、形状、大小等
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	CreatedByUID   string    `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                      // 创建用户ID
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"` // 更新时间
	UpdatedByUID   string    `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`                      // 更新用户ID
	DeletedAt      soft_delete.DeletedAt     `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`              // 删除时间(逻辑删除)
}

func (m *FlowchartVersion) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName FlowchartVersion's table name
func (*FlowchartVersion) TableName() string {
	return TableNameFlowchartVersion
}
