// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameFlowchartNodeConfig = "flowchart_node_config"

// FlowchartNodeConfig mapped from table <flowchart_node_config>
type FlowchartNodeConfig struct {
	ID                 string                `gorm:"column:id;primaryKey" json:"id"`                                   // 主键，uuid
	StartMode          int32                 `gorm:"column:start_mode;not null;default:1" json:"start_mode"`           // 启动方式，枚举：1：任一前序节点完成；2：全部前序节点完成；3：任一前序节点处于非未启动
	CompletionMode     int32                 `gorm:"column:completion_mode;not null;default:1" json:"completion_mode"` // 完成方式，枚举：1：手动确认；2：自动完成
	NodeID             string                `gorm:"column:node_id;not null" json:"node_id"`                           // 节点ID，flowchart_unit表的id字段
	FlowchartVersionID string                `gorm:"column:flowchart_version_id;not null" json:"flowchart_version_id"` // 运营流程版本ID
	DeletedAt          soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`    // 删除时间(逻辑删除)
}

func (m *FlowchartNodeConfig) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName FlowchartNodeConfig's table name
func (*FlowchartNodeConfig) TableName() string {
	return TableNameFlowchartNodeConfig
}
