// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameFlowchartNodeTask = "flowchart_node_task"

// FlowchartNodeTask mapped from table <flowchart_node_task>
type FlowchartNodeTask struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`                                   // 主键，uuid
	Name           string `gorm:"column:name;not null" json:"name"`                                 // 任务类型名称
	CompletionMode int32  `gorm:"column:completion_mode;not null;default:1" json:"completion_mode"` // 完成方式，枚举：1：手动确认；2：自动完成
	//ExecRoleID         string                `gorm:"column:exec_role_id;not null" json:"exec_role_id"`                 // 执行角色
	NodeID             string                `gorm:"column:node_id;not null" json:"node_id"`                           // 节点ID，flowchart_unit表的id字段
	NodeUnitID         string                `gorm:"column:node_unit_id;not null" json:"node_unit_id"`                 // 节点组件ID，冗余
	FlowchartVersionID string                `gorm:"column:flowchart_version_id;not null" json:"flowchart_version_id"` // 运营流程版本ID
	TaskType           int32                 `gorm:"column:task_type;not null;default:1" json:"task_type"`             // 任务类型数组，取值范围:1 普通任务(默认)，2 新建模型类任务，4 标准化任务。
	WorkOrderType      int32                 `gorm:"column:work_order_type;not null;default:0" json:"work_order_type"` // 任务类型数组，取值范围:1 普通任务(默认)，2 新建模型类任务，4 标准化任务。
	DeletedAt          soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`    // 删除时间(逻辑删除)
}

func (m *FlowchartNodeTask) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName FlowchartNodeTask's table name
func (*FlowchartNodeTask) TableName() string {
	return TableNameFlowchartNodeTask
}
