// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameFlowchartUnit = "flowchart_unit"

// FlowchartUnit mapped from table <flowchart_unit>
type FlowchartUnit struct {
	ID                 string                `gorm:"column:id;primaryKey" json:"id"`                                   // 主键，uuid
	UnitType           int32                 `gorm:"column:unit_type;not null" json:"unit_type"`                       // 单元类型，枚举：1：阶段；2：节点；3：连接线
	UnitID             string                `gorm:"column:unit_id;not null" json:"unit_id"`                           // 单元ID
	Name               string                `gorm:"column:name;not null" json:"name"`                                 // 单元名称
	Description        string                `gorm:"column:description;not null" json:"description"`                   // 单元描述说明
	ParentID           string                `gorm:"column:parent_id;not null" json:"parent_id"`                       // 所属单元ID
	ParentUnitID       string                `gorm:"column:parent_unit_id;not null" json:"parent_unit_id"`             // 所属单元ID，冗余
	SourceID           string                `gorm:"column:source_id;not null" json:"source_id"`                       // 来源单元ID
	SourceUnitID       string                `gorm:"column:source_unit_id;not null" json:"source_unit_id"`             // 来源单元ID，冗余
	TargetID           string                `gorm:"column:target_id;not null" json:"target_id"`                       // 目标单元ID
	TargetUnitID       string                `gorm:"column:target_unit_id;not null" json:"target_unit_id"`             // 目标单元ID，冗余
	UnitOrder          int32                 `gorm:"column:unit_order;not null" json:"unit_order"`                     // 单元次序，目前主要为阶段的先后顺序，从1开始
	FlowchartVersionID string                `gorm:"column:flowchart_version_id;not null" json:"flowchart_version_id"` // 运营流程版本ID
	DeletedAt          soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`    // 删除时间(逻辑删除)
}

func (m *FlowchartUnit) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName FlowchartUnit's table name
func (*FlowchartUnit) TableName() string {
	return TableNameFlowchartUnit
}
