// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/errorcode"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	log "github.com/kweaver-ai/idrm-go-frame/core/logx/zapx"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameInfoSystem = "info_system"

// InfoSystem mapped from table <info_system>
type InfoSystem struct {
	InfoStstemID      uint64                `gorm:"column:info_ststem_id;primaryKey" json:"info_ststem_id"`                      // 信息系统雪花id
	ID                string                `gorm:"column:id;not null" json:"id"`                                                // 信息系统业务id
	Name              string                `gorm:"column:name;not null" json:"name"`                                            // 信息系统名称
	Description       sql.NullString        `gorm:"column:description" json:"description"`                                       // 信息系统描述
	DepartmentId      sql.NullString        `gorm:"column:department_id" json:"department_id"`                                   // 信息系统部门ID
	AcceptanceAt      sql.NullInt64         `gorm:"column:acceptance_at" json:"acceptance_at"`                                   // 验收日期
	IsRegisterGateway sql.NullInt32         `gorm:"column:is_register_gateway;not null" json:"is_register_gateway"`              // 是否注册，bool：0：不是；1：是
	SystemIdentifier  string                `gorm:"column:system_identifier" json:"system_identifier"`                           // 系统标识·
	RegisterAt        time.Time             `gorm:"column:register_at;not null;default:current_timestamp(3)" json:"register_at"` // 注册时间
	CreatedAt         time.Time             `gorm:"column:created_at;autoCreateTime:milli;" json:"created_at"`                                // 创建时间
	CreatedByUID      string                `gorm:"column:created_by_uid;not null" json:"created_by_uid"`                        // 创建用户ID
	UpdatedAt         time.Time             `gorm:"column:updated_at;autoUpdateTime:milli" json:"updated_at"`                                // 更新时间
	UpdatedByUID      string                `gorm:"column:updated_by_uid;not null" json:"updated_by_uid"`                        // 更新用户ID
	DeletedAt         soft_delete.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`                                // 删除时间
	JsDepartmentId sql.NullString  `json:"js_department_id" gorm:"js_department_id" ` // 建设部门ID
	Status         int    `json:"status" gorm:"status"`                                      // 建设状态1已建、2拟建、3在建
}

func (m *InfoSystem) UniqueKey() string {
	return "id"
}

func (m *InfoSystem) BeforeCreate(_ *gorm.DB) (err error) {
	if m == nil {
		return nil
	}

	if m.InfoStstemID == 0 {
		if m.InfoStstemID, err = utils.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			err = errorcode.Desc(errorcode.PublicUniqueIDError)
		}
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName InfoSystem's table name
func (*InfoSystem) TableName() string {
	return TableNameInfoSystem
}
