// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameMqMessage = "mq_message"

// MqMessage mapped from table <mq_message>
type MqMessage struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`                                            // 主键，uuid
	Topic     string    `gorm:"column:topic;not null" json:"topic"`                                        // 消息的topic
	Message   string    `gorm:"column:message;not null" json:"message"`                                    // json类型字段,NSQ消息体
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"` // 更新时间
}

func (m *MqMessage) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName MqMessage's table name
func (*MqMessage) TableName() string {
	return TableNameMqMessage
}
