// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameObject = "object"

// Object mapped from table <object>
type Object struct {
	ID          string                `gorm:"column:id;primaryKey" json:"id"`                                            // 对象ID
	Name        string                `gorm:"column:name;not null" json:"name"`                                          // 对象名称
	PathID      string                `gorm:"column:path_id;not null" json:"path_id"`                                    // 路径ID
	Path        string                `gorm:"column:path;not null" json:"path"`                                          // 路径
	Type        int32                 `gorm:"column:type" json:"type"`                                                   // 类型
	Attribute   string                `gorm:"column:attribute" json:"attribute"`                                         // 属性信息：包括简称、机构编码、信用代码等
	CreatedAt   time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	UpdatedAt   time.Time             `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"` // 更新时间
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`             // 删除时间(逻辑删除)
	ThirdDeptId string                `gorm:"column:f_third_dept_id" json:"third_dept_id"`                               //第三方部门ID
	IsRegister  int32                 `gorm:"column:is_register" json:"registered"`
	RegisterAt  *time.Time            `gorm:"column:register_at;not null;default:current_timestamp(3)" json:"register_at"`
	DeptTag     string                `gorm:"column:dept_tag" json:"dept_tag"`
}

func (m *Object) UniqueKey() string {
	return "id"
}

func (m *Object) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName Object's table name
func (*Object) TableName() string {
	return TableNameObject
}
