// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	//"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
)

const TableNameResource = "resource"

// Resource mapped from table <resource>
type Resource struct {
	ID      uint64 `gorm:"column:id;primaryKey" json:"id"`
	RoleID  string `gorm:"column:role_id;not null" json:"role_id"`
	Type    int32  `gorm:"column:type;not null" json:"type"`
	SubType int32  `gorm:"column:sub_type;not null" json:"sub_type"`
	Value   int32  `gorm:"column:value;not null" json:"value"`
}

func (m *Resource) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		//m.ID = util.NewUUID()
		m.ID, _ = utils.GetUniqueID()
	}

	return nil
}

// TableName Resource's table name
func (*Resource) TableName() string {
	return TableNameResource
}
