// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/plugin/soft_delete"
	"time"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameSystemRole = "system_role"

// SystemRole mapped from table <system_role>
type SystemRole struct {
	ID        string                `gorm:"column:id;primaryKey" json:"id"`                                            // 主键，uuid
	Name      string                `gorm:"column:name;not null" json:"name"`                                          // 角色名称
	Description string				`gorm:"column:description" json:"description"`									   // 描述
	Color     string                `gorm:"column:color" json:"color"`                                                 // 角色背景色
	Icon      string                `gorm:"column:icon" json:"icon"`                                                   // 角色图标
	Type      string                `gorm:"column:type" json:"type"`                                                   // 类型
	Scope     string                `gorm:"column:scope" json:"scope"`                                                 // 权限范围
	// Deprecated: Use Type instead.
	System    int32                 `gorm:"column:system;not null" json:"system"`                                      // 是否是系统默认的角色1表示是默认，0表示不是
	CreatedAt time.Time             `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
	CreatedBy string    			`gorm:"column:created_by" json:"created_by"`                   					   // 创建人id
	UpdatedAt time.Time             `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"` // 更新时间
	UpdatedBy string    			`gorm:"column:updated_by" json:"updated_by"`                   					   // 更新人id
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`             // 删除时间(逻辑删除)
}

func (m *SystemRole) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName SystemRole's table name
func (*SystemRole) TableName() string {
	return TableNameSystemRole
}
