// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameTMenuAPI = "t_menu_api"

// TMenuAPI mapped from table <t_menu_api>
type TMenuAPI struct {
	ID          string `gorm:"column:f_id;primaryKey" json:"id"`
	ServiceName string `gorm:"column:f_service_name;not null" json:"service_name"` // 服务名称
	HashID      string `gorm:"column:f_hash_id;not null" json:"hash_id"`           // path.method.action 的md5值
	Path        string `gorm:"column:f_path;not null" json:"path"`                 // 接口路径
	Method      string `gorm:"column:f_method;not null" json:"method"`             // 接口方法
}

func (m *TMenuAPI) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName TMenuAPI's table name
func (*TMenuAPI) TableName() string {
	return TableNameTMenuAPI
}
