// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameTMenuAPIRelation = "t_menu_api_relation"

// TMenuAPIRelation mapped from table <t_menu_api_relation>
type TMenuAPIRelation struct {
	ID     string `gorm:"column:f_id;primaryKey" json:"id"`       // 主键ID
	Aid    string `gorm:"column:f_aid;not null" json:"aid"`       // 接口ID
	Action string `gorm:"column:f_action;not null" json:"action"` // 动作
	Key    string `gorm:"column:f_key;not null" json:"key"`       // 服务名称
}

func (m *TMenuAPIRelation) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName TMenuAPIRelation's table name
func (*TMenuAPIRelation) TableName() string {
	return TableNameTMenuAPIRelation
}
