// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/dsg/services/apps/configuration-center/common/util"
	"gorm.io/gorm"
)

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	ID        string    `gorm:"column:id;not null" json:"id"`                                              // 主键，uuid
	UserID    string    `gorm:"column:user_id;primaryKey" json:"user_id"`                                  // 用户ID，uuid
	RoleID    string    `gorm:"column:role_id;primaryKey" json:"role_id"`                                  // 角色ID，uuid
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"` // 创建时间
}

func (m *UserRole) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if len(m.ID) == 0 {
		m.ID = util.NewUUID()
	}

	return nil
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
