// Code generated by MockGen. DO NOT EDIT.
// Source: ./domain/tc_member/logic.go

// Package mock is a generated GoMock package.
package impl

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kweaver-ai/dsg/services/apps/task_center/infrastructure/repository/db/model"
)

// MockMemberRepo is a mock of MemberRepo interface.
type MockMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRepoMockRecorder
}

// MockMemberRepoMockRecorder is the mock recorder for MockMemberRepo.
type MockMemberRepoMockRecorder struct {
	mock *MockMemberRepo
}

// NewMockMemberRepo creates a new mock instance.
func NewMockMemberRepo(ctrl *gomock.Controller) *MockMemberRepo {
	mock := &MockMemberRepo{ctrl: ctrl}
	mock.recorder = &MockMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRepo) EXPECT() *MockMemberRepoMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockMemberRepo) Query(ctx context.Context, obj int8, objId string) ([]*model.TcMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, obj, objId)
	ret0, _ := ret[0].([]*model.TcMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockMemberRepoMockRecorder) Query(ctx, obj, objId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockMemberRepo)(nil).Query), ctx, obj, objId)
}
