// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	impl35 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/audit_process_bind/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/callbacks"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/common"
	impl54 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/address_book/impl"
	impl58 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/alarm_rule/impl"
	impl32 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/apps/impl"
	impl64 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/audit_policy/impl"
	impl45 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/business_matters/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/business_structure/impl"
	impl60 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/carousels/impl"
	impl20 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/code_generation_rule/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/configuration/impl"
	impl42 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/data_grade/impl"
	impl38 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/datasource/impl"
	impl46 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/dict/impl"
	impl49 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/firm/impl"
	impl23 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/flowchart/impl"
	impl26 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/flowchart_node_config/impl"
	impl27 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/flowchart_node_task/impl"
	impl25 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/flowchart_unit/impl"
	impl24 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/flowchart_version/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/front_end_processor"
	impl34 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/info_system/impl"
	impl33 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/liyue_registrations/impl"
	impl51 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/menu/impl"
	impl62 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/news_policy/impl"
	impl56 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/object_main_business/impl"
	impl2 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/object_subtype/impl"
	impl14 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/permission/impl"
	impl66 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/register/impl"
	impl5 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/resource/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/role/impl"
	impl16 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/role2/impl"
	impl13 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/role_group/impl"
	impl12 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/role_group_role_binding/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/role_permission_binding/impl"
	impl21 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/user/impl"
	impl3 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/user2/impl"
	impl9 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/user_permission_binding/impl"
	impl10 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/user_role_binding/impl"
	impl11 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/gorm/user_role_group_binding/impl"
	impl7 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/mq/configuration/impl"
	impl39 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/mq/datasource/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/data_connection"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/data_subject"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/hydra/v6"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/sszd_service"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/standardization"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/user_management"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/virtualization_engine"
	impl36 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/rest/workflow/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/spt"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/thrift/sharemgnt"
	impl28 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/tool/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driven/workflow"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver"
	v1_8 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/address_book/v1"
	v1_9 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/alarm_rule/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/apps/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/audit_policy/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/audit_process_bind/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/business_matters/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/business_structure/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/carousels/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/code_generation_rule/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/configuration/v1"
	user2 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/data_grade/v1"
	v1_5 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/data_masking/v1"
	v1_3 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/datasource/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/dict/v1"
	v1_6 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/firm/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/flowchart/v1"
	front_end_processor3 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/front_end_processor/v1"
	v1_4 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/info_system/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/menu"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/middleware"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/mq"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/mq/datasource"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/mq/department"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/mq/user_mgm"
	v1_11 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/news_policy/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/object_main_business/v1"
	v1_10 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/permission/v1"
	v1_12 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/register/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/role/v2"
	v1_13 "github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/sms_conf/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/tool/v1"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/adapter/driver/user/v1"
	impl55 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/address_book/impl"
	impl59 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/alarm_rule/impl"
	impl37 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/apps/impl"
	impl65 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/audit_policy/impl"
	impl44 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/audit_process_bind/impl"
	impl47 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/business_matters/impl"
	impl19 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/business_structure/impl"
	impl61 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/carousels/impl"
	impl22 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/code_generation_rule/impl"
	impl8 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/configuration/impl"
	impl43 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/data_grade/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/data_masking"
	impl40 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/datasource/impl"
	impl48 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/dict/impl"
	impl50 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/firm/impl"
	impl29 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/flowchart/impl"
	front_end_processor2 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/front_end_processor"
	impl41 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/info_system/impl"
	impl53 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/menu/impl"
	impl63 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/news_policy/impl"
	impl57 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/object_main_business/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/permission"
	impl67 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/register/impl"
	impl30 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/role_v2/impl"
	impl68 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/sms_conf/impl"
	impl31 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/tool/impl"
	impl18 "github.com/kweaver-ai/dsg/services/apps/configuration-center/domain/user/impl"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/conf"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/mq/kafka"
	"github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/repository/db"
	redis2 "github.com/kweaver-ai/dsg/services/apps/configuration-center/infrastructure/repository/redis"
	impl52 "github.com/kweaver-ai/idrm-go-common/d_session/impl"
	"github.com/kweaver-ai/idrm-go-common/go-ceph-client"
	v1_2 "github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl17 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl15 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	v1_7 "github.com/kweaver-ai/idrm-go-common/rest/doc_audit_rest/v1"
	user_management2 "github.com/kweaver-ai/idrm-go-common/rest/user_management"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/trace"
	"github.com/kweaver-ai/idrm-go-frame/core/utils/httpclient"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitApp(server *conf.Server, database *db.Database, options *redis.Options) (*AppRunner, func(), error) {
	gormDB, cleanup, err := db.NewData(database)
	if err != nil {
		return nil, nil, err
	}
	query := common.GetQuery(gormDB)
	repo := impl.NewBusinessStructureRepo(query)
	client := trace.NewOtelHttpClient()
	cephClient, err := gocephclient.NewCephClient(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpClient := httpclient.NewMiddlewareHTTPClient(client)
	drivenUserMgnt := user_management.NewUserMgnt(httpClient)
	producer, err := kafka.NewSyncProducer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	business_structureRepo := impl2.NewRepo(gormDB)
	iUserRepo := impl3.NewUserRepo(gormDB)
	roleRepo := impl4.NewRoleRepo(gormDB)
	resourceRepo := impl5.NewResourceRepo(gormDB)
	configurationRepo := impl6.NewConfigurationRepo(gormDB)
	configurationHandle := impl7.NewMQHandleInstance(producer)
	configurationCase := impl8.NewConfiguration(configurationRepo, configurationHandle)
	shareMgnDriven := sharemanagement.NewDriven()
	user_permission_bindingRepo := impl9.NewRepo(gormDB)
	user_role_bindingRepo := impl10.NewRepo(gormDB)
	user_role_group_bindingRepo := impl11.NewRepo(gormDB)
	role_permission_bindingRepo := impltype.NewRepo(gormDB)
	role_group_role_bindingRepo := impl12.NewRepo(gormDB)
	role_groupRepo := impl13.NewRepo(gormDB)
	permissionRepo := impl14.NewRepo(gormDB)
	driven := impl15.NewConfigurationCenterDrivenByService(client)
	role2Repo := impl16.NewRepo(gormDB)
	authorizationDriven := impl17.NewDriven(client)
	useCase := impl18.NewUser(iUserRepo, drivenUserMgnt, roleRepo, resourceRepo, configurationRepo, configurationCase, shareMgnDriven, user_permission_bindingRepo, user_role_bindingRepo, user_role_group_bindingRepo, role_permission_bindingRepo, role_group_role_bindingRepo, role_groupRepo, permissionRepo, driven, role2Repo, repo, authorizationDriven, business_structureRepo)
	business_structureUseCase := impl19.NewBusinessStructUseCase(repo, cephClient, drivenUserMgnt, producer, business_structureRepo, useCase)
	service := business_structure.NewService(business_structureUseCase)
	code_generation_ruleRepo := impl20.NewCodeGenerationRuleRepo(gormDB)
	userRepo := impl21.NewUserRepo(gormDB)
	code_generation_ruleUseCase := impl22.NewCodeGenerationRuleUseCase(code_generation_ruleRepo, userRepo)
	v1Service := v1.NewService(code_generation_ruleUseCase)
	flowchartRepo := impl23.NewFlowchartRepo(gormDB)
	flowchart_versionRepo := impl24.NewFlowchartVersionRepo(gormDB)
	flowchart_unitRepo := impl25.NewFlowchartUnit(query)
	flowchart_node_configRepo := impl26.NewFlowchartNodeConfigRepo(query)
	flowchart_node_taskRepo := impl27.NewFlowchartNodeTask(query)
	toolRepo := impl28.NewToolRepo()
	flowchartUseCase := impl29.NewFlowchartUseCase(flowchartRepo, flowchart_versionRepo, flowchart_unitRepo, flowchart_node_configRepo, flowchart_node_taskRepo, roleRepo, toolRepo, iUserRepo)
	flowchartService := flowchart.NewService(flowchartUseCase)
	role_v2UseCase := impl30.NewRoleUseCase(authorizationDriven)
	v2Service := v2.NewService(role_v2UseCase)
	toolUseCase := impl31.NewToolUsecase(toolRepo)
	toolService := tool.NewService(toolUseCase)
	userService := user.NewService(useCase)
	hydra := v6.NewHydra(client)
	appsRepo := impl32.NewAppsRepo(gormDB)
	liyueRegistrationsRepo := impl33.NewLiyueRegistrationsRepo(gormDB)
	info_systemRepo := impl34.NewInfoSystemRepo(gormDB)
	authServiceInternalV1Interface, err := v1_2.NewInternalForBase(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sszdService := sszd_service.NewSszdService(client)
	auditProcessBindRepo := impl35.NewAuditProcessBindRepo(gormDB)
	workflowWorkflow := impl36.NewWorkflow(client)
	workflowInterface, err := impl36.NewCommonWorkflow(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clientConnInterface, err := spt.NewGRPCClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userServiceClient := spt.NewUserRegisterClient(clientConnInterface)
	appsUseCase := impl37.NewAuditProcessBindUseCase(appsRepo, liyueRegistrationsRepo, drivenUserMgnt, hydra, useCase, info_systemRepo, roleRepo, repo, authServiceInternalV1Interface, sszdService, auditProcessBindRepo, workflowWorkflow, producer, workflowInterface, userServiceClient)
	middlewareMiddleware := middleware.NewMiddleware(hydra, useCase, drivenUserMgnt, appsUseCase)
	datasourceRepo := impl38.NewDataSourceRepo(gormDB)
	drivenVirtualizationEngine := virtualization_engine.NewVirtualizationEngine()
	drivenDataConnection := data_connection.NewDataConnection()
	dataSourceHandle := impl39.NewMQHandleInstance(producer)
	datasourceUseCase := impl40.NewDataSourceUseCase(datasourceRepo, drivenVirtualizationEngine, drivenDataConnection, dataSourceHandle, info_systemRepo, useCase, repo, configurationRepo)
	service2 := v1_3.NewService(datasourceUseCase)
	configurationService := configuration.NewService(configurationCase)
	saramaClient, err := kafka.NewSaramaClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	info_systemUseCase, cleanup2, err := impl41.NewInfoSystemUseCase(info_systemRepo, liyueRegistrationsRepo, useCase, repo, userServiceClient, saramaClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	service3 := v1_4.NewService(info_systemUseCase)
	iDataGradeRepo := impl42.NewDataGradeRepo(gormDB)
	standardizationStandardization := standardization.NewStandardization(client)
	dataSubject := data_subject.NewDataSubject(client)
	dataGradeCase := impl43.NewDataGrade(iDataGradeRepo, configurationRepo, standardizationStandardization, dataSubject)
	service4 := user2.NewService(dataGradeCase)
	sqlMaskingDomain := data_masking.NewSqlMaskingDomain()
	service5 := v1_5.NewService(sqlMaskingDomain)
	auditProcessBindUseCase := impl44.NewAuditProcessBindUseCase(auditProcessBindRepo, workflowWorkflow)
	audit_process_bindService := audit_process_bind.NewService(auditProcessBindUseCase)
	user_managementDrivenUserMgnt := user_management2.NewUserMgntByService(client)
	appsService := apps.NewService(appsUseCase, user_managementDrivenUserMgnt)
	businessMattersRepo := impl45.NewBusinessMattersRepo(gormDB)
	dictRepo := impl46.NewDictRepo(gormDB)
	businessMattersUseCase := impl47.NewBusinessMattersUseCase(businessMattersRepo, hydra, useCase, repo, configurationRepo, dictRepo)
	business_mattersService := business_matters.NewService(businessMattersUseCase)
	redisClient := redis2.NewRedis()
	dictUseCase := impl48.NewUseCase(dictRepo, redisClient)
	dictService := dict.NewService(dictUseCase)
	firmRepo := impl49.NewRepo(gormDB)
	firmUseCase := impl50.NewUseCase(firmRepo, gormDB)
	service6 := v1_6.NewService(firmUseCase)
	repository := front_end_processor.NewRepository(gormDB)
	docAuditRestV1Interface, err := v1_7.NewForHTTPClient(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	front_end_processorUseCase := front_end_processor2.New(auditProcessBindRepo, repo, repository, iUserRepo, docAuditRestV1Interface, workflowInterface, info_systemRepo, workflowWorkflow, useCase)
	front_end_processorService := front_end_processor3.New(front_end_processorUseCase)
	menuRepo := impl51.NewMenuRepo(gormDB)
	session := impl52.NewSession(redisClient)
	menuUseCase := impl53.NewUseCase(menuRepo, configurationRepo, resourceRepo, session, useCase, permissionRepo, authorizationDriven)
	menuService := menu.NewService(menuUseCase)
	repo2 := impl54.NewRepo(gormDB)
	useCase2 := impl55.NewUseCase(repo2, gormDB)
	service7 := v1_8.NewService(useCase2)
	repo3 := impl56.NewRepo(gormDB)
	object_main_businessUseCase := impl57.NewUseCase(repo3, repo)
	object_main_businessService := object_main_business.NewService(object_main_businessUseCase)
	alarm_ruleRepo := impl58.NewRepo(gormDB)
	alarm_ruleUseCase := impl59.NewUseCase(alarm_ruleRepo, gormDB, producer)
	service8 := v1_9.NewService(alarm_ruleUseCase)
	domain := permission.New(permissionRepo)
	service9 := v1_10.NewService(domain)
	iRepository := impl60.NewRepository(gormDB)
	iService := impl61.NewUseCase(cephClient, iRepository)
	carouselsService := carousels.NewService(iService)
	news_policyUseCase := impl62.NewRepo(gormDB)
	useCase3 := impl63.NewUseCase(news_policyUseCase, cephClient, iUserRepo)
	service10 := v1_11.NewService(useCase3)
	auditPolicyRepo := impl64.NewAuditPolicyRepo(gormDB)
	audit_policyAppsUseCase := impl65.NewAuditPolicyUseCase(auditPolicyRepo, useCase)
	audit_policyService := audit_policy.NewService(audit_policyAppsUseCase)
	registerUseCase := impl66.NewRepo(gormDB)
	useCase4 := impl67.NewUseCase(registerUseCase, iUserRepo, drivenUserMgnt, userServiceClient, repo)
	service11 := v1_12.NewService(useCase4, business_structureUseCase, useCase, userServiceClient)
	sms_confUseCase := impl68.NewUseCase(configurationRepo, gormDB)
	service12 := v1_13.NewService(sms_confUseCase)
	router := &driver.Router{
		BusinessStructureApi:  service,
		CodeGenerationRuleApi: v1Service,
		FlowchartApi:          flowchartService,
		RoleApiV2:             v2Service,
		ToolApi:               toolService,
		UserApi:               userService,
		Middleware:            middlewareMiddleware,
		DataSource:            service2,
		ConfigurationApi:      configurationService,
		InfoSystemApi:         service3,
		DataGrade:             service4,
		DataMasking:           service5,
		AuditProcessBindApi:   audit_process_bindService,
		AppsApi:               appsService,
		BusinessMattersApi:    business_mattersService,
		DictApi:               dictService,
		FirmApi:               service6,
		FrontEndProcessor:     front_end_processorService,
		MenuApi:               menuService,
		AddressBookApi:        service7,
		ObjectMainBusinessApi: object_main_businessService,
		AlarmRuleApi:          service8,
		PermissionApi:         service9,
		CarouselsApi:          carouselsService,
		NewsPolicyApi:         service10,
		AuditPolicysApi:       audit_policyService,
		RegistrationsApi:      service11,
		SMSConfApi:            service12,
	}
	restServer := driver.NewHttpServer(server, router)
	app := newApp(restServer, workflowInterface)
	handler := user_mgm.NewHandler(flowchartUseCase, business_structureUseCase, useCase)
	departmentHandler := department.NewHandler(business_structureUseCase)
	datasourceHandler := datasource.NewHandler(datasourceUseCase, datasourceRepo, dataSourceHandle)
	implMQ, err := mq.NewMQ(handler, departmentHandler, datasourceHandler)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	entityChangeTransport := callbacks.NewEntityChangeTransport(producer)
	transports := callbacks.NewTransport(gormDB, entityChangeTransport)
	wfStarter := workflow.NewWFStarter(workflowInterface, client)
	appRunner, err := NewAppRunnerWithInit(app, implMQ, transports, wfStarter, configurationCase)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return appRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}
