// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/auth_service (interfaces: Repo)
//
// Generated by this command:
//
//	mockgen -destination=auth_service.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/auth_service Repo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth_service "github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/auth_service"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=auth_service.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/dsg/services/apps/data-catalog/adapter/driven/auth_service Repo

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockRepo) Enforce(arg0 context.Context, arg1 []auth_service.PolicyEnforce) ([]auth_service.PolicyEnforceEffect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enforce", arg0, arg1)
	ret0, _ := ret[0].([]auth_service.PolicyEnforceEffect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockRepoMockRecorder) Enforce(arg0, arg1 any) *MockRepoEnforceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockRepo)(nil).Enforce), arg0, arg1)
	return &MockRepoEnforceCall{Call: call}
}

// MockRepoEnforceCall wrap *gomock.Call
type MockRepoEnforceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepoEnforceCall) Return(arg0 []auth_service.PolicyEnforceEffect, arg1 error) *MockRepoEnforceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepoEnforceCall) Do(f func(context.Context, []auth_service.PolicyEnforce) ([]auth_service.PolicyEnforceEffect, error)) *MockRepoEnforceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepoEnforceCall) DoAndReturn(f func(context.Context, []auth_service.PolicyEnforce) ([]auth_service.PolicyEnforceEffect, error)) *MockRepoEnforceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSubjectObjects mocks base method.
func (m *MockRepo) GetSubjectObjects(arg0 context.Context, arg1 auth_service.GetObjectsOptions) (*auth_service.ObjectWithPermissionsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubjectObjects", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.ObjectWithPermissionsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubjectObjects indicates an expected call of GetSubjectObjects.
func (mr *MockRepoMockRecorder) GetSubjectObjects(arg0, arg1 any) *MockRepoGetSubjectObjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubjectObjects", reflect.TypeOf((*MockRepo)(nil).GetSubjectObjects), arg0, arg1)
	return &MockRepoGetSubjectObjectsCall{Call: call}
}

// MockRepoGetSubjectObjectsCall wrap *gomock.Call
type MockRepoGetSubjectObjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepoGetSubjectObjectsCall) Return(arg0 *auth_service.ObjectWithPermissionsList, arg1 error) *MockRepoGetSubjectObjectsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepoGetSubjectObjectsCall) Do(f func(context.Context, auth_service.GetObjectsOptions) (*auth_service.ObjectWithPermissionsList, error)) *MockRepoGetSubjectObjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepoGetSubjectObjectsCall) DoAndReturn(f func(context.Context, auth_service.GetObjectsOptions) (*auth_service.ObjectWithPermissionsList, error)) *MockRepoGetSubjectObjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
