// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/af-sailor-service/v1/comprehension": {
            "get": {
                "description": "获取数据理解",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据理解"
                ],
                "summary": "获取数据理解",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "目录的ID",
                        "name": "catalogID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/af-sailor-service/v1/comprehension/config": {
            "get": {
                "description": "数据理解智能配置文件",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据理解"
                ],
                "summary": "数据理解智能配置文件",
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/comprehension.ThinkingConfig"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "数据理解智能配置文件",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据理解"
                ],
                "summary": "数据理解智能配置文件",
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/af-sailor-service/v1/tools/knowledge-network/graph/iframe": {
            "get": {
                "description": "图分析结果查询",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认知工具"
                ],
                "summary": "数据资产图谱呈现",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "实体类的名称",
                        "name": "entity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "属性id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "属性名称",
                        "name": "prop_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务的名称",
                        "name": "service_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/recommend/asset/search": {
            "get": {
                "description": "AF数据资产认知搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能搜索"
                ],
                "summary": "AF数据资产认知搜索",
                "parameters": [
                    {
                        "description": "资产认知搜索请求参数",
                        "name": "reqData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.AssetSearchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/recommend.AssetSearchResp"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/recommend/check/code": {
            "post": {
                "description": "字段标准一致性校验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能推荐"
                ],
                "summary": "字段标准一致性校验",
                "parameters": [
                    {
                        "description": "字段标准一致性校验请求参数",
                        "name": "reqData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.CheckCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/recommend.CheckCodeResp"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/recommend/code": {
            "post": {
                "description": "字段标准推荐",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能推荐"
                ],
                "summary": "字段标准推荐",
                "parameters": [
                    {
                        "description": "字段标准推荐请求参数",
                        "name": "reqData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.FieldStandardRecommendationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/recommend.FieldStandardRecommendationResp"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/recommend/flow": {
            "post": {
                "description": "流程图推荐",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能推荐"
                ],
                "summary": "流程图推荐",
                "parameters": [
                    {
                        "description": "流程图推荐请求参数",
                        "name": "reqData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.FlowRecommendationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/recommend.FlowRecommendationResp"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/recommend/table": {
            "post": {
                "description": "表单推荐",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能推荐"
                ],
                "summary": "表单推荐",
                "parameters": [
                    {
                        "description": "表单推荐请求参数",
                        "name": "reqData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.TableRecommendationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/recommend.TableRecommendationResp"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/tools/knowledge-network/alg-server/explore/kgs/neighbors": {
            "post": {
                "description": "AD图谱邻居搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认知工具"
                ],
                "summary": "AD图谱邻居搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "图谱类型",
                        "name": "kg_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "steps",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "vid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/alg_server.NeighborsResp"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/tools/knowledge-network/alg-server/graph-search/kgs/full-text": {
            "post": {
                "description": "AD图谱全文搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认知工具"
                ],
                "summary": "AD图谱全文搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "kg_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "图谱类型",
                        "name": "kg_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "$ref": "#/definitions/alg_server.FullTextResp"
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        },
        "/api/internal/af-sailor-service/v1/tools/large_language_model/sample_data": {
            "post": {
                "description": "样例数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认知工具"
                ],
                "summary": "样例数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "样例数据参数",
                        "name": "reqData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/intelligence.SampleDataReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应参数",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Res": {
                                            "$ref": "#/definitions/intelligence.SampleDataResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "失败响应参数",
                        "schema": {
                            "$ref": "#/definitions/rest.HttpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "alg_server.FullTextResp": {
            "type": "object",
            "properties": {
                "res": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer"
                        },
                        "result": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "alias": {
                                        "type": "string"
                                    },
                                    "color": {
                                        "type": "string"
                                    },
                                    "icon": {
                                        "type": "string"
                                    },
                                    "tag": {
                                        "type": "string"
                                    },
                                    "vertexs": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "color": {
                                                    "type": "string"
                                                },
                                                "default_property": {
                                                    "type": "object",
                                                    "properties": {
                                                        "a": {
                                                            "type": "string"
                                                        },
                                                        "n": {
                                                            "type": "string"
                                                        },
                                                        "v": {
                                                            "type": "string"
                                                        }
                                                    }
                                                },
                                                "icon": {
                                                    "type": "string"
                                                },
                                                "id": {
                                                    "type": "string"
                                                },
                                                "properties": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "props": {
                                                                "type": "array",
                                                                "items": {
                                                                    "type": "object",
                                                                    "properties": {
                                                                        "alias": {
                                                                            "type": "string"
                                                                        },
                                                                        "name": {
                                                                            "type": "string"
                                                                        },
                                                                        "type": {
                                                                            "type": "string"
                                                                        },
                                                                        "value": {
                                                                            "type": "string"
                                                                        }
                                                                    }
                                                                }
                                                            },
                                                            "tag": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                },
                                                "tags": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "alg_server.NeighborsResp": {
            "type": "object",
            "properties": {
                "res": {
                    "type": "object",
                    "properties": {
                        "v_count": {
                            "type": "integer"
                        },
                        "v_result": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "alias": {
                                        "type": "string"
                                    },
                                    "color": {
                                        "type": "string"
                                    },
                                    "icon": {
                                        "type": "string"
                                    },
                                    "tag": {
                                        "type": "string"
                                    },
                                    "vertexes": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "default_property": {
                                                    "type": "object",
                                                    "properties": {
                                                        "a": {
                                                            "type": "string"
                                                        },
                                                        "n": {
                                                            "type": "string"
                                                        },
                                                        "v": {
                                                            "type": "string"
                                                        }
                                                    }
                                                },
                                                "id": {
                                                    "type": "string"
                                                },
                                                "in_edges": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                },
                                                "out_edges": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                },
                                                "properties": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "props": {
                                                                "type": "array",
                                                                "items": {
                                                                    "type": "object",
                                                                    "properties": {
                                                                        "alias": {
                                                                            "type": "string"
                                                                        },
                                                                        "name": {
                                                                            "type": "string"
                                                                        },
                                                                        "type": {
                                                                            "type": "string"
                                                                        },
                                                                        "value": {
                                                                            "type": "string"
                                                                        }
                                                                    }
                                                                }
                                                            },
                                                            "tag": {
                                                                "type": "string"
                                                            }
                                                        }
                                                    }
                                                },
                                                "tags": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "client.AssetSearchAnswerEntity": {
            "type": "object",
            "properties": {
                "entity": {
                    "$ref": "#/definitions/client.AssetSearchEntity"
                },
                "score": {
                    "type": "number"
                },
                "starts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.SearchStartInfo"
                    }
                },
                "subgraph": {
                    "$ref": "#/definitions/client.GraphSynSearchSubgraphPath"
                },
                "total_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "client.AssetSearchData": {
            "type": "object",
            "properties": {
                "class_count_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.ClassCountInfo"
                    }
                },
                "entities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.AssetSearchAnswerEntity"
                    }
                },
                "query_cuts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.QueryCut"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "word_count_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.WordCountInfo"
                    }
                }
            }
        },
        "client.AssetSearchEntity": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "data_owner": {
                    "type": "string"
                },
                "datacatalogid": {
                    "type": "string"
                },
                "datacatalogname": {
                    "type": "string"
                },
                "datasource": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "description_name": {
                    "type": "string"
                },
                "metadata_schema": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "vid": {
                    "type": "string"
                }
            }
        },
        "client.ClassCountInfo": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "class_name": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "entity_count_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.EntityCountInfo"
                    }
                },
                "entity_counter": {
                    "$ref": "#/definitions/client.Counter"
                }
            }
        },
        "client.Counter": {
            "type": "object"
        },
        "client.EntityCountInfo": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "client.GraphSynSearchSubgraphPath": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "starts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "client.QueryCut": {
            "type": "object",
            "properties": {
                "is_stopword": {
                    "type": "boolean"
                },
                "source": {
                    "type": "string"
                },
                "synonym": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "client.SearchConfigItem": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.SearchProp"
                    }
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "client.SearchProp": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "f_db_type f_tb_name f_db_name",
                    "type": "string"
                },
                "op_value": {
                    "type": "string"
                },
                "operation": {
                    "description": "eq",
                    "type": "string"
                }
            }
        },
        "client.SearchStartInfo": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "class_name": {
                    "description": "Synonyms []struct {\n\tSource  string   ` + "`" + `json:\"source\"` + "`" + `\n\tSynonym []string ` + "`" + `json:\"synonym\"` + "`" + `\n} ` + "`" + `json:\"synonyms\"` + "`" + `",
                    "type": "string"
                },
                "hit": {
                    "type": "object",
                    "properties": {
                        "alias": {
                            "type": "string"
                        },
                        "keys": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "prop": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "client.StopEntityInfo": {
            "type": "object",
            "properties": {
                "class_name": {
                    "type": "string"
                },
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "client.WordCountInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "isSynonym": {
                    "type": "boolean"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "comprehension.Process": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "查询配置"
                },
                "desc": {
                    "description": "流程配置名称",
                    "type": "string"
                },
                "format": {
                    "description": "答案格式",
                    "type": "string"
                },
                "way": {
                    "description": "查询方式",
                    "type": "string"
                }
            }
        },
        "comprehension.Thinking": {
            "type": "object",
            "properties": {
                "break_through": {
                    "description": "遇到错误，处理为空是否继续，默认不继续",
                    "type": "boolean"
                },
                "child": {
                    "description": "思路分叉，执行每个分叉是由条件的",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comprehension.Thinking"
                    }
                },
                "condition": {
                    "description": "执行该节点的条件",
                    "type": "string"
                },
                "filter_previous": {
                    "description": "过滤掉的前序指",
                    "type": "string"
                },
                "inputs": {
                    "description": "输入的数据",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "loop_data_key": {
                    "description": "循环key",
                    "type": "string"
                },
                "process": {
                    "description": "当前节点的思考",
                    "$ref": "#/definitions/comprehension.Process"
                }
            }
        },
        "comprehension.ThinkingConfig": {
            "type": "object",
            "properties": {
                "cache_key": {
                    "description": "需要缓存处理的key,  值：id,name,column_infos 表示隐藏ID，使用name去缓存补充column_infos中的ID",
                    "type": "string"
                },
                "cache_thinking": {
                    "description": "需要缓存的配置节点，逗号分割符",
                    "type": "string"
                },
                "result_key": {
                    "description": "最终结果的key",
                    "type": "string"
                },
                "tag": {
                    "description": "标签，思考的是那件事情",
                    "type": "string"
                },
                "thinking": {
                    "description": "思考配置和过程",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comprehension.Thinking"
                    }
                }
            }
        },
        "intelligence.SampleDataReq": {
            "type": "object",
            "required": [
                "titles"
            ],
            "properties": {
                "differs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "example": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/intelligence.SampleItem"
                    }
                },
                "titles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "intelligence.SampleDataResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "sample_data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/intelligence.SampleItem"
                    }
                }
            }
        },
        "intelligence.SampleItem": {
            "type": "object",
            "additionalProperties": {}
        },
        "recommend.AssetSearchReq": {
            "type": "object",
            "required": [
                "query"
            ],
            "properties": {
                "asset_type": {
                    "description": "资产分类",
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                },
                "data_kind": {
                    "description": "属性相关的",
                    "type": "array",
                    "maxItems": 10,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "end_time": {
                    "description": "结束时间，秒时间戳",
                    "type": "integer",
                    "minimum": 0,
                    "example": 1682586655
                },
                "last_id": {
                    "description": "最后一个结果的ID",
                    "type": "string"
                },
                "last_score": {
                    "description": "最后一个结果的分数",
                    "type": "number",
                    "minimum": 0
                },
                "limit": {
                    "description": "每次返回的数量",
                    "type": "integer",
                    "maximum": 100
                },
                "query": {
                    "description": "输入的查询内容",
                    "type": "string"
                },
                "shared_type": {
                    "description": "共享属性 1 无条件共享 2 有条件共享 3 不予共享",
                    "type": "array",
                    "maxItems": 10,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        2
                    ]
                },
                "start_time": {
                    "description": "开始时间，秒时间戳",
                    "type": "integer",
                    "minimum": 0,
                    "example": 1682586655
                },
                "stop_entities": {
                    "description": "智能搜索维度, 停用的实体类别",
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "datacatalog"
                    ]
                },
                "stop_entity_infos": {
                    "description": "智能搜索维度, 停用的实体点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.StopEntityInfo"
                    }
                },
                "stopwords": {
                    "description": "智能搜索对象，停用词",
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "应用"
                    ]
                },
                "update_cycle": {
                    "description": "更新频率 参考数据字典：GXZQ，1不定时 2实时 3每日 4每周 5每月 6每季度 7每半年 8每年 9其他",
                    "type": "array",
                    "maxItems": 10,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        3,
                        7
                    ]
                }
            }
        },
        "recommend.AssetSearchResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/client.AssetSearchData"
                }
            }
        },
        "recommend.CheckCodeReq": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "table_fields": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "field_id": {
                                            "type": "string"
                                        },
                                        "standard_id": {
                                            "type": "string"
                                        },
                                        "table_field_name": {
                                            "type": "string"
                                        },
                                        "table_field_range": {
                                            "type": "string"
                                        },
                                        "table_field_type": {
                                            "type": "string"
                                        }
                                    }
                                }
                            },
                            "table_id": {
                                "type": "string"
                            },
                            "table_name": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "recommend.CheckCodeResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "fields_check_result": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "consistent": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "field_id": {
                                                        "type": "string"
                                                    },
                                                    "table_id": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        },
                                        "field_id": {
                                            "type": "string"
                                        },
                                        "inconsistent": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "fields": {
                                                        "type": "array",
                                                        "items": {
                                                            "type": "object",
                                                            "properties": {
                                                                "field_id": {
                                                                    "type": "string"
                                                                },
                                                                "table_id": {
                                                                    "type": "string"
                                                                }
                                                            }
                                                        }
                                                    },
                                                    "standard_id": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        },
                                        "standard_id": {
                                            "type": "string"
                                        }
                                    }
                                }
                            },
                            "table_id": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "recommend.FieldStandardRecommendationReq": {
            "type": "object",
            "properties": {
                "table_fields": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "table_field_name": {
                                "type": "string"
                            },
                            "table_field_type": {
                                "type": "string"
                            }
                        }
                    }
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "recommend.FieldStandardRecommendationResp": {
            "type": "object",
            "properties": {
                "table_fields": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "rec_stds": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "info": {
                                            "type": "string"
                                        },
                                        "rank": {
                                            "type": "integer"
                                        },
                                        "rec_reason": {
                                            "type": "string"
                                        },
                                        "std_ch_name": {
                                            "type": "string"
                                        },
                                        "std_code": {}
                                    }
                                }
                            },
                            "table_field_name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "recommend.FlowRecommendationReq": {
            "type": "object",
            "properties": {
                "business_model_id": {
                    "type": "string"
                },
                "flowchart": {
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "nodes": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "description": {
                                        "type": "string"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "mxcell_id": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "node": {
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "mxcell_id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "parent_node": {
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "mxcell_id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "tables": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "recommend.FlowRecommendationResp": {
            "type": "object",
            "properties": {
                "flowcharts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "hit_score": {
                                "type": "number"
                            },
                            "id": {
                                "type": "string"
                            },
                            "reason": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "recommend.TableRecommendationReq": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "code_table": {
                                "type": "string"
                            },
                            "data_accuracy": {
                                "type": "integer"
                            },
                            "data_length": {
                                "type": "integer"
                            },
                            "data_type": {
                                "type": "string"
                            },
                            "encoding_rule": {
                                "type": "string"
                            },
                            "formulate_basis": {
                                "type": "string"
                            },
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "name_en": {
                                "type": "string"
                            },
                            "standard_id": {
                                "type": "string"
                            }
                        }
                    }
                },
                "main_business_ID": {
                    "type": "string"
                },
                "table": {
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "guideline": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "resource_tag": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "source_system": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "recommend.TableRecommendationResp": {
            "type": "object",
            "properties": {
                "tables": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "hit_score": {
                                "type": "number"
                            },
                            "id": {
                                "type": "string"
                            },
                            "reason": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "response.ResResult": {
            "type": "object",
            "properties": {
                "res": {
                    "description": "返回的结构"
                }
            }
        },
        "rest.HttpError": {
            "type": "object",
            "properties": {
                "cause": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "detail": {},
                "solution": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "af-sailor-service",
	Description:      "AnyFabric af-sailor-service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
